
import { IA_TAG } from "./help-arvore.js";

// nome digitado → chave do grupo (aceita PT e EN, novos e antigos)
export const ALIAS_GRUPO = {
  // novos
  comecar: "comecar", "começar": "comecar", inicio: "comecar", start: "comecar", "getting-started": "comecar",
  proteger: "proteger", protecao: "proteger", "proteção": "proteger", protect: "proteger", protection: "proteger",
  personalizar: "personalizar", customize: "personalizar", customise: "personalizar", personalize: "personalizar",
  diversao: "diversao", "diversão": "diversao", fun: "diversao",
  rpg: "rpg", game: "rpg", jogo: "rpg", personagem: "rpg", character: "rpg",
  diagnostico: "diagnostico", "diagnóstico": "diagnostico", diagnostics: "diagnostico", problemas: "diagnostico", troubleshooting: "diagnostico",
  dono: "dono", owner: "dono",
  // antigos → onde o conteúdo foi parar
  geral: "comecar", general: "comecar",
  moderacao: "proteger", "moderação": "proteger", mod: "proteger", moderation: "proteger",
  automod: "proteger",
  config: "personalizar", configuracao: "personalizar", "configuração": "personalizar", configuration: "personalizar", settings: "personalizar",
  ferramentas: "personalizar", ferramenta: "personalizar", tools: "personalizar", tool: "personalizar",
  xp: "diversao", nivel: "diversao", niveis: "diversao", "níveis": "diversao", level: "diversao", levels: "diversao",
};

// Ordem fixa dos grupos no índice e nas páginas.
export const ORDEM = ["comecar", "proteger", "personalizar", "diversao", "rpg", "diagnostico"];

export function grupos(P, lang = "pt") {
  return lang === "en" ? gruposEN(P) : gruposPT(P);
}

function gruposPT(P) {
  return {
    comecar: {
      emoji: "🚀", titulo: "Começar",
      resumo: "acabou de adicionar o bot? comece aqui",
      linhas: [
        "**Os três primeiros comandos**",
        `\`${P}assistente\` — ⭐ configuração **guiada**: o bot pergunta, você responde, pronto`,
        `\`${P}tutorial\` — guia em páginas: permissões, canais, proteção, boas-vindas…`,
        `\`${P}config\` — panorama de tudo que está configurado neste servidor`,
        "",
        "**Regra de ouro dos canais**",
        "A permissão **do canal** vence a **do cargo**. Se o canal nega, o cargo não salva.",
        `Veja os 3 tipos de canal em \`${P}tutorial canais\` — resolve 80% dos "por que não funciona".`,
        "",
        "**Do dia a dia**",
        `\`${P}idioma pt|en\` — idioma do bot neste servidor *(ManagePermissions)*`,
        `\`${P}staff\` — quem é a equipe (os cargos com acesso aos comandos)`,
        `\`${P}userinfo [@pessoa]\` — ID, data de entrada e cargos`,
        `\`${P}sobre\` · \`${P}ping\` — informações e latência do bot`,
        `\`${P}repete <texto>\` — o bot repete (anúncios rápidos)`,
      ],
    },

    proteger: {
      emoji: "🛡️", titulo: "Proteger",
      resumo: "spam, golpe, links, invasão e punições",
      linhas: [
        "**Automático** *(ManagePermissions)*",
        `\`${P}automod\` — os 4 grupos: antispam, antiruido, antilink, sentinela — e as partes de cada um`,
        `\`${P}automod <grupo> on|off\` · \`${P}automod <grupo> <parte> on|off\` — o grupo inteiro ou só uma parte`,
        `\`${P}automod sentinela\` — o que **julga** conteúdo (golpe, +18, gore, ódio, imagens de conta nova)`,
        `\`${P}automod punicao modo <avisar|apagar|confirmar|acumular|banir>\` — o que acontece com quem infringe`,
        `\`${P}automod punicao escada\` — os degraus do modo \`acumular\` (aviso → mute → ban)`,
        `\`${P}banglobal <off|avisar|banir>\` — o que fazer com quem já foi banido em outro servidor *(BanMembers)*`,
        `\`${P}automod whitelist\` · \`${P}automod blocklist\` — convites permitidos · domínios proibidos`,
        `\`${P}modia\` — moderação por IA, com critérios em texto livre *(ManageServer)*` + IA_TAG,
        "",
        "**Manual**",
        `\`${P}warn @pessoa [motivo]\` — aviso (conta na escada) *(KickMembers)*`,
        `\`${P}warn lista [@pessoa]\` · \`${P}warn limpar @pessoa\` — ver e zerar avisos`,
        `\`${P}silenciar @pessoa <tempo> [motivo]\` — silêncio nativo do Stoat por um tempo *(TimeoutMembers)*`,
        `\`${P}kick @pessoa [motivo]\` · \`${P}ban @pessoa [motivo]\``,
        `\`${P}limpar <n> [@pessoa]\` — apaga mensagens *(ManageMessages)*`,
        "",
        "**Quem modera e onde**",
        `\`${P}acesso cargo add @cargo\` — dá acesso aos comandos de moderação`,
        `\`${P}acesso canal somente\` + \`${P}acesso canal add #canal\` — comandos só em certos canais`,
      ],
    },

    personalizar: {
      emoji: "🎨", titulo: "Personalizar",
      resumo: "boas-vindas, cargos, cores, embeds, logs, notícias",
      linhas: [
        "**Entrada e saída** *(ManageMessages)*",
        `\`${P}boasvindas canal aqui\` — embed quando alguém entra (\`${P}help boasvindas\` explica cada parâmetro)`,
        `\`${P}adeus canal aqui\` — embed quando alguém sai`,
        `\`${P}autorole <cargo>\` — cargo automático a quem entra *(ManageRole)*`,
        "",
        "**Cargos** *(ManageRole)*",
        `\`${P}reactionrole add <mensagem> <emoji> <cargo>\` — cargo por reação`,
        `\`${P}cor <cargo> <cor|gradiente>\` — cor dos cargos, inclusive gradiente`,
        `\`${P}cor painel aqui\` — painel "escolha sua cor" pronto, num comando`,
        "",
        "**Mensagens e registro**",
        `\`${P}embed titulo: … | descricao: …\` — publica um embed bonito *(ManageMessages)*`,
        `\`${P}log canal aqui\` — onde o bot registra o que aconteceu *(ManagePermissions)*`,
        `\`${P}rss add <url>\` — curadoria de notícias num canal`,
        `\`${P}fuso add <cidade>\` — relógio com várias cidades`,
        `\`${P}webhook criar <nome> [#canal]\` — GitHub, Crafty/Minecraft e afins publicando nos seus canais, um gancho por assunto`,
        `\`${P}rolar 2d20kh1+5\` — dados de RPG completos (vantagem, explosão, sucessos, Fate) · \`${P}iniciativa\` — ordem de combate`,
        `\`${P}ticket painel #canal\` — painel em que se **reage** para abrir um ticket; 🔒 (staff) trava e manda o registro .txt ao log`,
        "",
        "**O próprio bot**",
        `\`${P}comando desativar|ativar <nome>\` — liga/desliga um comando neste servidor`,
        `\`${P}idioma pt|en\` — idioma das respostas`,
      ],
    },

    diversao: {
      emoji: "🎮", titulo: "Diversão",
      resumo: "níveis por XP, a moeda do servidor, conversa com a Judy, voz",
      resumoSemIA: "níveis por XP, a moeda do servidor e voz",
      linhas: [
        "**Níveis (XP por mensagem)**",
        `\`${P}xp\` — seu nível e progresso · \`${P}xp rank [@pessoa]\``,
        `\`${P}xp top\` — ranking do servidor`,
        `\`${P}economia\` — a moeda do servidor: \`minerar\`, \`top\`, \`loja\` de cargos e \`comprar\``,
        `\`${P}xp setup\` — configurar: cargos por nível, multiplicador, canal de anúncio *(ManagePermissions)*`,
        `\`${P}xp criarcargos\` — cria os cargos de nível sozinho`,
        "",
        "**Judy (IA)**" + IA_TAG,
        `\`${P}chat <mensagem>\` — conversa (ou só mencione o bot)` + IA_TAG,
        `\`${P}chat livre on|off\` — ela entra sozinha na conversa deste canal` + IA_TAG,
        `\`${P}chat comentar aqui|off\` — comenta por iniciativa própria` + IA_TAG,
        `\`${P}chat perfil [@pessoa]\` · \`${P}chat esquecer [tudo]\` — o que ela lembra` + IA_TAG,
        `\`${P}personalidade\` — vê/define o prompt de personalidade da IA *(ManageServer)*` + IA_TAG,
        "",
        "**Voz**",
        `\`${P}entrar\` — de qualquer canal: ela entra na sua call e lê o canal onde você digitou (\`${P}sair\` desfaz)`,
        `\`${P}tts <texto>\` — ou só uma frase específica`,
        `\`${P}musica <link ou nome>\` — música na call (YouTube, SoundCloud, Spotify) com fila, skip e volume — e ela abaixa sozinha quando o TTS fala`,
        "",
        `_O RPG é outro sistema, com personagem, mercado e moedas próprios: \`${P}help rpg\`._`,
      ],
    },

    rpg: {
      emoji: "🎲", titulo: "RPG",
      resumo: "personagem, missões, companheiros e mercado",
      linhas: [
        "**Personagem**",
        `\`${P}game criar [nome]\` — cria · \`${P}game\` — sua ficha · \`${P}game ficha [@pessoa]\``,
        `\`${P}game pontos <atributo> [quantos]\` — distribui pontos (for, int, sor…)`,
        `\`${P}game magias\` · \`${P}game aprender <nome>\` — grimório`,
        `\`${P}game top\` — ranking · \`${P}game apagar confirmar\` — recomeça`,
        "",
        "**Aventura**",
        `\`${P}game missao\` — missões e suas chances · \`${P}game missao <nome>\` — parte`,
        `\`${P}game coop abrir <missão>\` — chama até 4 pessoas para a dungeon · \`${P}game coop entrar\``,
        `\`${P}game resetar pontos\` — devolve os pontos gastos para redistribuir (custa Ouro)`,
        `\`${P}game followers\` · \`${P}game recrutas\` · \`${P}game contratar [nome]\` — companheiros`,
        `\`${P}game follower levar|tirar <nome>\` — monta a party · \`${P}game follower ficha <nome>\``,
        `\`${P}game dungeon\` — quem está capturado · \`${P}game descansar\` — energia`,
        "",
        "**Itens**",
        `\`${P}game itens\` — mochila · \`${P}game item <nome>\` · \`${P}game catalogo [raridade|slot]\``,
        `\`${P}game equipar <item>\` · \`${P}game desequipar <slot|item>\``,
        "",
        "**Mercado e moedas do jogo**",
        `\`${P}game carteira\` · \`${P}game comprar [item]\` · \`${P}game vender <item>\``,
        `\`${P}game mercado\` — bazar entre jogadores · \`${P}game trocar\` — escambo`,
        `\`${P}game cambio <qtd> <moeda> [para <moeda>]\` — câmbio com o banco`,
        "",
        `_O RPG é um mundo só, igual em todo servidor — a wiki: \`${P}tutorial game\`. Não confundir com \`${P}xp\`._`,
      ],
    },

    diagnostico: {
      emoji: "🔧", titulo: "Diagnóstico",
      resumo: "quando algo não funciona",
      linhas: [
        `\`${P}debug\` — **o diagnóstico completo**: o que está quebrado primeiro, depois permissões, hierarquia, canais, voz e IA`,
        `\`${P}debug @pessoa\` — o que o bot consegue fazer com essa pessoa (punir, silenciar, cargos de nível)`,
        `\`${P}debug #canal\` — a conta de permissão do bot nesse canal (permissão de canal > cargo!)`,
        `\`${P}config\` — panorama de tudo que está ligado`,
        `\`${P}automod status\` · \`${P}automod sentinela\` · \`${P}automod punicao\` — estado da proteção`,
        `\`${P}reactionrole list\` · \`${P}reactionrole recarregar\` — se os cargos por reação pararam`,
        `\`${P}ping\` — o bot está respondendo?`,
        "",
        "**Os três culpados de sempre**",
        "1. Falta permissão no **canal** (não no cargo) → `debug #canal`",
        "2. O cargo do bot está **abaixo** do cargo que ele precisa mexer → suba ele na lista",
        "3. `ManageRole` ≠ `AssignRoles`: um cria cargos, o outro entrega → o bot precisa dos dois",
      ],
    },

    dono: {
      emoji: "👑", titulo: "Dono do bot",
      resumo: "só você vê esta página",
      linhas: [
        `\`${P}servidores\` — cada servidor: nome, membros, mensagens por minuto`,
        `\`${P}game admin\` — ferramentas de teste e moedas do RPG (\`${P}help game admin\`)`,
        `\`${P}automod debug on|off\` — log detalhado do automod (global)`,
        `\`${P}banglobal revisar\` — revisa a lista global`,
        "",
        "_A IA (\`chat\`, \`modia\`, comentário espontâneo) roda só nos servidores de `CHAT_SERVIDORES`._" + IA_TAG,
      ],
    },
  };
}

function gruposEN(P) {
  return {
    comecar: {
      emoji: "🚀", titulo: "Getting started",
      resumo: "just added the bot? start here",
      linhas: [
        "**The first three commands**",
        `\`${P}assistente\` — ⭐ **guided** setup: the bot asks, you answer, done`,
        `\`${P}tutorial\` — paged guide: permissions, channels, protection, welcome…`,
        `\`${P}config\` — overview of everything configured on this server`,
        "",
        "**The golden rule of channels**",
        "**Channel** permissions beat **role** permissions. If the channel denies it, the role can't save it.",
        `See the 3 channel types in \`${P}tutorial canais\` — it solves 80% of "why doesn't it work".`,
        "",
        "**Everyday**",
        `\`${P}idioma pt|en\` — the bot's language on this server *(ManagePermissions)*`,
        `\`${P}staff\` — who the team is (the roles with command access)`,
        `\`${P}userinfo [@user]\` — ID, join date and roles`,
        `\`${P}sobre\` · \`${P}ping\` — bot info and latency`,
        `\`${P}repete <text>\` — the bot repeats it (quick announcements)`,
      ],
    },

    proteger: {
      emoji: "🛡️", titulo: "Protect",
      resumo: "spam, scams, links, raids and punishments",
      linhas: [
        "**Automatic** *(ManagePermissions)*",
        `\`${P}automod\` — the 4 groups: antispam, antiruido, antilink, sentinela — and each one's parts`,
        `\`${P}automod <group> on|off\` · \`${P}automod <group> <part> on|off\` — the whole group or one part`,
        `\`${P}automod sentinela\` — what **judges** content (scams, NSFW, gore, hate, new accounts' images)`,
        `\`${P}automod punicao modo <avisar|apagar|confirmar|acumular|banir>\` — what happens to offenders`,
        `\`${P}automod punicao escada\` — the steps of \`acumular\` mode (warning → mute → ban)`,
        `\`${P}banglobal <off|avisar|banir>\` — what to do with people banned on other servers *(BanMembers)*`,
        `\`${P}automod whitelist\` · \`${P}automod blocklist\` — allowed invites · forbidden domains`,
        `\`${P}modia\` — AI moderation with free-text criteria *(ManageServer)*` + IA_TAG,
        "",
        "**Manual**",
        `\`${P}warn @user [reason]\` — warning (counts on the ladder) *(KickMembers)*`,
        `\`${P}warn lista [@user]\` · \`${P}warn limpar @user\` — see and clear warnings`,
        `\`${P}silenciar @user <time> [reason]\` — Stoat's native timeout *(TimeoutMembers)*`,
        `\`${P}kick @user [reason]\` · \`${P}ban @user [reason]\``,
        `\`${P}limpar <n> [@user]\` — deletes messages *(ManageMessages)*`,
        "",
        "**Who moderates and where**",
        `\`${P}acesso cargo add @role\` — grants access to moderation commands`,
        `\`${P}acesso canal somente\` + \`${P}acesso canal add #channel\` — commands only in chosen channels`,
      ],
    },

    personalizar: {
      emoji: "🎨", titulo: "Customize",
      resumo: "welcome, roles, colors, embeds, logs, news",
      linhas: [
        "**Join and leave** *(ManageMessages)*",
        `\`${P}boasvindas canal aqui\` — embed when someone joins (\`${P}help boasvindas\` explains every parameter)`,
        `\`${P}adeus canal aqui\` — embed when someone leaves`,
        `\`${P}autorole <role>\` — automatic role on join *(ManageRole)*`,
        "",
        "**Roles** *(ManageRole)*",
        `\`${P}reactionrole add <message> <emoji> <role>\` — reaction roles`,
        `\`${P}cor <role> <color|gradient>\` — role colors, gradients included`,
        `\`${P}cor painel aqui\` — a ready-made "pick your color" panel, in one command`,
        "",
        "**Messages and logging**",
        `\`${P}embed titulo: … | descricao: …\` — posts a pretty embed *(ManageMessages)*`,
        `\`${P}log canal aqui\` — where the bot writes down what happened *(ManagePermissions)*`,
        `\`${P}rss add <url>\` — news curation in a channel`,
        `\`${P}fuso add <city>\` — clock with several cities`,
        `\`${P}webhook criar <name> [#channel]\` — GitHub, Crafty/Minecraft and friends posting into your channels, one hook per subject`,
        `\`${P}rolar 2d20kh1+5\` — full tabletop dice (advantage, exploding, successes, Fate) · \`${P}iniciativa\` — combat order`,
        `\`${P}ticket painel #channel\` — a panel people **react** on to open a ticket; 🔒 (staff) locks it and sends the .txt record to the log`,
        "",
        "**The bot itself**",
        `\`${P}comando disable|enable <name>\` — toggles a command on this server`,
        `\`${P}idioma pt|en\` — language of the replies`,
      ],
    },

    diversao: {
      emoji: "🎮", titulo: "Fun",
      resumo: "XP levels, the server currency, chatting with Judy, voice",
      resumoSemIA: "XP levels, the server currency and voice",
      linhas: [
        "**Levels (message XP)**",
        `\`${P}xp\` — your level and progress · \`${P}xp rank [@user]\``,
        `\`${P}xp top\` — server ranking`,
        `\`${P}economia\` — the server's currency: \`minerar\`, \`top\`, the role \`loja\` and \`comprar\``,
        `\`${P}xp setup\` — configure: level roles, multiplier, announcement channel *(ManagePermissions)*`,
        `\`${P}xp criarcargos\` — creates the level roles by itself`,
        "",
        "**Judy (AI)**" + IA_TAG,
        `\`${P}chat <message>\` — talk (or just mention the bot)` + IA_TAG,
        `\`${P}chat livre on|off\` — she joins this channel's conversation on her own` + IA_TAG,
        `\`${P}chat comentar aqui|off\` — comments on her own initiative` + IA_TAG,
        `\`${P}personality\` — view/set the AI personality prompt *(ManageServer)*` + IA_TAG,
        `\`${P}chat perfil [@user]\` · \`${P}chat esquecer [tudo]\` — what she remembers` + IA_TAG,
        "",
        "**Voice**",
        `\`${P}entrar\` — from any channel: she joins your call and reads the channel where you typed it (\`${P}sair\` undoes it)`,
        `\`${P}tts <text>\` — or just one specific line`,
        `\`${P}musica <link or name>\` — music in the call (YouTube, SoundCloud, Spotify) with queue, skip and volume — it auto-ducks while TTS speaks`,
        "",
        `_The RPG is a separate system, with its own character, market and currencies: \`${P}help rpg\`._`,
      ],
    },

    rpg: {
      emoji: "🎲", titulo: "RPG",
      resumo: "character, missions, companions and market",
      linhas: [
        "**Character**",
        `\`${P}game criar [name]\` — create · \`${P}game\` — your sheet · \`${P}game ficha [@user]\``,
        `\`${P}game pontos <attribute> [amount]\` — spends points (str, int, luck…)`,
        `\`${P}game magias\` · \`${P}game aprender <name>\` — grimoire`,
        `\`${P}game top\` — ranking · \`${P}game apagar confirmar\` — start over`,
        "",
        "**Adventure**",
        `\`${P}game missao\` — missions and your odds · \`${P}game missao <name>\` — set off`,
        `\`${P}game coop abrir <mission>\` — calls up to 4 people to the dungeon · \`${P}game coop entrar\``,
        `\`${P}game resetar pontos\` — gives back the spent points to redistribute (costs Gold)`,
        `\`${P}game followers\` · \`${P}game recrutas\` · \`${P}game contratar [name]\` — companions`,
        `\`${P}game follower levar|tirar <name>\` — builds the party · \`${P}game follower ficha <name>\``,
        `\`${P}game dungeon\` — who's captured · \`${P}game descansar\` — energy`,
        "",
        "**Items**",
        `\`${P}game itens\` — backpack · \`${P}game item <name>\` · \`${P}game catalogo [rarity|slot]\``,
        `\`${P}game equipar <item>\` · \`${P}game desequipar <slot|item>\``,
        "",
        "**The game's market and currencies**",
        `\`${P}game carteira\` · \`${P}game comprar [item]\` · \`${P}game vender <item>\``,
        `\`${P}game mercado\` — player bazaar · \`${P}game trocar\` — bartering`,
        `\`${P}game cambio <qty> <currency> [para <currency>]\` — exchange with the bank`,
        "",
        `_The RPG is one world, the same on every server — the wiki: \`${P}tutorial game\`. Not to be confused with \`${P}xp\`._`,
      ],
    },

    diagnostico: {
      emoji: "🔧", titulo: "Diagnostics",
      resumo: "when something doesn't work",
      linhas: [
        `\`${P}debug\` — **the full diagnostics**: what's broken first, then permissions, hierarchy, channels, voice and AI`,
        `\`${P}debug @user\` — what the bot can do with that person (punish, time out, level roles)`,
        `\`${P}debug #channel\` — the bot's permission math in that channel (channel permission > role!)`,
        `\`${P}config\` — overview of everything that's on`,
        `\`${P}automod status\` · \`${P}automod sentinela\` · \`${P}automod punicao\` — protection state`,
        `\`${P}reactionrole list\` · \`${P}reactionrole recarregar\` — if reaction roles stopped`,
        `\`${P}ping\` — is the bot responding?`,
        "",
        "**The three usual suspects**",
        "1. Missing permission on the **channel** (not the role) → `debug #channel`",
        "2. The bot's role sits **below** the role it needs to touch → move it up the list",
        "3. `ManageRole` ≠ `AssignRoles`: one creates roles, the other hands them out → the bot needs both",
      ],
    },

    dono: {
      emoji: "👑", titulo: "Bot owner",
      resumo: "only you can see this page",
      linhas: [
        `\`${P}servidores\` — each server: name, members, messages per minute`,
        `\`${P}game admin\` — RPG testing and currency tools (\`${P}help game admin\`)`,
        `\`${P}automod debug on|off\` — verbose automod log (global)`,
        `\`${P}banglobal revisar\` — reviews the global list`,
        "",
        "_The AI (\`chat\`, \`modia\`, spontaneous comments) only runs on the servers in `CHAT_SERVIDORES`._" + IA_TAG,
      ],
    },
  };
}
