// ══════════════════════════════════════════════════════════
//  help-arvore.js — subtópicos do &help, um por SUBCOMANDO
//
//  O &help <comando> mostra o comando inteiro; aqui vive o nível
//  seguinte: &help <comando> <subcomando>, com a lista do que
//  existe dentro daquele subcomando e o que cada coisa faz.
//
//  Ex.: &help game admin  → todos os &game admin ...
//       &help xp setup    → todos os parâmetros do assistente
//
//  Formato: { comando: { subcomando: { titulo, texto } } }
//  `titulo` entra depois do prefixo: `📖 Ajuda — &game admin`.
//
//  Cada entrada existe em PT e EN. O idioma vem do servidor.
//  Marque com IA_TAG a linha que só faz sentido onde a IA roda —
//  o help remove essas linhas nos demais servidores.
// ══════════════════════════════════════════════════════════

// Precisa bater com a constante do geral.js (marca invisível).
export const IA_TAG = "\u200b[ia]";

// Monta a árvore completa. `P` é o prefixo do bot.
export function arvoreSubtopicos(P, lang = "pt") {
  return lang === "en" ? arvoreEN(P) : arvorePT(P);
}

// ══════════════════════════════════════════════════════════
//  PORTUGUÊS
// ══════════════════════════════════════════════════════════
function arvorePT(P) {
  return {
    // ── &game ────────────────────────────────────────────
    game: {
      admin: {
        titulo: "game admin",
        texto: [
          "**Só o dono do bot.** Ferramentas para preparar e depurar o RPG.",
          "",
          "**Dar coisas a alguém** _(sem @pessoa, é para você)_",
          `\`${P}game admin dar <qtd> [@pessoa]\` — credita moeda`,
          `\`${P}game admin item <nome> [@pessoa]\` — entrega um item do catálogo`,
          `\`${P}game admin follower <nome> [nível] [@pessoa]\` — entrega um companheiro`,
          `\`${P}game admin pontos <n> [@pessoa]\` — dá pontos livres de atributo`,
          `\`${P}game admin nivel <n> [@pessoa]\` — força o nível do personagem`,
          "",
          "**Destravar**",
          `\`${P}game admin energia [@pessoa]\` — enche a energia dos companheiros`,
          `\`${P}game admin cooldown [@pessoa]\` — zera espera de missão e recuperação`,
          "",
          "**Economia**",
          `\`${P}game admin moeda\` — cria e configura as moedas _(veja \`${P}help game moeda\`)_`,
          `\`${P}game admin eco\` — números da economia: P, multiplicador, pote`,
          `\`${P}game admin dungeon <qtd>\` — põe moeda no pote da dungeon`,
          "",
          "**Testar sem quebrar nada**",
          `\`${P}game admin teste\` — cria um personagem de teste e roda o jogo inteiro`,
          `\`${P}game admin simular <missao> [n]\` — roda a missão n vezes, sem efeito real`,
          "",
          "**Recomeçar** _(exige \`confirmar\`)_",
          `\`${P}game admin reset servidor confirmar\` — apaga o progresso`,
          `\`${P}game admin reset catalogo confirmar\` — apaga o catálogo curado`,
          `\`${P}game admin reset tudo confirmar\` — os dois`,
        ].join("\n"),
      },
      moeda: {
        titulo: "game admin moeda",
        texto: [
          "**Só o dono do bot.** As moedas do servidor — cada uma com sua própria economia.",
          "",
          "**Uma a uma, do catálogo**",
          `\`${P}game admin moeda perfil\` — as 12 moedas prontas, por grupo`,
          `\`${P}game admin moeda perfil <id>\` — adiciona · várias: \`perfil brl xau btc\``,
          "💵 Real · Dólar · Euro · Libra Esterlina",
          "🥇 Cobre · Prata · Ouro     💎 Esmeralda · Diamante",
          "₿ Monero · Ethereum · Bitcoin",
          "Todas na mesma escala de valor, então misturar é seguro: o suprimento",
          "de cada uma já nasce inverso ao valor dela.",
          "",
          "**Conjuntos fechados**",
          `\`${P}game admin moeda modelo mundo\` — Real, Dólar, Euro, Prata, Ouro, Bitcoin`,
          `\`${P}game admin moeda modelo fantasia\` — Cobre, Prata, Ouro, Cristal`,
          `\`${P}game admin moeda modelo simples\` — uma moeda só`,
          "",
          "**Uma a uma**",
          `\`${P}game admin moeda\` — lista as existentes`,
          `\`${P}game admin moeda ver <id>\` — ficha completa e quanto rende`,
          `\`${P}game admin moeda criar <id> <nome> [símbolo] [campo=valor …]\``,
          `\`${P}game admin moeda set <id> <campo> <valor>\` — ajusta um campo`,
          `\`${P}game admin moeda padrao <id>\` — define a principal (preços aparecem nela)`,
          `\`${P}game admin moeda remover <id>\` — apaga a moeda **e os saldos**`,
          `\`${P}game admin moeda duplicadas\` — funde moedas com o mesmo nome`,
          "",
          "**Duplicadas**",
          "Dois conjuntos podem trazer a mesma moeda com ids diferentes (`mundo`",
          "traz Prata como `xag`, `fantasia` como `prata`). Hoje isso é barrado na",
          "criação — e bases antigas são reparadas sozinhas no primeiro boot.",
          "A fusão **soma** saldos, estoque e pote na moeda que fica; nada some.",
          "",
          "**Campos que dá para ajustar**",
          "`dificuldade` — o quanto ela é rara nas missões",
          "`finita` — se o total em circulação tem teto",
          "`mercado` — o estoque fora das carteiras",
          "",
          `_O \`id\` é o nome curto usado nos comandos: letras e números, sem espaço._`,
        ].join("\n"),
      },
      mercado: {
        titulo: "game mercado",
        texto: [
          "Negócio **entre jogadores**, com custódia: o que você anuncia sai da sua",
          "carteira e fica comigo até fechar ou você cancelar. Sem isso, vira golpe.",
          "",
          `\`${P}game mercado\` — lista as ofertas abertas`,
          `\`${P}game mercado vender <item> <preço>\` — anuncia um item seu`,
          `\`${P}game mercado comprar <#>\` — fecha a oferta de alguém`,
          `\`${P}game mercado cancelar <#>\` — tira a sua do ar e recebe de volta`,
          "",
          "**Primos do mercado**",
          `\`${P}game cambio\` — câmbio de moedas _(veja \`${P}help game cambio\`)_`,
          `\`${P}game trocar [@pessoa] <seu item> por <item dela>\` — escambo item por item`,
          `\`${P}game trocar aceitar <#>\` — fecha um escambo proposto a você`,
          "",
          "_Toda venda paga uma taxa ao mercado; ela cresce com o valor da oferta._",
          `_Loja do sistema (preço fixo, sem outro jogador): \`${P}game comprar\` e \`${P}game vender\`._`,
        ].join("\n"),
      },
      magia: {
        titulo: "game magias",
        texto: [
          "Magia é o que dá uso ao atributo **Mana**. Antes ela só vinha de",
          "companheiro; agora dá para comprar a sua e carregar no grimório.",
          "",
          `\`${P}game magias\` — o catálogo e o que você já sabe`,
          `\`${P}game magia <nome>\` — a ficha: custo, poder, preço em cada moeda`,
          `\`${P}game aprender <nome> [com <moeda>]\` — compra a magia`,
          "",
          "**Mana é o limite, não a coleção**",
          "As magias entram da **mais forte para a mais fraca**, enquanto a Mana",
          "durar. Aprender dez não ajuda se você só tem Mana para duas — as",
          "outras ficam dormentes (💤 na lista) até você subir Mana.",
          "",
          "**Duas escolas**",
          "🔥 **Ataque** — sobe a chance de cumprir a missão",
          "✨ **Suporte** — sobe a chance de voltar vivo",
          "",
          "**Divide a mana com os followers**",
          "As magias de companheiro entram na mesma disputa. Uma party de magos",
          "com Mana baixa desperdiça poder — vale equilibrar.",
          "",
          `_Nível trava as mais fortes (🔒 na lista). O Carisma desconta o preço,_`,
          "_igual ao contratar mercenário._",
        ].join("\n"),
      },
      cambio: {
        titulo: "game cambio",
        texto: [
          "Duas formas de trocar moeda, e elas servem a coisas diferentes.",
          "",
          "**Quanto vale em cada moeda**",
          `\`${P}game cambio <qtd> <moeda>\` — o valor em TODAS as outras`,
          `   ex.: \`${P}game cambio 1 bitcoin\``,
          `\`${P}game cambio taxas\` — a tabela completa, de cada uma para cada uma`,
          "",
          "**Com o banco — na hora, sem depender de ninguém**",
          `\`${P}game cambio <qtd> <moeda> para <moeda>\``,
          `   ex.: \`${P}game cambio 1000 real para dolar\``,
          "",
          "**Com outro jogador — você define a taxa**",
          `\`${P}game cambio <qtd> <moeda> por <qtd> <moeda>\``,
          `   ex.: \`${P}game cambio 100 real por 5 dolar\``,
          "O valor sai da sua carteira e fica em custódia até alguém aceitar",
          `ou você cancelar em \`${P}game mercado cancelar <#>\`.`,
          "",
          "**De onde vem a taxa do banco**",
          "Duas coisas: a **dificuldade** da moeda (o quanto ela é rara de ganhar —",
          "é o lastro) e o **P** dela (quanto está parado nas carteiras — é a",
          "inflação). Por isso a taxa muda sozinha conforme o servidor joga.",
          "",
          "**Fração é dinheiro**",
          "Moeda cara se compra em pedaço: 112 Reais viram 1,24 Monero, não 1.",
          "O que sobra continua seu. Dá para digitar fração também:",
          `\`${P}game cambio 0,5 xau para brl\` (ponto ou vírgula, tanto faz).`,
          "",
          "**Por que o A→B→A não enriquece**",
          "Cada troca cobra um spread. Ida e volta custam mais do que a oscilação",
          "devolve, então ficar girando moeda só queima saldo.",
          "",
          "_Moeda finita tem estoque: se o banco não tiver o bastante, ele diz —",
          "e o balcão entre jogadores continua aberto._",
        ].join("\n"),
      },
      missao: {
        titulo: "game missao",
        texto: [
          `\`${P}game missao\` — lista as missões com a chance de cada uma`,
          `\`${P}game missao <nome>\` — parte para a missão`,
          "",
          "**Os tipos**",
          "🏪 **Mercado** — sem risco, paga pouco, sem cooldown longo",
          "🟢 **Fácil** · 🟡 **Média** · 🔴 **Difícil** — risco e prêmio sobem juntos",
          "",
          "**A chance que importa**",
          "O 🏆 mostrado é `êxito × sobrevivência` — a chance de cumprir **e** voltar.",
          "Uma missão de 53% de êxito com 75% de sobrevivência cumpre só 40% das vezes.",
          "",
          "**O que muda o resultado**",
          "• seus atributos e o equipamento",
          `• os companheiros na party (\`${P}game follower levar <nome>\`)`,
          "• Sorte melhora o loot; Inteligência e Sorte aumentam o XP",
          "",
          "**As duas esperas**",
          "Cada missão tem um cooldown próprio: 10 min no mercado, 20 na fácil,",
          "45 na média, 90 na difícil. Se você caiu, some a isso ~30 min de",
          "recuperação — as duas correm **juntas**, então o que vale é a maior.",
          `A lista (\`${P}game missao\`) marca com ⏳ quanto falta em cada uma:`,
          "depois de cair numa difícil, as leves liberam bem antes.",
          "",
          "**Se você cair**",
          "Perde parte da moeda que carrega (vai para o pote da dungeon), fica ~30 min",
          "se recuperando, e em missões médias/difíceis os companheiros podem ser",
          `capturados — resgate com \`${P}game dungeon\`.`,
        ].join("\n"),
      },
      follower: {
        titulo: "game follower",
        texto: [
          "Companheiros lutam com você e mudam bastante a chance das missões.",
          "",
          `\`${P}game followers\` — os seus, e quem está na party`,
          `\`${P}game follower ficha <nome>\` — atributos, magia, energia e mochila`,
          `\`${P}game follower levar <nome>\` — coloca na party (máximo **2**)`,
          `\`${P}game follower tirar <nome>\` — devolve para a reserva`,
          `\`${P}game follower dispensar <nome>\` — libera de vez`,
          `\`${P}game follower fotos <nome>\` — o álbum dele`,
          "",
          "**A mochila dele**",
          `\`${P}game follower dar <nome> <item>\` — entrega um item para carregar`,
          `\`${P}game follower pegar <nome> <item>\` — traz o item de volta`,
          "",
          "_Os dois nomes podem ter espaço_ — `dar Curandeira Errante Espada",
          "Temperada` funciona: eu testo todas as quebras até os dois lados",
          "baterem com algo real. Se ficar ambíguo, separe com `|`:",
          `\`${P}game follower dar Curandeira Errante | Espada Temperada\``,
          "Cada companheiro carrega até **2** itens, e o bônus deles soma nos",
          "atributos DELE — é o destino natural do equipamento que você já superou,",
          "em vez de revender tudo. A ficha mostra a base e, entre parênteses, o",
          "que a mochila acrescenta.",
          "",
          "**Energia** ⚡",
          "Cada missão de dungeon gasta 1. Volta sozinha (1 por hora) ou de uma vez",
          `com \`${P}game descansar confirmar\`, pagando.`,
          "",
          "**De onde vêm**",
          `\`${P}game recrutas\` — todos que existem no jogo`,
          `\`${P}game contratar <nome>\` — compra um (seu Carisma dá desconto)`,
          "Loot de dungeon — alguns só aparecem assim 🗝️",
        ].join("\n"),
      },
      dungeon: {
        titulo: "game dungeon",
        texto: [
          "Quando você cai numa missão, dois destinos: a moeda perdida vira o **pote**,",
          "e os companheiros podem ficar **capturados** lá.",
          "",
          `\`${P}game dungeon\` — quem está preso agora`,
          "",
          "**O resgate é automático**",
          "Não há comando de resgate: toda missão de que você **volta** é uma",
          "tentativa. Cumprir a missão dá a chance cheia; voltar sem cumprir dá",
          "metade; cair não dá nenhuma — você não estava em condição de tirar",
          "ninguém de lá.",
          "",
          "**As regras**",
          "• O dono original tem chance bem maior.",
          "• Nas primeiras horas, **só** o dono resgata (janela de prioridade).",
          "• Passada a janela, a missão de qualquer um pode soltá-lo — e quem",
          "  soltar fica com ele.",
          "• Uma tentativa por missão, e os seus vêm primeiro.",
          "",
          "_O pote em moeda é o prêmio de quem vencer a dungeon; veja em_ "
            + `\`${P}game carteira\`.`,
        ].join("\n"),
      },
      itens: {
        titulo: "game itens",
        texto: [
          `\`${P}game itens\` — sua mochila, agrupada por raridade`,
          `\`${P}game equipar <item>\` — veste (✅ marca o que está em uso)`,
          `\`${P}game equipar <item> acessorio2\` — escolhe o slot do acessório`,
          `\`${P}game desequipar <slot ou item>\` — tira e devolve à mochila`,
          `\`${P}game catalogo\` — resumo de tudo que existe no jogo`,
          `\`${P}game catalogo raro\` — a lista completa daquela raridade`,
          `\`${P}game catalogo arma\` — filtra por slot`,
          `\`${P}game item <nome>\` — a ficha de UM item: preço, estoque, bônus`,
          "",
          "**Os 6 slots**",
          "arma · capacete · armadura · acessorio1 · acessorio2 · acessorio3",
          `A ficha (\`${P}game\`) lista os seis, inclusive os **vazios** — é o jeito`,
          "rápido de ver onde ainda dá para melhorar.",
          "",
          "**Preço em cada moeda**",
          `\`${P}game item <nome>\` mostra quanto custa em TODAS as moedas do`,
          "servidor, com ✅ nas que você consegue pagar. Comprar com uma",
          `específica: \`${P}game comprar <item> com <moeda>\`.`,
          "",
          "_O bônus do equipamento aparece na ficha ao lado do valor base, assim: `12 (+3)`._",
          `_Vender: \`${P}game vender <item>\` (o Carisma melhora o que te pagam)._`,
        ].join("\n"),
      },
      pontos: {
        titulo: "game pontos",
        texto: [
          `\`${P}game pontos <atributo> [quantos]\` — distribui os pontos livres`,
          "",
          "**Atributos** _(aceito abreviação: for, des, res, agi, int, sor, car…)_",
          "⚔️ **Força** — dano e êxito no combate direto",
          "🏃 **Destreza** · 🌀 **Agilidade** — esquiva e sobrevivência",
          "🛡 **Resistência** — aguentar a missão sem cair",
          "🧠 **Inteligência** — mais XP e mais pontos por nível",
          "🍀 **Sorte** — loot melhor, mais XP, mais pontos",
          "✨ **Carisma** — preço melhor ao vender e desconto ao contratar",
          "",
          "**Como se ganha ponto**",
          "Subindo de nível. Quanto você ganha por nível depende de Inteligência e",
          "Sorte — com retorno decrescente, então investir nelas nunca deixa de valer.",
          "",
          "_Cada nível também dá um ganho automático em **todos** os atributos._",
        ].join("\n"),
      },
    },

    // ── &xp ──────────────────────────────────────────────
    xp: {
      setup: {
        titulo: "xp setup",
        texto: [
          "Assistente de configuração do sistema de níveis. **Exige ManagePermissions.**",
          "",
          `\`${P}xp setup\` — mostra a configuração atual`,
          `\`${P}xp setup multiplicador <1–5>\` — dificuldade da curva (ex.: 1.5)`,
          `\`${P}xp setup nivelmaximo <5–1000>\` — o teto`,
          `\`${P}xp setup intervalo <5|10>\` — de quantos em quantos níveis vem cargo`,
          `\`${P}xp setup xp <min> <max>\` — quanto cada mensagem paga`,
          `\`${P}xp setup cooldown <segundos>\` — intervalo mínimo entre ganhos`,
          `\`${P}xp setup canal <aqui|off>\` — onde anunciar o level up`,
          `\`${P}xp setup anuncio <on|off>\` — anunciar ou não`,
          "",
          "**Ordem que funciona**",
          `1. \`${P}xp setup\` e ajuste o que quiser`,
          `2. \`${P}xp criarcargos\` — cria os cargos de nível`,
          `3. \`${P}xp on\` — liga o sistema`,
          "",
          "_XP vem só de mensagens: o Stoat não emite eventos de voz, então não há_",
          "_como cronometrar call de forma confiável._",
        ].join("\n"),
      },
      cargos: {
        titulo: "xp cargos",
        texto: [
          `\`${P}xp cargos\` — lista os cargos de nível já configurados`,
          `\`${P}xp criarcargos\` — cria automaticamente, um a cada N níveis`,
          "",
          "**Segurança de hierarquia**",
          "Todo cargo criado aqui é posicionado **abaixo** do cargo de silêncio, para",
          "ninguém usar um cargo de nível para escapar do mute. Se você ainda não tem",
          `um cargo de silêncio, crie com \`${P}cargomudo\` e rode \`${P}xp criarcargos\``,
          "de novo para reordenar.",
          "",
          "_O bot precisa de **ManageRole**, e o cargo dele precisa estar acima dos que cria._",
        ].join("\n"),
      },
    },

    // ── &acesso ──────────────────────────────────────────
    acesso: {
      cargo: {
        titulo: "acesso cargo",
        texto: [
          "Cargos que valem como **staff** — usam os comandos de moderação mesmo sem",
          "a permissão nativa do Stoat. Útil para dar poder de moderar sem entregar",
          "permissões reais do servidor.",
          "",
          `\`${P}acesso cargo add <@cargo|id>\``,
          `\`${P}acesso cargo remove <@cargo|id>\``,
          `\`${P}acesso cargo limpar\` — volta a valer só a permissão nativa`,
          "",
          "_Não cobre **ManageServer**: administração de verdade continua exigindo a_",
          "_permissão real. Exige ManagePermissions para configurar._",
        ].join("\n"),
      },
      canal: {
        titulo: "acesso canal",
        texto: [
          "Onde os comandos funcionam — para não poluir os canais de conversa.",
          "",
          "**Modos**",
          `\`${P}acesso canal todos\` — em qualquer canal (padrão)`,
          `\`${P}acesso canal somente\` — só nos canais da lista`,
          `\`${P}acesso canal exceto\` — em todos, menos os da lista`,
          "",
          "**A lista** _(sem #canal, usa o canal onde você digitou)_",
          `\`${P}acesso canal add [#canal]\``,
          `\`${P}acesso canal remove [#canal]\``,
          `\`${P}acesso canal limpar\``,
          "",
          "**Staff**",
          `\`${P}acesso staffignora on|off\` — se o staff escapa da restrição`,
          "",
          "_No modo `todos` a lista existe, mas não tem efeito._",
        ].join("\n"),
      },
    },

    // ── &banglobal ───────────────────────────────────────
    banglobal: {
      varrer: {
        titulo: "banglobal varrer",
        texto: [
          "O ban global age quando alguém **entra**. Quem já estava aqui quando foi",
          "banido em outro servidor passava despercebido — a varredura fecha esse ponto cego.",
          "",
          `\`${P}banglobal varrer ver\` — só mostra quem apareceria, não bane ninguém`,
          `\`${P}banglobal varrer\` — confere e **age** conforme o modo atual`,
          "",
          "**O que ela faz depende do modo**",
          "`off` — a varredura só funciona em modo `ver`",
          "`avisar` — lista quem consta, sem agir",
          "`banir` — bane quem consta na lista",
          "",
          "_O bot precisa enxergar os membros e ter **BanMembers**, com o cargo dele_",
          "_acima do cargo da pessoa. Falhas aparecem no fim do relatório._",
        ].join("\n"),
      },
      contribuicao: {
        titulo: "banglobal contribuição",
        texto: [
          "**Todo servidor onde o bot está alimenta a lista. Sempre.**",
          "Não há comando para ligar, desligar ou importar à mão.",
          "",
          "**O que entra sozinho**",
          "• Bans **novos** — no instante em que acontecem (automod ou `&ban`).",
          "• Bans **antigos** — sincronizados ~1 min após o bot subir e a cada 6h.",
          "• Servidor **novo** — o histórico entra assim que o bot é adicionado.",
          "",
          "**O que ainda é escolha sua**",
          `\`${P}banglobal <off|avisar|banir>\` — se ESTE servidor se aproveita da lista.`,
          "Dá para não usar a lista; não dá para usá-la sem alimentá-la.",
          "",
          "**Se um registro não se sustentar**",
          `\`${P}banglobal esquecer <@usuário|id>\` — tira aquele registro da lista`,
          `\`${P}banglobal historico <@usuário|id>\` — onde e por que foi banido`,
          "",
          "_Registros já existentes não são duplicados._",
          "_Vale pensar antes de adicionar o bot a um servidor de terceiros: o critério de moderação de lá passa a valer para os seus._",
        ].join("\n"),
      },
    },

    // ── &punicao ─────────────────────────────────────────
    punicao: {
      escada: {
        titulo: "punicao escada",
        texto: [
          "No modo `acumular`, cada reincidência sobe um degrau. O padrão:",
          "",
          "**1.** aviso",
          "**2.** silêncio de 5 min",
          "**3.** silêncio de 1 h",
          "**4.** ban",
          "",
          "**Por que uma escada e não um contador**",
          "Antes eram N avisos e, no limite, ban — sem nada no meio. Isso punia",
          "igual quem escorregou uma vez e quem está atacando o servidor, e dava",
          "ao membro comum um susto desproporcional na única punição que ele via.",
          "A escada dá peso crescente e, principalmente, dá **chance**: quem para",
          "no primeiro degrau nunca chega ao último.",
          "",
          "**Mudar**",
          `\`${P}punicao escada\` — mostra a escada atual`,
          `\`${P}punicao escada aviso,10m,2h,ban\` — mais tempo em cada degrau`,
          `\`${P}punicao escada aviso,ban\` — só um aviso antes do ban`,
          "",
          "Aceita `aviso`, `ban` e prazos como `30s`, `10m`, `2h`, `1d`.",
          "O ban é sempre o último degrau, mesmo que você não escreva.",
          "",
          `_Os degraus de silêncio precisam de um cargo de silêncio: \`${P}cargomudo\` cria um._`,
          "_O prazo fica no banco, então um mute de 1 h sobrevive a reinício do bot._",
        ].join("\n"),
      },
    },

    // ── &sentinela ───────────────────────────────────────
    sentinela: {
      antiguidade: {
        titulo: "sentinela antiguidade",
        texto: [
          "O sentinela é o único módulo que **julga** em vez de medir — e por isso",
          "é o único que muda de rigor conforme quem escreve.",
          "",
          "**A ideia**",
          "Conta criada agora, que chega mandando link e falando de venda, é o",
          "padrão clássico de golpe. A mesma frase vinda de quem está no servidor",
          "há semanas quase sempre é brincadeira que o detector não entende.",
          "",
          "**A medida de convívio é o nível de XP**",
          "O Stoat não expõe a data de entrada de forma confiável. O nível serve",
          "melhor: ele só sobe conversando, ao longo do tempo — que é exatamente",
          "o que se quer medir. Sem XP ligado, todo mundo é tratado como novato,",
          "que é o lado seguro de errar.",
          "",
          "| nível | faixa | limiar (base 6) |",
          "|---|---|---|",
          "| 0 | recém-chegado | 4,5 |",
          "| 1–2 | conhecido | 5,0 |",
          "| 3–5 | frequente | 5,5 |",
          "| 6–10 | estabelecido | 6,0 |",
          "| 11+ | veterano | 6,5 |",
          "",
          "Há piso e teto: nem o veterano fica imune, nem o novato é punido por",
          "qualquer bobagem.",
          "",
          `\`${P}sentinela antiguidade on|off\``,
          "",
          "_Vale SÓ para o sentinela. Spam, caps, links, menções, repetição e_",
          "_caracteres medem coisas exatas — lá o limite é igual para todo mundo._",
        ].join("\n"),
      },
      alerta: {
        titulo: "sentinela alerta",
        texto: [
          "Marca a staff quando alguém levanta suspeita **repetidas vezes** em",
          "pouco tempo — mesmo sem chegar ao limiar de punição.",
          "",
          "**Por que separado da punição**",
          "Nem todo padrão suspeito merece punir, mas todo padrão suspeito merece",
          "um par de olhos humanos **enquanto está acontecendo**. É justamente o",
          "caso duvidoso — nota alta mas não alta o bastante — que a moderação",
          "precisa ver antes de o bot decidir sozinho.",
          "",
          "**Como dispara**",
          "3 sinais em 10 minutos da mesma pessoa. Um sinal isolado é ruído.",
          "Depois de avisar, fica 30 min em silêncio sobre aquela pessoa: alerta",
          "que se repete vira ruído e a staff para de ler.",
          "",
          "**O que o aviso traz**",
          "Quem é, quantas vezes, o perfil (recém-chegado/veterano e o nível), a",
          "maior nota, os sinais que apareceram e os comandos de ação.",
          "",
          `\`${P}sentinela alerta on|off\``,
          `\`${P}sentinela channel <id|aqui>\` — onde avisar (senão usa o canal de logs)`,
          `_Marca os cargos de \`${P}acesso cargo\`._`,
        ].join("\n"),
      },
    },

    // ── &cor ─────────────────────────────────────────────
    cor: {
      painel: {
        titulo: "cor painel",
        texto: [
          "Faz tudo sozinho: cria os cargos coloridos, publica a mensagem de escolha,",
          "reage com um emoji por cor e liga os cargos por reação em modo exclusivo.",
          "",
          `\`${P}cor painel aqui\` — painel neste canal, com todas as cores`,
          `\`${P}cor painel <id-do-canal>\` — publica em outro canal`,
          `\`${P}cor painel aqui fogo gelo neon\` — só as cores que você listar`,
          `\`${P}cor criar\` — só cria e pinta os cargos, sem publicar nada`,
          "",
          "**Exclusivo por padrão:** escolher uma cor tira a anterior. É o que faz",
          "sentido para cor — ninguém quer duas ao mesmo tempo.",
          "",
          "_O bot precisa de **ManageRole**, **React** no canal, e o cargo dele precisa_",
          "_estar acima dos cargos de cor._",
        ].join("\n"),
      },
      gradiente: {
        titulo: "cor gradiente",
        texto: [
          "O campo de cor do cargo no Stoat aceita **qualquer cor CSS** — por isso dá",
          "para usar gradiente, e não só hex.",
          "",
          `\`${P}cor <cargo> gradiente #FF0000 #0000FF\` — de uma cor à outra`,
          `\`${P}cor <cargo> gradiente 45 vermelho azul\` — o número inicial é o ângulo`,
          `\`${P}cor <cargo> preset fogo\` — um dos prontos (\`${P}cor presets\`)`,
          `\`${P}cor <cargo> linear-gradient(90deg, #f00 0%, #00f 100%)\` — CSS na mão`,
          "",
          "**A pegadinha clássica**",
          "Escrever `gradient(...)` sem o `linear-` devolve erro 400. É o motivo",
          "número um de falha aqui — a validação avisa antes de tentar.",
          "",
          `_Cor sólida: \`${P}cor <cargo> #FF00AA\` ou um nome (\`roxo\`)._`,
          `_Voltar ao padrão: \`${P}cor <cargo> remover\`._`,
        ].join("\n"),
      },
    },

    // ── &reactionrole ────────────────────────────────────
    reactionrole: {
      exclusivo: {
        titulo: "reactionrole exclusivo",
        texto: [
          "Define se a pessoa pode acumular os cargos daquela mensagem ou se escolher",
          "um **troca** o anterior.",
          "",
          `\`${P}reactionrole exclusivo <mensagem> on\` — troca (cor, idade, time)`,
          `\`${P}reactionrole exclusivo <mensagem> off\` — acumula (interesses, jogos)`,
          "",
          "No modo exclusivo o bot também **tira a reação antiga** da pessoa, para o",
          "painel refletir a escolha atual.",
          "",
          "_A mensagem pode ser o ID ou o link. Ela precisa já ter regras registradas._",
        ].join("\n"),
      },
      recarregar: {
        titulo: "reactionrole recarregar",
        texto: [
          "**O sintoma:** funcionava, o bot reiniciou, parou de entregar cargos — mas",
          "os emojis continuam lá.",
          "",
          "**A causa:** a lib só emite evento de reação para mensagens que ela conhece.",
          "Depois de um restart, as mensagens antigas não estão em cache.",
          "",
          `\`${P}reactionrole recarregar\` — busca as mensagens e devolve ao cache`,
          "",
          "Isso já roda **sozinho a cada reinício**; o comando existe para quando você",
          "quiser forçar, ou diagnosticar o que não foi encontrado.",
          "",
          "_Mensagem não encontrada = canal apagado, ou falta \\`ViewChannel\\`/_",
          "_\\`ReadMessageHistory\\` para o bot._",
        ].join("\n"),
      },
    },

    // ── &log ─────────────────────────────────────────────
    log: {
      eventos: {
        titulo: "log <evento>",
        texto: [
          "Cada categoria liga e desliga sozinha: `&log <evento> <on|off>`.",
          "",
          "`punicoes` — avisos, silêncios e bans (automod e manuais)",
          "`membros` — entradas e saídas do servidor",
          "`mensagens` — mensagens apagadas e editadas",
          "`cargos` — cargos criados e cargos dados a alguém",
          "`comandos` — tentativas de uso de comandos do bot",
          "",
          "**Exemplo**",
          `\`${P}log mensagens off\` — para de registrar edição/exclusão`,
          "",
          `_Todas começam ligadas. O canal se define com \`${P}log canal aqui\` (ou menção, link, ID, nome)._`,
          "_Os registros no canal de log saem sempre em português._",
        ].join("\n"),
      },
    },

    // ── &chat (IA) ───────────────────────────────────────
    chat: {
      livre: {
        titulo: "chat livre",
        texto: [
          "Faz a Judy participar do canal **sem precisar de menção**.",
          "",
          `\`${P}chat livre on\` — liga neste canal`,
          `\`${P}chat livre off\` — desliga`,
          `\`${P}chat livre modo relevante\` — ela responde só o que julgar importante`,
          `\`${P}chat livre modo todas\` — ela responde toda mensagem`,
          "",
          "_Uma conversa por vez: enquanto ela responde alguém, as outras esperam._",
          "_Exige ManagePermissions._",
        ].join("\n"),
      },
      memoria: {
        titulo: "chat esquecer / perfil",
        texto: [
          "A Judy guarda fatos sobre quem conversa com ela, e um perfil por pessoa.",
          "",
          `\`${P}chat perfil [@pessoa]\` — o que ela sabe`,
          `\`${P}chat mapear [@pessoa]\` — captura bio/status do cartão de perfil`,
          `\`${P}chat esquecer\` — apaga tudo sobre **você**`,
          `\`${P}chat esquecer tudo\` — apaga a memória do servidor inteiro _(ManageServer)_`,
          `\`${P}chat cuidado [@pessoa] on|off\` — tratamento gentil, sem ironia ácida`,
          "",
          "_Qualquer um liga o `cuidado` para si; para outra pessoa exige ManagePermissions._",
        ].join("\n"),
      },
      comentar: {
        titulo: "chat comentar",
        texto: [
          "A Judy solta comentários **por iniciativa própria** sobre a conversa em",
          "andamento — só no canal escolhido, e com freios para não virar spam.",
          "",
          `\`${P}chat comentar aqui\` — liga neste canal`,
          `\`${P}chat comentar off\` — desliga`,
          `\`${P}chat comentar pordia <1–20>\` — teto diário (padrão 4)`,
          `\`${P}chat comentar status\` — como está agora`,
          "",
          "_Ela não puxa assunto do nada: só comenta o que já está rolando._",
        ].join("\n"),
      },
    },

    // ── &modia (IA) ──────────────────────────────────────
    modia: {
      criterios: {
        titulo: "modia criterios",
        texto: [
          "Você escreve **em linguagem natural** o que deve ser moderado. Não há lista",
          "de palavras: a Judy lê a mensagem e julga pelo que você descreveu.",
          "",
          `\`${P}modia criterios <texto>\``,
          "",
          "**Exemplo bom** _(específico, diz o que NÃO moderar também)_",
          "```",
          `${P}modia criterios Apague divulgação de outros servidores, venda de contas`,
          "e ataques pessoais diretos. Não modere palavrão leve nem discussão acalorada.",
          "```",
          "",
          "**O que ela faz ao encontrar:** apaga a mensagem e marca o dono no canal de",
          "log com as opções. **Ela nunca bane sozinha.**",
          "",
          `_Ligar depois de definir: \`${P}modia on\`. Exige ManageServer._`,
        ].join("\n"),
      },
    },

    // ── &debug ───────────────────────────────────────────
    debug: {
      canais: {
        titulo: "debug canais",
        texto: [
          "No Stoat a permissão do **canal** vence a do cargo: dá para o bot ter",
          "SendMessage no servidor e mesmo assim estar mudo num canal. Este relatório",
          "expõe exatamente isso.",
          "",
          `\`${P}debug canais\` — o que eu enxergo e posso fazer em cada canal`,
          `\`${P}debug canais cru\` — o que a API me devolve (para diagnóstico)`,
          "",
          "**Como ler**",
          "⚠️ **Falta o essencial** — ali eu não consigo responder",
          "🚫 **Não enxergo** — sem ViewChannel",
          "🟡 **Ok, mas incompleto** — falta React ou ManageMessages",
          "✅ **Tudo certo**",
          "❔ **Não consegui avaliar** — rode a versão `cru`",
        ].join("\n"),
      },
      silence: {
        titulo: "debug silence",
        texto: [
          "Responde a pergunta que importa: **o silêncio vai calar essa pessoa mesmo?**",
          "",
          `\`${P}debug silence\` — checa a cobertura do cargo de silêncio nos canais`,
          `\`${P}debug silence @pessoa\` — checa se os cargos dela anulam o silêncio`,
          "",
          "**Os dois jeitos de o mute falhar**",
          "1. O cargo não está negado em algum canal com permissão própria —",
          `   conserta com \`${P}cargomudo canais\`.`,
          "2. A pessoa tem um cargo **acima** do silêncio que libera falar —",
          "   suba o cargo de silêncio, ou tire o SendMessage do outro.",
          "",
          "_O dono do servidor nunca é silenciado: nenhuma permissão o alcança._",
        ].join("\n"),
      },
    },

    // ── &blocklist ───────────────────────────────────────
    blocklist: {
      dominios: {
        titulo: "blocklist adddomain",
        texto: [
          "Duas coisas diferentes convivem aqui: **fontes** (listas Pi-hole inteiras,",
          "com milhões de domínios) e **domínios manuais** (um a um, seus).",
          "",
          "**Fontes**",
          `\`${P}blocklist add <url>\` — baixa e incorpora uma lista`,
          `\`${P}blocklist remove <url>\` — remove a fonte`,
          "",
          "**Manuais**",
          `\`${P}blocklist adddomain 02giga.link\``,
          `\`${P}blocklist removedomain 02giga.link\``,
          "",
          "**Manutenção**",
          `\`${P}blocklist list\` — fontes, manuais e o total carregado`,
          `\`${P}blocklist reload\` — rebaixa tudo`,
          `\`${P}blocklist clear\` — zera fontes e manuais`,
          "",
          "_A lista é **global** ao bot, não por servidor: uma vez baixada, vale para todos._",
          "_O índice pronto fica cacheado em disco: após reiniciar, o anti-link já nasce armado._",
          "_Se uma fonte falhar no `reload`, a lista atual é mantida — ela nunca encolhe por queda de rede._",
        ].join("\n"),
      },
    },

    // ── &embed ───────────────────────────────────────────
    // ── &staff / &boasvindas / &adeus ────────────────────
    fuso: {
      cidades: {
        titulo: "fuso",
        texto: [
          "Relógio do servidor mostrando **várias cidades ao mesmo tempo** — para",
          "quando a galera está espalhada e todo combinado vira conta de cabeça.",
          "",
          "**Consultar** _(qualquer pessoa)_",
          `\`${P}fuso\` — a hora agora em cada cidade da lista`,
          `\`${P}fuso ver <cidade>\` — hora de qualquer cidade, sem configurar`,
          `\`${P}fuso buscar <termo>\` — procura cidades disponíveis`,
          `\`${P}fuso <cidade>\` — atalho para \`ver\``,
          "",
          "**Configurar** _(ManageMessages)_",
          `\`${P}fuso add <cidade>\` · \`${P}fuso remove <cidade>\``,
          `\`${P}fuso apelido <cidade> <texto>\` — ex.: Madrid aparecendo como \"Europa\"`,
          `\`${P}fuso principal <cidade>\` — de quem as diferenças são contadas`,
          `\`${P}fuso formato <12|24>\` · \`${P}fuso limpar\``,
          "",
          "**Como escrever a cidade**",
          "Acentos funcionam (`São Paulo`), o formato `Cidade/País` também",
          "(`Madrid/Europa`), e há apelidos prontos: `sp`, `nova york`, `toquio`,",
          "`londres`, `lisboa`, `utc`. Se houver empate, o bot mostra as opções.",
          "",
          "_A lista sai ordenada do fuso mais atrasado ao mais adiantado — é como o_",
          "_olho espera ler um relógio mundial. O limite é de 12 cidades._",
        ].join("\n"),
      },
    },

    staff: {
      equipe: {
        titulo: "staff",
        texto: [
          "A **equipe do servidor**, agrupada por cargo, com quem tem cada um.",
          "",
          "**A lista não é um cadastro à parte.** Ela lê os mesmos cargos que o",
          `\`${P}acesso cargo\` usa para decidir quem pode moderar. Promover no`,
          `\`${P}staff add\` é promover de verdade; tirar daqui tira o acesso também.`,
          "Assim o quadro de avisos nunca discorda da permissão real.",
          "",
          "**Comandos** _(mexer exige ManagePermissions; consultar é público)_",
          `\`${P}staff\` — mostra a equipe`,
          `\`${P}staff add <@cargo>\` — marca o cargo como staff`,
          `\`${P}staff remove <@cargo>\` — desmarca`,
          `\`${P}staff titulo <@cargo> <texto>\` — rótulo no lugar do nome do cargo`,
          `\`${P}staff limpar\` — esvazia a lista`,
          "",
          "_A ordem é a de adição: o primeiro cargo adicionado aparece no topo._",
        ].join("\n"),
      },
    },
    boasvindas: {
      mensagens: {
        titulo: "boasvindas / adeus",
        texto: [
          `Embeds publicados quando alguém **entra** (\`${P}boasvindas\`) ou **sai**`,
          `(\`${P}adeus\`) do servidor. Os dois têm exatamente as mesmas opções.`,
          "",
          "**Configurar**",
          `\`${P}boasvindas canal aqui\` — onde publicar _(já liga)_`,
          `\`${P}boasvindas titulo <texto>\` · \`${P}boasvindas texto <descrição>\``,
          `\`${P}boasvindas cor <cor>\` · \`${P}boasvindas imagem <url|limpar>\``,
          `\`${P}boasvindas testar\` — publica usando você de exemplo`,
          `\`${P}boasvindas padrao\` — volta ao texto de fábrica`,
          `\`${P}boasvindas on|off\` — liga/desliga sem perder o que você escreveu`,
          "",
          "**Marcadores**",
          "`{usuario}` — menção clicável · `{nome}` — só o nome",
          "`{servidor}` — nome do servidor · `{membros}` — total de membros",
          "",
          "_Na despedida o `{usuario}` vira o **nome**, não menção: quem saiu não está_",
          "_mais no servidor e a menção apareceria como um ID cru na tela._",
          "",
          "_O texto aceita várias linhas; `\\n` também vira quebra de linha._",
          "",
          "**Sobre a imagem**",
          "Há **dois resultados diferentes**, conforme a origem do link:",
          "• **Anexo do Stoat** → a imagem vira a **capa do embed**. É o melhor.",
          "• **Link de fora** → aparece como **pré-visualização abaixo** do embed.",
          "  _(O campo de capa do Stoat só aceita anexo dele mesmo, não URL externa.)_",
          "  A URL vai mascarada, então **não fica aquele link enorme na tela**.",
          `  Se a imagem não aparecer: \`${P}boasvindas imagem visivel\` devolve a URL crua.`,
          "",
          "O jeito recomendado é **enviar o arquivo aqui no Stoat e usar o link do anexo**:",
          "aí a imagem fica na infraestrutura do Stoat, não some, e ninguém de fora",
          "fica sabendo quem viu a mensagem.",
          "",
          "Link de site de terceiros funciona, mas o dono daquele site **vê o IP de cada",
          "pessoa que carregar a mensagem** — numa boas-vindas, o de todo mundo que entra.",
          "Precisa ser o link do **arquivo** (`.png`, `.jpg`, `.gif`, `.webp`); link de",
          "resultado de busca (Brave, Google, Bing) é miniatura temporária e costuma falhar.",
          "",
          "_Endereços de rede interna (`localhost`, `192.168.x`, `100.x` da Tailscale,",
          "portas fora de 80/443) são **recusados**: guardá-los viraria um atalho para a",
          "rede da máquina do bot. O bot nunca baixa a imagem — só repassa o link._",
          "Se a imagem falhar no envio, a mensagem vai assim mesmo — só sem capa.",
        ].join("\n"),
      },
    },

    embed: {
      campos: {
        titulo: "embed (campos)",
        texto: [
          "Um campo por linha, no formato `campo: valor`. Sem parênteses em volta e",
          "sem vírgula no fim — os dois erros mais comuns (e eu tolero os dois).",
          "",
          "**Campos**",
          "`titulo:` — o título",
          "`descricao:` — o corpo; pode ocupar várias linhas",
          "`cor:` — hex `#RRGGBB` ou nome (`roxo`, `verde`…)",
          "`rodape:` — uma linha em itálico no fim",
          "`imagem:` — URL da imagem de capa",
          "`canal:` — ID, para publicar em **outro** canal",
          "",
          "**Aceito também**",
          "• chaves em inglês (`title`, `description`, `color`…)",
          "• tudo numa linha só, separando com `|`",
          "• `\\n` no meio de um valor, para quebrar linha",
          "",
          "_Se algo for ignorado, eu envio e aviso o que não entendi — em vez de falhar calado._",
        ].join("\n"),
      },
    },

    // ── &comando ─────────────────────────────────────────
    comando: {
      gerenciar: {
        titulo: "comando disable/enable",
        texto: [
          `\`${P}comando\` — lista os comandos e o estado de cada um`,
          `\`${P}comando disable <nome>\` — desliga neste servidor`,
          `\`${P}comando enable <nome>\` — religa`,
          "",
          "**A trava de segurança**",
          "`help` e `comando` **não podem** ser desativados — senão você se trancaria",
          "para fora, sem como reverter.",
          "",
          "_Vale por servidor: desativar aqui não afeta os outros._",
          "_Use o nome canônico (o que aparece na lista), não um apelido._",
        ].join("\n"),
      },
    },

    // ── &cargomudo ───────────────────────────────────────
    cargomudo: {
      canais: {
        titulo: "cargomudo canais",
        texto: [
          "Criar o cargo com tudo negado **no servidor** não basta: um canal com",
          "permissão própria ignora isso. Por isso a negação é aplicada canal a canal.",
          "",
          `\`${P}cargomudo [nome]\` — cria o cargo, nega em tudo e já o define como`,
          "   cargo de silêncio da política de punição",
          `\`${P}cargomudo canais\` — **reaplica** a negação nos canais, usando o cargo`,
          "   de silêncio que já está definido",
          "",
          "**Quando rodar de novo**",
          "Sempre que criar canais novos — eles nascem sem a negação.",
          "",
          `_Para conferir se o silêncio realmente cala alguém: \`${P}debug silence @pessoa\`._`,
        ].join("\n"),
      },
    },

    // ── &rss ─────────────────────────────────────────────
    rss: {
      feeds: {
        titulo: "rss add/remove",
        texto: [
          `\`${P}rss add <url>\` — valida o feed e cadastra`,
          `\`${P}rss list\` — os feeds com seus IDs`,
          `\`${P}rss remove <id|url>\` — remove`,
          "",
          "**Ao adicionar**, tudo que já está no feed é marcado como visto — você",
          "recebe só o que sair **daí em diante**. Sem isso, o primeiro ciclo",
          "despejaria o histórico inteiro no canal.",
          "",
          "**O ciclo**",
          `\`${P}rss canal aqui\` — onde publicar (obrigatório)`,
          `\`${P}rss agora\` — força um ciclo imediato`,
          "Automático a cada hora, com teto de itens por ciclo.",
          "",
          "_Onde a IA está ligada, a Judy escreve um resumo antes da lista._" + IA_TAG,
        ].join("\n"),
      },
    },

    // ── &tutorial ────────────────────────────────────────
    tutorial: {
      areas: {
        titulo: "tutorial <área>",
        texto: [
          "O tutorial é dividido por assunto — cada um explica o caminho, não só o comando.",
          "",
          `\`${P}tutorial\` — o guia em 6 páginas (reaja ◀ ▶, ou \`${P}tutorial 3\`)`,
          "",
          "**Preparar o servidor**",
          `\`${P}tutorial permissoes\` · \`${P}tutorial canais\` (os 3 tipos) · \`${P}tutorial moderacao\` · \`${P}tutorial logs\``,
          `\`${P}tutorial cargos\` · \`${P}tutorial mensagens\` · \`${P}tutorial ajustes\``,
          "",
          "**Jogo e comunidade**",
          `\`${P}tutorial xp\` · \`${P}tutorial game\` (configurar o RPG)`,
          `\`${P}tutorial rpg\` · \`${P}tutorial aventura\` · \`${P}tutorial economia\``,
          `\`${P}tutorial noticias\``,
          `\`${P}tutorial ia\` — a Judy` + IA_TAG,
          "",
          `_Aceito os nomes em inglês também (\`moderation\`, \`roles\`, \`levels\`…)._`,
          `_Para a referência seca de um comando, use \`${P}help <comando>\`._`,
        ].join("\n"),
      },
    },
  };
}

// ══════════════════════════════════════════════════════════
//  ENGLISH
// ══════════════════════════════════════════════════════════
function arvoreEN(P) {
  return {
    game: {
      admin: {
        titulo: "game admin",
        texto: [
          "**Bot owner only.** Tools to set up and debug the RPG.",
          "",
          "**Give things to someone** _(with no @person, it's for you)_",
          `\`${P}game admin dar <qty> [@person]\` — credits currency`,
          `\`${P}game admin item <name> [@person]\` — grants a catalog item`,
          `\`${P}game admin follower <name> [level] [@person]\` — grants a companion`,
          `\`${P}game admin pontos <n> [@person]\` — grants free attribute points`,
          `\`${P}game admin nivel <n> [@person]\` — forces the character's level`,
          "",
          "**Unblock**",
          `\`${P}game admin energia [@person]\` — refills companions' energy`,
          `\`${P}game admin cooldown [@person]\` — clears mission wait and recovery`,
          "",
          "**Economy**",
          `\`${P}game admin moeda\` — creates and configures currencies _(see \`${P}help game moeda\`)_`,
          `\`${P}game admin eco\` — economy numbers: P, multiplier, pot`,
          `\`${P}game admin dungeon <qty>\` — puts currency in the dungeon pot`,
          "",
          "**Test without breaking anything**",
          `\`${P}game admin teste\` — creates a test character and runs the whole game`,
          `\`${P}game admin simular <mission> [n]\` — runs the mission n times, no real effect`,
          "",
          "**Start over** _(requires \`confirmar\`)_",
          `\`${P}game admin reset servidor confirmar\` — erases progress`,
          `\`${P}game admin reset catalogo confirmar\` — erases the curated catalog`,
          `\`${P}game admin reset tudo confirmar\` — both`,
        ].join("\n"),
      },
      moeda: {
        titulo: "game admin moeda",
        texto: [
          "**Bot owner only.** The server's currencies — each with its own economy.",
          "",
          "**One at a time, from the catalog**",
          `\`${P}game admin moeda perfil\` — the 12 ready-made currencies, by group`,
          `\`${P}game admin moeda perfil <id>\` — adds one · several: \`perfil brl xau btc\``,
          "💵 Real · Dollar · Euro · Pound Sterling",
          "🥇 Copper · Silver · Gold     💎 Emerald · Diamond",
          "₿ Monero · Ethereum · Bitcoin",
          "All on the same value scale, so mixing is safe: each one's supply is",
          "born inversely proportional to its value.",
          "",
          "**Closed sets**",
          `\`${P}game admin moeda modelo mundo\` — Real, Dollar, Euro, Silver, Gold, Bitcoin`,
          `\`${P}game admin moeda modelo fantasia\` — Copper, Silver, Gold, Crystal`,
          `\`${P}game admin moeda modelo simples\` — a single currency`,
          "",
          "**One by one**",
          `\`${P}game admin moeda\` — lists the existing ones`,
          `\`${P}game admin moeda ver <id>\` — full sheet and what it pays`,
          `\`${P}game admin moeda criar <id> <name> [symbol] [field=value …]\``,
          `\`${P}game admin moeda set <id> <field> <value>\` — adjusts one field`,
          `\`${P}game admin moeda padrao <id>\` — sets the main one (prices show in it)`,
          `\`${P}game admin moeda remover <id>\` — deletes the currency **and its balances**`,
          `\`${P}game admin moeda duplicadas\` — merges currencies sharing a name`,
          "",
          "**Duplicates**",
          "Two sets can bring the same currency under different ids (`mundo` brings",
          "Silver as `xag`, `fantasia` as `prata`). That's blocked at creation now —",
          "and older databases are repaired on the first boot.",
          "The merge **sums** balances, stock and pot into the one that stays; nothing is lost.",
          "",
          "**Fields you can adjust**",
          "`dificuldade` — how rare it is in missions",
          "`finita` — whether the total in circulation is capped",
          "`mercado` — the stock outside wallets",
          "",
          `_The \`id\` is the short name used in commands: letters and numbers, no spaces._`,
        ].join("\n"),
      },
      mercado: {
        titulo: "game mercado",
        texto: [
          "Trade **between players**, with escrow: what you list leaves your wallet and",
          "stays with me until it closes or you cancel. Without that, it becomes a scam.",
          "",
          `\`${P}game mercado\` — lists the open offers`,
          `\`${P}game mercado vender <item> <price>\` — lists an item of yours`,
          `\`${P}game mercado comprar <#>\` — closes someone's offer`,
          `\`${P}game mercado cancelar <#>\` — takes yours down and returns it`,
          "",
          "**Market cousins**",
          `\`${P}game cambio\` — currency exchange _(see \`${P}help game cambio\`)_`,
          `\`${P}game trocar [@person] <your item> por <their item>\` — item for item`,
          `\`${P}game trocar aceitar <#>\` — closes a barter offered to you`,
          "",
          "_Every sale pays a market fee; it grows with the offer's value._",
          `_System shop (fixed price, no other player): \`${P}game comprar\` and \`${P}game vender\`._`,
        ].join("\n"),
      },
      magia: {
        titulo: "game magias",
        texto: [
          "Magic is what gives the **Mana** attribute a purpose. It used to come",
          "only from companions; now you can buy your own and carry a grimoire.",
          "",
          `\`${P}game magias\` — the catalog and what you already know`,
          `\`${P}game magia <name>\` — the sheet: cost, power, price in each currency`,
          `\`${P}game aprender <name> [com <currency>]\` — buys the spell`,
          "",
          "**Mana is the limit, not the collection**",
          "Spells enter from the **strongest down**, while the Mana lasts. Learning",
          "ten doesn't help if you only have Mana for two — the others sit dormant",
          "(💤 in the list) until you raise Mana.",
          "",
          "**Two schools**",
          "🔥 **Attack** — raises the chance of completing the mission",
          "✨ **Support** — raises the chance of coming back alive",
          "",
          "**Shares mana with followers**",
          "Companion spells join the same contest. A party of mages with low Mana",
          "wastes power — it's worth balancing.",
          "",
          "_Level gates the strongest ones (🔒 in the list). Charisma discounts the_",
          "_price, same as hiring a mercenary._",
        ].join("\n"),
      },
      cambio: {
        titulo: "game cambio",
        texto: [
          "Two ways to exchange currency, and they serve different purposes.",
          "",
          "**What it's worth in every currency**",
          `\`${P}game cambio <qty> <currency>\` — the value in every other one`,
          `   e.g. \`${P}game cambio 1 bitcoin\``,
          `\`${P}game cambio taxas\` — the full table, each one against each one`,
          "",
          "**With the bank — instantly, no one else needed**",
          `\`${P}game cambio <qty> <currency> para <currency>\``,
          `   e.g. \`${P}game cambio 1000 real para dolar\``,
          "",
          "**With another player — you set the rate**",
          `\`${P}game cambio <qty> <currency> por <qty> <currency>\``,
          `   e.g. \`${P}game cambio 100 real por 5 dolar\``,
          "The amount leaves your wallet and sits in escrow until someone accepts",
          `or you cancel it with \`${P}game mercado cancelar <#>\`.`,
          "",
          "**Where the bank's rate comes from**",
          "Two things: the currency's **difficulty** (how rare it is to earn — that's",
          "the backing) and its **P** (how much sits idle in wallets — that's the",
          "inflation). So the rate moves on its own as the server plays.",
          "",
          "**Fractions are money**",
          "Expensive currency is bought in pieces: 112 Reais become 1.24 Monero,",
          "not 1. What's left over stays yours. You can type fractions too:",
          `\`${P}game cambio 0,5 xau para brl\` (dot or comma, either works).`,
          "",
          "**Why A→B→A doesn't make you rich**",
          "Every exchange charges a spread. A round trip costs more than the swing",
          "gives back, so churning currency just burns your balance.",
          "",
          "_Finite currencies have stock: if the bank runs short it says so —",
          "and the player counter stays open._",
        ].join("\n"),
      },
      missao: {
        titulo: "game missao",
        texto: [
          `\`${P}game missao\` — lists the missions with each one's chance`,
          `\`${P}game missao <name>\` — sets out on the mission`,
          "",
          "**The types**",
          "🏪 **Market** — no risk, pays little, no long cooldown",
          "🟢 **Easy** · 🟡 **Medium** · 🔴 **Hard** — risk and reward rise together",
          "",
          "**The chance that matters**",
          "The 🏆 shown is `success × survival` — the chance to finish **and** come back.",
          "A mission at 53% success with 75% survival only completes 40% of the time.",
          "",
          "**What changes the outcome**",
          "• your attributes and gear",
          `• the companions in your party (\`${P}game follower levar <name>\`)`,
          "• Luck improves loot; Intelligence and Luck increase XP",
          "",
          "**The two waits**",
          "Each mission has its own cooldown: 10 min for market, 20 easy, 45 medium,",
          "90 hard. If you fell, add ~30 min of recovery — the two run **together**,",
          `so what counts is the longer one. The list (\`${P}game missao\`) marks with`,
          "⏳ how long each one has left: after falling on a hard mission, the light",
          "ones come back much sooner.",
          "",
          "**If you fall**",
          "You lose part of the currency you carry (it goes to the dungeon pot), spend",
          "~30 min recovering, and on medium/hard missions companions may be captured —",
          `rescue them with \`${P}game dungeon\`.`,
        ].join("\n"),
      },
      follower: {
        titulo: "game follower",
        texto: [
          "Companions fight with you and change mission odds considerably.",
          "",
          `\`${P}game followers\` — yours, and who's in the party`,
          `\`${P}game follower ficha <name>\` — attributes, spell, energy and bag`,
          `\`${P}game follower levar <name>\` — adds to the party (max **2**)`,
          `\`${P}game follower tirar <name>\` — back to the bench`,
          `\`${P}game follower dispensar <name>\` — lets them go for good`,
          `\`${P}game follower fotos <name>\` — their album`,
          "",
          "**Their bag**",
          `\`${P}game follower dar <name> <item>\` — hands them an item to carry`,
          `\`${P}game follower pegar <name> <item>\` — takes the item back`,
          "",
          "_Both names can have spaces_ — `dar Curandeira Errante Espada",
          "Temperada` works: I try every split until both sides match something",
          "real. If it stays ambiguous, separate them with `|`:",
          `\`${P}game follower dar Curandeira Errante | Espada Temperada\``,
          "Each companion carries up to **2** items, and their bonuses add to",
          "THEIR attributes — it's the natural destination for gear you've",
          "outgrown, instead of selling everything. The sheet shows the base and,",
          "in parentheses, what the bag adds.",
          "",
          "**Energy** ⚡",
          "Each dungeon mission spends 1. It returns on its own (1 per hour) or all at",
          `once with \`${P}game descansar confirmar\`, for a price.`,
          "",
          "**Where they come from**",
          `\`${P}game recrutas\` — everyone who exists in the game`,
          `\`${P}game contratar <name>\` — buys one (your Charisma gives a discount)`,
          "Dungeon loot — some only show up that way 🗝️",
        ].join("\n"),
      },
      dungeon: {
        titulo: "game dungeon",
        texto: [
          "When you fall on a mission, two things happen: the lost currency becomes the",
          "**pot**, and companions may be left **captured** there.",
          "",
          `\`${P}game dungeon\` — who's held right now`,
          "",
          "**The rescue is automatic**",
          "There's no rescue command: every mission you **come back from** is an",
          "attempt. Completing the mission gives the full chance; coming back",
          "without completing it gives half; falling gives none — you were in no",
          "shape to pull anyone out.",
          "",
          "**The rules**",
          "• The original owner has a much better chance.",
          "• In the first hours, **only** the owner rescues (priority window).",
          "• After the window, anyone's mission can free them — and whoever",
          "  frees them keeps them.",
          "• One attempt per mission, and yours come first.",
          "",
          "_The currency pot is the prize for beating the dungeon; see it in_ "
            + `\`${P}game carteira\`.`,
        ].join("\n"),
      },
      itens: {
        titulo: "game itens",
        texto: [
          `\`${P}game itens\` — your bag, grouped by rarity`,
          `\`${P}game equipar <item>\` — equips it (✅ marks what's in use)`,
          `\`${P}game equipar <item> acessorio2\` — picks the accessory slot`,
          `\`${P}game desequipar <slot or item>\` — removes it back to the bag`,
          `\`${P}game catalogo\` — summary of everything in the game`,
          `\`${P}game catalogo raro\` — the full list for that rarity`,
          `\`${P}game catalogo arma\` — filters by slot`,
          `\`${P}game item <name>\` — ONE item's sheet: price, stock, bonuses`,
          "",
          "**The 6 slots**",
          "arma · capacete · armadura · acessorio1 · acessorio2 · acessorio3",
          `The sheet (\`${P}game\`) lists all six, **empty ones included** — it's the`,
          "quick way to see where you can still improve.",
          "",
          "**Price in each currency**",
          `\`${P}game item <name>\` shows the cost in EVERY currency on the server,`,
          "with a ✅ on the ones you can afford. To buy with a specific one:",
          `\`${P}game comprar <item> com <currency>\`.`,
          "",
          "_Gear bonuses show on the sheet next to the base value, like this: `12 (+3)`._",
          `_Selling: \`${P}game vender <item>\` (Charisma improves what you're paid)._`,
        ].join("\n"),
      },
      pontos: {
        titulo: "game pontos",
        texto: [
          `\`${P}game pontos <attribute> [how many]\` — spends your free points`,
          "",
          "**Attributes** _(abbreviations accepted: for, des, res, agi, int, sor, car…)_",
          "⚔️ **Strength** — damage and success in direct combat",
          "🏃 **Dexterity** · 🌀 **Agility** — dodging and survival",
          "🛡 **Resistance** — enduring the mission without falling",
          "🧠 **Intelligence** — more XP and more points per level",
          "🍀 **Luck** — better loot, more XP, more points",
          "✨ **Charisma** — better selling price and hiring discount",
          "",
          "**How you earn points**",
          "By leveling up. How much you get per level depends on Intelligence and Luck —",
          "with diminishing returns, so investing in them never stops paying off.",
          "",
          "_Each level also gives an automatic gain to **all** attributes._",
        ].join("\n"),
      },
    },

    xp: {
      setup: {
        titulo: "xp setup",
        texto: [
          "Setup wizard for the leveling system. **Requires ManagePermissions.**",
          "",
          `\`${P}xp setup\` — shows the current configuration`,
          `\`${P}xp setup multiplicador <1–5>\` — curve difficulty (e.g. 1.5)`,
          `\`${P}xp setup nivelmaximo <5–1000>\` — the cap`,
          `\`${P}xp setup intervalo <5|10>\` — how often a level role comes`,
          `\`${P}xp setup xp <min> <max>\` — how much each message pays`,
          `\`${P}xp setup cooldown <seconds>\` — minimum interval between gains`,
          `\`${P}xp setup canal <aqui|off>\` — where to announce level ups`,
          `\`${P}xp setup anuncio <on|off>\` — announce or not`,
          "",
          "**The order that works**",
          `1. \`${P}xp setup\` and adjust what you want`,
          `2. \`${P}xp criarcargos\` — creates the level roles`,
          `3. \`${P}xp on\` — turns the system on`,
          "",
          "_XP comes from messages only: Stoat doesn't emit voice events, so there's no_",
          "_reliable way to time voice calls._",
        ].join("\n"),
      },
      cargos: {
        titulo: "xp cargos",
        texto: [
          `\`${P}xp cargos\` — lists the level roles already configured`,
          `\`${P}xp criarcargos\` — creates them automatically, one every N levels`,
          "",
          "**Hierarchy safety**",
          "Every role created here is positioned **below** the silence role, so nobody",
          "can use a level role to escape a mute. If you don't have a silence role yet,",
          `create one with \`${P}cargomudo\` and run \`${P}xp criarcargos\` again to reorder.`,
          "",
          "_The bot needs **ManageRole**, and its role must sit above the ones it creates._",
        ].join("\n"),
      },
    },

    acesso: {
      cargo: {
        titulo: "acesso cargo",
        texto: [
          "Roles that count as **staff** — they use the moderation commands even without",
          "Stoat's native permission. Useful to grant moderation power without handing",
          "over real server permissions.",
          "",
          `\`${P}acesso cargo add <@role|id>\``,
          `\`${P}acesso cargo remove <@role|id>\``,
          `\`${P}acesso cargo limpar\` — back to native permissions only`,
          "",
          "_It doesn't cover **ManageServer**: real administration still requires the_",
          "_real permission. Configuring requires ManagePermissions._",
        ].join("\n"),
      },
      canal: {
        titulo: "acesso canal",
        texto: [
          "Where the commands work — so they don't pollute the chat channels.",
          "",
          "**Modes**",
          `\`${P}acesso canal todos\` — in any channel (default)`,
          `\`${P}acesso canal somente\` — only in the listed channels`,
          `\`${P}acesso canal exceto\` — everywhere except the listed ones`,
          "",
          "**The list** _(with no #channel, it uses the one you typed in)_",
          `\`${P}acesso canal add [#channel]\``,
          `\`${P}acesso canal remove [#channel]\``,
          `\`${P}acesso canal limpar\``,
          "",
          "**Staff**",
          `\`${P}acesso staffignora on|off\` — whether staff bypasses the restriction`,
          "",
          "_In `todos` mode the list still exists, but has no effect._",
        ].join("\n"),
      },
    },

    banglobal: {
      varrer: {
        titulo: "banglobal varrer",
        texto: [
          "The global ban acts when someone **joins**. Anyone already here when they got",
          "banned elsewhere went unnoticed — the sweep closes that blind spot.",
          "",
          `\`${P}banglobal varrer ver\` — only shows who would show up, bans nobody`,
          `\`${P}banglobal varrer\` — checks and **acts** according to the current mode`,
          "",
          "**What it does depends on the mode**",
          "`off` — the sweep only works in `ver` mode",
          "`avisar` — lists who is on the list, without acting",
          "`banir` — bans whoever is on the list",
          "",
          "_The bot must be able to see the members and have **BanMembers**, with its role_",
          "_above the person's role. Failures appear at the end of the report._",
        ].join("\n"),
      },
      contribuicao: {
        titulo: "banglobal contribution",
        texto: [
          "**Every server the bot is in feeds the list. Always.**",
          "There's no command to enable, disable or import by hand.",
          "",
          "**What goes in on its own**",
          "• **New** bans — the moment they happen (automod or `&ban`).",
          "• **Old** bans — synced ~1 min after the bot boots and every 6h.",
          "• A **new** server — its history goes in as soon as the bot is added.",
          "",
          "**What's still your choice**",
          `\`${P}banglobal <off|avisar|banir>\` — whether THIS server benefits from the list.`,
          "You can opt out of using the list; you can't use it without feeding it.",
          "",
          "**If a record doesn't hold up**",
          `\`${P}banglobal esquecer <@user|id>\` — drops that record from the list`,
          `\`${P}banglobal historico <@user|id>\` — where and why they were banned`,
          "",
          "_Existing records aren't duplicated._",
          "_Worth a thought before adding the bot to someone else's server: their moderation standards become yours._",
        ].join("\n"),
      },
    },

    punicao: {
      escada: {
        titulo: "punicao escada",
        texto: [
          "In `acumular` mode, each repeat offence climbs a step. The default:",
          "",
          "**1.** warning",
          "**2.** 5 min silence",
          "**3.** 1 h silence",
          "**4.** ban",
          "",
          "**Why a ladder and not a counter**",
          "It used to be N warnings and then a ban, with nothing in between. That",
          "punished a one-off slip the same as a deliberate attack, and gave an",
          "ordinary member a wildly disproportionate scare on the only punishment",
          "they ever saw. The ladder adds weight gradually and, above all, gives a",
          "**chance**: whoever stops at the first step never reaches the last.",
          "",
          "**Changing it**",
          `\`${P}punicao escada\` — shows the current ladder`,
          `\`${P}punicao escada aviso,10m,2h,ban\` — longer at each step`,
          `\`${P}punicao escada aviso,ban\` — a single warning before the ban`,
          "",
          "Accepts `aviso`, `ban` and durations like `30s`, `10m`, `2h`, `1d`.",
          "A ban is always the last step, even if you don't write it.",
          "",
          `_Silence steps need a silence role: \`${P}cargomudo\` creates one._`,
          "_The deadline lives in the database, so a 1 h mute survives a bot restart._",
        ].join("\n"),
      },
    },

    sentinela: {
      antiguidade: {
        titulo: "sentinela antiguidade",
        texto: [
          "The sentinel is the only module that **judges** instead of measuring —",
          "and so the only one whose strictness changes with who is writing.",
          "",
          "**The idea**",
          "An account created minutes ago that arrives posting links and talking",
          "about sales is the classic scam pattern. The same sentence from someone",
          "who's been here for weeks is almost always a joke the detector misses.",
          "",
          "**Tenure is measured by XP level**",
          "Stoat doesn't reliably expose the join date. Level works better: it only",
          "grows by talking, over time — which is exactly what we want to measure.",
          "With XP off, everyone is treated as a newcomer, which is the safe side",
          "to err on.",
          "",
          "| level | band | threshold (base 6) |",
          "|---|---|---|",
          "| 0 | newcomer | 4.5 |",
          "| 1–2 | getting known | 5.0 |",
          "| 3–5 | regular | 5.5 |",
          "| 6–10 | established | 6.0 |",
          "| 11+ | veteran | 6.5 |",
          "",
          "There's a floor and a ceiling: no veteran is immune, and no newcomer",
          "gets punished over nothing.",
          "",
          `\`${P}sentinela antiguidade on|off\``,
          "",
          "_Applies ONLY to the sentinel. Spam, caps, links, mentions, repetition_",
          "_and characters measure exact things — there the limit is the same for all._",
        ].join("\n"),
      },
      alerta: {
        titulo: "sentinela alerta",
        texto: [
          "Pings the staff when someone raises suspicion **repeatedly** in a short",
          "window — even without reaching the punishment threshold.",
          "",
          "**Why it's separate from punishing**",
          "Not every suspicious pattern deserves a punishment, but every suspicious",
          "pattern deserves human eyes **while it's happening**. It's exactly the",
          "borderline case — high score, but not high enough — that moderation",
          "needs to see before the bot decides on its own.",
          "",
          "**How it triggers**",
          "3 signals in 10 minutes from the same person. One signal is noise.",
          "After alerting, it stays quiet about that person for 30 min: an alert",
          "that repeats becomes noise and staff stop reading it.",
          "",
          "**What the alert carries**",
          "Who, how many times, the profile (newcomer/veteran and level), the",
          "highest score, the signals seen, and the action commands.",
          "",
          `\`${P}sentinela alerta on|off\``,
          `\`${P}sentinela channel <id|here>\` — where to alert (falls back to the log channel)`,
          `_Pings the roles from \`${P}acesso cargo\`._`,
        ].join("\n"),
      },
    },

    cor: {
      painel: {
        titulo: "cor painel",
        texto: [
          "Does everything for you: creates the colored roles, posts the picker message,",
          "reacts with one emoji per color and wires the reaction roles in exclusive mode.",
          "",
          `\`${P}cor painel aqui\` — panel in this channel, with every color`,
          `\`${P}cor painel <channel-id>\` — posts in another channel`,
          `\`${P}cor painel aqui fogo gelo neon\` — only the colors you list`,
          `\`${P}cor criar\` — only creates and paints the roles, posts nothing`,
          "",
          "**Exclusive by default:** picking a color removes the previous one. That's what",
          "makes sense for color — nobody wants two at once.",
          "",
          "_The bot needs **ManageRole**, **React** in the channel, and its role must sit_",
          "_above the color roles._",
        ].join("\n"),
      },
      gradiente: {
        titulo: "cor gradiente",
        texto: [
          "Stoat's role color field accepts **any CSS color** — which is why gradients",
          "work here, not just hex.",
          "",
          `\`${P}cor <role> gradiente #FF0000 #0000FF\` — from one color to another`,
          `\`${P}cor <role> gradiente 45 vermelho azul\` — the leading number is the angle`,
          `\`${P}cor <role> preset fogo\` — one of the ready-made ones (\`${P}cor presets\`)`,
          `\`${P}cor <role> linear-gradient(90deg, #f00 0%, #00f 100%)\` — raw CSS`,
          "",
          "**The classic gotcha**",
          "Writing `gradient(...)` without the `linear-` returns a 400 error. It's the",
          "number-one failure here — the validation warns you before trying.",
          "",
          `_Solid color: \`${P}cor <role> #FF00AA\` or a name (\`roxo\`)._`,
          `_Back to default: \`${P}cor <role> remover\`._`,
        ].join("\n"),
      },
    },

    reactionrole: {
      exclusivo: {
        titulo: "reactionrole exclusivo",
        texto: [
          "Sets whether a person can stack that message's roles or whether picking one",
          "**swaps** the previous.",
          "",
          `\`${P}reactionrole exclusivo <message> on\` — swaps (color, age, team)`,
          `\`${P}reactionrole exclusivo <message> off\` — stacks (interests, games)`,
          "",
          "In exclusive mode the bot also **removes the old reaction**, so the panel",
          "reflects the current choice.",
          "",
          "_The message can be its ID or link. It must already have rules registered._",
        ].join("\n"),
      },
      recarregar: {
        titulo: "reactionrole recarregar",
        texto: [
          "**The symptom:** it worked, the bot restarted, it stopped granting roles — but",
          "the emojis are still there.",
          "",
          "**The cause:** the library only emits reaction events for messages it knows.",
          "After a restart, old messages aren't in the cache.",
          "",
          `\`${P}reactionrole recarregar\` — fetches the messages back into the cache`,
          "",
          "This already runs **automatically on every restart**; the command exists for",
          "when you want to force it, or to diagnose what wasn't found.",
          "",
          "_Message not found = channel deleted, or the bot lacks \\`ViewChannel\\`/_",
          "_\\`ReadMessageHistory\\`._",
        ].join("\n"),
      },
    },

    log: {
      eventos: {
        titulo: "log <event>",
        texto: [
          "Each category toggles on its own: `&log <event> <on|off>`.",
          "",
          "`punicoes` — warnings, silences and bans (automod and manual)",
          "`membros` — server joins and leaves",
          "`mensagens` — deleted and edited messages",
          "`cargos` — roles created and roles granted to someone",
          "`comandos` — command usage attempts",
          "",
          "**Example**",
          `\`${P}log mensagens off\` — stops logging edits/deletions`,
          "",
          `_All start enabled. Set the channel with \`${P}log channel here\` (or a mention, link, ID, name)._`,
          "_Entries in the log channel are always written in Portuguese._",
        ].join("\n"),
      },
    },

    chat: {
      livre: {
        titulo: "chat livre",
        texto: [
          "Makes Judy join the channel **without needing a mention**.",
          "",
          `\`${P}chat livre on\` — enables it in this channel`,
          `\`${P}chat livre off\` — disables it`,
          `\`${P}chat livre modo relevante\` — she only answers what she judges important`,
          `\`${P}chat livre modo todas\` — she answers every message`,
          "",
          "_One conversation at a time: while she answers someone, the others wait._",
          "_Requires ManagePermissions._",
        ].join("\n"),
      },
      memoria: {
        titulo: "chat esquecer / perfil",
        texto: [
          "Judy keeps facts about whoever talks to her, plus a profile per person.",
          "",
          `\`${P}chat perfil [@person]\` — what she knows`,
          `\`${P}chat mapear [@person]\` — captures bio/status from the profile card`,
          `\`${P}chat esquecer\` — erases everything about **you**`,
          `\`${P}chat esquecer tudo\` — erases the whole server's memory _(ManageServer)_`,
          `\`${P}chat cuidado [@person] on|off\` — gentle treatment, no acid irony`,
          "",
          "_Anyone can turn `cuidado` on for themselves; for others it needs ManagePermissions._",
        ].join("\n"),
      },
      comentar: {
        titulo: "chat comentar",
        texto: [
          "Judy drops comments **on her own initiative** about the ongoing conversation —",
          "only in the chosen channel, and with brakes so it doesn't become spam.",
          "",
          `\`${P}chat comentar aqui\` — enables it in this channel`,
          `\`${P}chat comentar off\` — disables it`,
          `\`${P}chat comentar pordia <1–20>\` — daily cap (default 4)`,
          `\`${P}chat comentar status\` — how it stands now`,
          "",
          "_She doesn't start topics out of nowhere: she only comments on what's happening._",
        ].join("\n"),
      },
    },

    modia: {
      criterios: {
        titulo: "modia criterios",
        texto: [
          "You write **in natural language** what should be moderated. There's no word",
          "list: Judy reads the message and judges it by what you described.",
          "",
          `\`${P}modia criterios <text>\``,
          "",
          "**A good example** _(specific, and says what NOT to moderate too)_",
          "```",
          `${P}modia criterios Delete promos for other servers, account selling and`,
          "direct personal attacks. Don't moderate mild swearing or heated discussion.",
          "```",
          "",
          "**What she does on a hit:** deletes the message and pings the owner in the log",
          "channel with the options. **She never bans on her own.**",
          "",
          `_Enable after defining: \`${P}modia on\`. Requires ManageServer._`,
        ].join("\n"),
      },
    },

    debug: {
      canais: {
        titulo: "debug canais",
        texto: [
          "In Stoat, **channel** permissions beat role permissions: the bot can have",
          "SendMessage server-wide and still be mute in one channel. This report exposes",
          "exactly that.",
          "",
          `\`${P}debug canais\` — what I can see and do in each channel`,
          `\`${P}debug canais cru\` — what the API returns (for diagnosis)`,
          "",
          "**How to read it**",
          "⚠️ **Missing the essentials** — I can't reply there",
          "🚫 **I can't see** — no ViewChannel",
          "🟡 **Ok, but incomplete** — missing React or ManageMessages",
          "✅ **All good**",
          "❔ **Couldn't evaluate** — run the `cru` version",
        ].join("\n"),
      },
      silence: {
        titulo: "debug silence",
        texto: [
          "Answers the question that matters: **will the silence actually mute this person?**",
          "",
          `\`${P}debug silence\` — checks the silence role's coverage across channels`,
          `\`${P}debug silence @person\` — checks whether their roles override the silence`,
          "",
          "**The two ways a mute fails**",
          "1. The role isn't denied in some channel with its own permissions —",
          `   fix it with \`${P}cargomudo canais\`.`,
          "2. The person has a role **above** the silence one that allows speaking —",
          "   move the silence role up, or remove SendMessage from the other one.",
          "",
          "_The server owner is never silenced: no permission reaches them._",
        ].join("\n"),
      },
    },

    blocklist: {
      dominios: {
        titulo: "blocklist adddomain",
        texto: [
          "Two different things live here: **sources** (whole Pi-hole lists, with millions",
          "of domains) and **manual domains** (one by one, yours).",
          "",
          "**Sources**",
          `\`${P}blocklist add <url>\` — downloads and incorporates a list`,
          `\`${P}blocklist remove <url>\` — removes the source`,
          "",
          "**Manual**",
          `\`${P}blocklist adddomain 02giga.link\``,
          `\`${P}blocklist removedomain 02giga.link\``,
          "",
          "**Maintenance**",
          `\`${P}blocklist list\` — sources, manual entries and the total loaded`,
          `\`${P}blocklist reload\` — re-downloads everything`,
          `\`${P}blocklist clear\` — wipes sources and manual entries`,
          "",
          "_The list is **global** to the bot, not per server: once downloaded, it applies to all._",
          "_The finished index is cached on disk: after a restart, the anti-link wakes up already armed._",
          "_If a source fails during `reload`, the current list is kept — it never shrinks because of a network hiccup._",
        ].join("\n"),
      },
    },

    // ── &staff / &welcome / &goodbye ─────────────────────
    fuso: {
      cidades: {
        titulo: "fuso (timezones)",
        texto: [
          "A server clock showing **several cities at once** — for when people are",
          "spread out and every plan turns into mental arithmetic.",
          "",
          "**Viewing** _(anyone)_",
          `\`${P}fuso\` — the current time in each city on the list`,
          `\`${P}fuso ver <city>\` — any city's time, no setup needed`,
          `\`${P}fuso buscar <term>\` — search available cities`,
          `\`${P}fuso <city>\` — shortcut for \`ver\``,
          "",
          "**Configuring** _(ManageMessages)_",
          `\`${P}fuso add <city>\` · \`${P}fuso remove <city>\``,
          `\`${P}fuso apelido <city> <text>\` — e.g. Madrid showing as \"Europe\"`,
          `\`${P}fuso principal <city>\` — which city the differences count from`,
          `\`${P}fuso formato <12|24>\` · \`${P}fuso limpar\``,
          "",
          "**How to write the city**",
          "Accents work (`São Paulo`), so does the `City/Country` format",
          "(`Madrid/Europa`), and there are built-in nicknames: `sp`, `nova york`,",
          "`toquio`, `londres`, `utc`. On a tie, the bot shows you the options.",
          "",
          "_The list is sorted from the earliest offset to the latest — the way the eye_",
          "_expects to read a world clock. The limit is 12 cities._",
        ].join("\n"),
      },
    },

    staff: {
      equipe: {
        titulo: "staff",
        texto: [
          "The **server's staff**, grouped by role, showing who holds each one.",
          "",
          "**The list isn't a separate registry.** It reads the very same roles that",
          `\`${P}acesso cargo\` uses to decide who may moderate. Promoting with`,
          `\`${P}staff add\` is a real promotion; removing here removes the access too.`,
          "That way the notice board can never disagree with the actual permission.",
          "",
          "**Commands** _(changing requires ManagePermissions; viewing is public)_",
          `\`${P}staff\` — show the team`,
          `\`${P}staff add <@role>\` — mark the role as staff`,
          `\`${P}staff remove <@role>\` — unmark it`,
          `\`${P}staff title <@role> <text>\` — label instead of the role's name`,
          `\`${P}staff clear\` — empty the list`,
          "",
          "_Order follows insertion: the first role added shows up on top._",
        ].join("\n"),
      },
    },
    boasvindas: {
      mensagens: {
        titulo: "welcome / goodbye",
        texto: [
          `Embeds posted when someone **joins** (\`${P}welcome\`) or **leaves**`,
          `(\`${P}goodbye\`) the server. Both have exactly the same options.`,
          "",
          "**Configure**",
          `\`${P}welcome channel here\` — where to post _(turns it on)_`,
          `\`${P}welcome title <text>\` · \`${P}welcome text <description>\``,
          `\`${P}welcome colour <colour>\` · \`${P}welcome image <url|clear>\``,
          `\`${P}welcome test\` — posts using you as the example`,
          `\`${P}welcome default\` — back to the factory text`,
          `\`${P}welcome on|off\` — toggle without losing what you wrote`,
          "",
          "**Markers**",
          "`{usuario}` — clickable mention · `{nome}` — just the name",
          "`{servidor}` — server name · `{membros}` — member count",
          "",
          "_In farewells `{usuario}` becomes the **name**, not a mention: whoever left_",
          "_isn't on the server anymore and the mention would show as a raw ID._",
          "",
          "_The text accepts multiple lines; `\\n` also becomes a line break._",
          "",
          "**About the image**",
          "There are **two different results**, depending on where the link comes from:",
          "• **Stoat attachment** → the image becomes the **embed's cover**. Best result.",
          "• **External link** → shows as a **preview below** the embed.",
          "  _(Stoat's cover field only accepts its own attachments, not external URLs.)_",
          "  The URL goes in masked, so **no giant link on screen**.",
          `  If the image doesn't show: \`${P}welcome image visible\` brings the raw URL back.`,
          "",
          "The recommended way is to **upload the file here on Stoat and use the attachment",
          "link**: the image then lives on Stoat's infrastructure, never rots, and nobody",
          "outside learns who saw the message.",
          "",
          "A third-party link works, but that site's owner **sees the IP of everyone who",
          "loads the message** — in a welcome message, everyone who joins.",
          "It must be the **file** link (`.png`, `.jpg`, `.gif`, `.webp`); a search-result",
          "link (Brave, Google, Bing) is a temporary thumbnail and usually fails.",
          "",
          "_Internal network addresses (`localhost`, `192.168.x`, Tailscale's `100.x`, ports",
          "outside 80/443) are **rejected**: storing them would create a shortcut into the",
          "bot machine's network. The bot never downloads the image — it only passes the link._",
          "If the image fails to send, the message still goes out — just without a cover.",
        ].join("\n"),
      },
    },

    embed: {
      campos: {
        titulo: "embed (fields)",
        texto: [
          "One field per line, in the `field: value` format. No parentheses around it and",
          "no trailing comma — the two most common mistakes (and I tolerate both).",
          "",
          "**Fields**",
          "`titulo:` — the title",
          "`descricao:` — the body; it can span several lines",
          "`cor:` — hex `#RRGGBB` or a name (`roxo`, `verde`…)",
          "`rodape:` — an italic line at the end",
          "`imagem:` — cover image URL",
          "`canal:` — an ID, to post in **another** channel",
          "",
          "**Also accepted**",
          "• English keys (`title`, `description`, `color`…)",
          "• everything on one line, separated by `|`",
          "• `\\n` inside a value, for a line break",
          "",
          "_If something is ignored, I send it and tell you what I didn't understand — instead of failing silently._",
        ].join("\n"),
      },
    },

    comando: {
      gerenciar: {
        titulo: "comando disable/enable",
        texto: [
          `\`${P}comando\` — lists the commands and each one's state`,
          `\`${P}comando disable <name>\` — turns it off on this server`,
          `\`${P}comando enable <name>\` — turns it back on`,
          "",
          "**The safety latch**",
          "`help` and `comando` **can't** be disabled — otherwise you'd lock yourself out,",
          "with no way back.",
          "",
          "_It's per server: disabling here doesn't affect the others._",
          "_Use the canonical name (the one in the list), not an alias._",
        ].join("\n"),
      },
    },

    cargomudo: {
      canais: {
        titulo: "cargomudo canais",
        texto: [
          "Creating the role with everything denied **server-wide** isn't enough: a channel",
          "with its own permissions ignores that. So the denial is applied channel by channel.",
          "",
          `\`${P}cargomudo [name]\` — creates the role, denies everything and sets it as`,
          "   the punishment policy's silence role",
          `\`${P}cargomudo canais\` — **re-applies** the denial across channels, using the`,
          "   silence role already set",
          "",
          "**When to run it again**",
          "Whenever you create new channels — they're born without the denial.",
          "",
          `_To check whether the silence really mutes someone: \`${P}debug silence @person\`._`,
        ].join("\n"),
      },
    },

    rss: {
      feeds: {
        titulo: "rss add/remove",
        texto: [
          `\`${P}rss add <url>\` — validates the feed and registers it`,
          `\`${P}rss list\` — the feeds with their IDs`,
          `\`${P}rss remove <id|url>\` — removes one`,
          "",
          "**On adding**, everything already in the feed is marked as seen — you only get",
          "what comes out **from then on**. Without that, the first cycle would dump the",
          "whole history into the channel.",
          "",
          "**The cycle**",
          `\`${P}rss canal aqui\` — where to post (required)`,
          `\`${P}rss agora\` — forces an immediate cycle`,
          "Automatic every hour, with a cap on items per cycle.",
          "",
          "_Where the AI is enabled, Judy writes a digest before the list._" + IA_TAG,
        ].join("\n"),
      },
    },

    tutorial: {
      areas: {
        titulo: "tutorial <area>",
        texto: [
          "The tutorial is split by subject — each one explains the path, not just the command.",
          "",
          `\`${P}tutorial\` — the 6-page guide (react ◀ ▶, or \`${P}tutorial 3\`)`,
          "",
          "**Setting the server up**",
          `\`${P}tutorial permissoes\` · \`${P}tutorial canais\` (the 3 types) · \`${P}tutorial moderacao\` · \`${P}tutorial logs\``,
          `\`${P}tutorial cargos\` · \`${P}tutorial mensagens\` · \`${P}tutorial ajustes\``,
          "",
          "**Game and community**",
          `\`${P}tutorial xp\` · \`${P}tutorial game\` (setting up the RPG)`,
          `\`${P}tutorial rpg\` · \`${P}tutorial aventura\` · \`${P}tutorial economia\``,
          `\`${P}tutorial noticias\``,
          `\`${P}tutorial ia\` — Judy` + IA_TAG,
          "",
          `_English names work too (\`moderation\`, \`roles\`, \`levels\`…)._`,
          `_For a command's dry reference, use \`${P}help <command>\`._`,
        ].join("\n"),
      },
    },
  };
}

// Comandos cujos subtópicos só existem onde a IA está ligada.
export const SUBTOPICOS_SO_IA = new Set(["chat", "modia"]);
