import * as visaoMod from "./visao.js";
import { servidorPermitido as temIA } from "../ai/chat.js";
import { lingua } from "../core/i18n.js";
import { enviarPaginado, paginarLinhas } from "../core/paginas.js";

function AREAS(P, lang = "pt", comIA = false) {
  if (lang === "en") return {
    permissoes: {
      titulo: "🔑 Bot permissions",
      ordem: 0,
      resumo: "First of all: without these, nothing works.",
      corpo: [
        "In **Server settings → Roles**, give the bot's role:",
        "",
        "**Essentials**",
        "• `ViewChannel`, `ReadMessageHistory` — see and read the channels",
        "• `SendMessage`, `SendEmbeds` — reply",
        `• \`React\` — reactions (reaction roles${comIA ? ", Judy's 👀" : ""})`,
        "",
        "**To moderate**",
        "• `ManageMessages` — delete messages (automod, `&limpar`)",
        "• `KickMembers`, `BanMembers` — `&kick`, `&ban`, global bans",
        "• `TimeoutMembers` — timed silences (`&silenciar`)",
        "",
        "**To manage roles and channels**",
        "• `ManageRole` — **create** roles (level roles)",
        "• `AssignRoles` — **give** roles to someone (autorole, levels, reactions)",
        "• `ManageChannel` — create/edit channels",
        "",
        "⚠️ `ManageRole` and `AssignRoles` are **different** things: one creates the role, the other hands it to the person. Missing the second, the bot creates the roles and then fails to apply them.",
        "",
        "💡 The bot's role must sit **above** the roles it will manage in the role list.",
      ],
    },

    canais: {
      titulo: "🔀 Channels: the 3 types",
      ordem: 0.5,
      resumo: "Channel permission beats role permission. Sort every channel into one of 3 types.",
      corpo: [
        "**The rule that explains almost every \"why doesn't it work\":**",
        "a permission set **on the channel** overrides the one **on the role**. If a role can *Send messages* server-wide but the channel denies it, the role doesn't send. So: keep role permissions as the *minimum* and open exceptions per channel.",
        "",
        "Put every channel in one of **three types**:",
        "",
        "**🔒 Staff-only to see** — logs, Sentinel alerts, backstage",
        "• Channel → *Permissions* → **Default**: deny *View channel*",
        "• then, for each **staff role**: allow *View channel*",
        "",
        "**📢 Staff-only to write** — rules, announcements, reaction-role panels",
        "• **Default**: deny *Send messages* (keep *View channel* allowed)",
        "• for each **staff role**: allow *Send messages*",
        "",
        "**💬 General** — chat, off-topic, media",
        "• touch nothing; it inherits the server defaults",
        "",
        "**And the bot?** Give its role *View channel* + *Send messages* in the first two types too, or it can't log, alert, or post panels. " + "`&debug` checks that for you, channel by channel.",
        "",
        `💡 \`${P}assistente canais\` asks which channels are which type and lists exactly what to click.`,
      ],
    },

    moderacao: {
      titulo: "🛡️ Automatic moderation",
      ordem: 1,
      resumo: "The filters that act on their own and what happens to offenders.",
      corpo: [
        `**1. See the current state:** \`${P}automod\``,
        "Shows the 4 groups — antispam (floods), antiruido (noisy text), antilink (links and invites), sentinela (harmful content) — and each one's parts.",
        "",
        `**2. Toggle whatever you want:** \`${P}automod <group> on|off\` · one part only: \`${P}automod <group> <part> on|off\``,
        `**3. Go deeper:** \`${P}automod blocklist\`, \`${P}automod sentinela\`, \`${P}automod punicao\` — the whole family lives under \`${P}automod\`, and \`${P}help automod\` walks it`,
        `E.g.: \`${P}automod antilink on\` · \`${P}automod antiruido caps off\``,
        "",
        `**4. Set the punishment:** \`${P}automod punicao modo <avisar|apagar|confirmar|acumular|banir>\``,
        "• `avisar` — warn only (good for testing)",
        "• `apagar` — removes the message, doesn't punish the person",
        "• `confirmar` — deletes, silences and calls a moderator",
        "• `acumular` — climbs a ladder of punishments per repeat offence",
        "• `banir` — bans on the spot",
        "",
        `**5. If you use \`acumular\`:** \`${P}automod punicao escada\``,
        "The default ladder is **warning → 5 min silence → 1 h silence → ban**.",
        "Whoever stops at the first step never reaches the last; whoever insists climbs on their own.",
        "**Noise filters** (repeat, caps, emoji, speed): the 1st slip in 10 min is just a heads-up, with no warning — except new accounts and during a raid.",
        `Warnings reset after **30 days** without a new one (\`${P}automod punicao validade <days|0>\`).`,
        `Change it with \`${P}automod punicao escada aviso,10m,2h,ban\`. Mutes are the Stoat's native timeout: the bot needs **TimeoutMembers**.`,
        `**6. If you use \`confirmar\`:** the person is timed out until the staff decides (24 h at most) — the bot needs **TimeoutMembers**.`,
        "",
        `**Sentinel** (\`${P}automod sentinela\`, formerly \`scam\`): the only module that **judges** instead of measuring —`,
        "it scores the content for suspicion. Because it judges, it adapts:",
        "• **stricter with newcomers** — the threshold follows the member's XP level, so a brand new account",
        "  gets a closer look than someone who's been talking here for weeks",
        "• **alerts the staff** on a repeated *pattern*, before punishing anything",
        `\`${P}automod sentinela on\` · \`${P}automod sentinela sensitivity <baixa|media|alta>\` · \`${P}automod sentinela antiguidade on|off\``,
        `**Allowed links:** \`${P}automod whitelist add <domain>\`.`,
        "",
        `**Manual warning:** \`${P}warn @user <reason>\` — climbs the same ladder as the automod. \`${P}warn lista @user\` · \`${P}warn limpar @user\`.`,
        `**Who can moderate:** \`${P}acesso cargo add <@role>\` gives moderation power to a role without touching Stoat's permissions.`,
        `**Where commands work:** \`${P}acesso canal somente\` + \`${P}acesso canal add\` limits **every** command of non-staff to the chosen channels (the RPG included — that's where you pick where it's played).`,
      ],
    },

    logs: {
      titulo: "📋 Logging",
      ordem: 2,
      resumo: "Where the bot writes down what happened.",
      corpo: [
        "Create a channel (e.g. **#log**) visible only to the team. Then, **inside it**:",
        "",
        `\`${P}log channel here\` — sets this channel as the log channel`,
        `\`${P}log\` — shows what's being logged`,
        `\`${P}log <punicoes|membros|mensagens|cargos|comandos> on|off\``,
        "",
        "Logging punishments and joins/leaves is worth it; `comandos` is noisy and starts disabled.",
        "",
        ...(comIA ? ["💡 The log channel is where Judy pings you when AI moderation deletes something."] : []),
      ],
    },

    cargos: {
      titulo: "🎭 Roles",
      ordem: 3,
      resumo: "Role on join and reaction roles.",
      corpo: [
        `**Automatic role on join:** \`${P}autorole set @Role\``,
        "The role can be mentioned, named or given by ID (Settings → Roles → *Copy role ID*).",
        "",
        `**Reaction roles** (react and get the role):`,
        `1. Post the message: \`${P}embed titulo: Pick your roles | descricao: 🎮 Games · 📢 News\``,
        `2. Wire emoji → role: \`${P}reactionrole add <message> 🎮 <role-id>\``,
        "   The **message** can be the ID **or the link** (`...` menu → *Copy link*).",
        `3. Check it with \`${P}reactionrole list\``,
        `4. If only one option can apply (color, team, age): \`${P}reactionrole exclusivo <message> on\``,
        "   Then picking one emoji **swaps** the previous role instead of stacking.",
        "",
        `**Silencing** (\`${P}silenciar\`): Stoat's native timeout — no role needed, the bot needs **TimeoutMembers**`,
        "",
        `**Role colors:** \`${P}cor <role> <color>\``,
        `Takes hex, names, and even **gradients** — which the Stoat client doesn't offer:`,
        `\`${P}cor VIP gradiente #FF71CE #01CDFE #05FFA1\``,
        `\`${P}cor VIP preset vaporwave\` · \`${P}cor presets\` lists the ready-made ones`,
        `\`${P}cor painel aqui\` — **does everything**: creates the colored roles, posts the picker message, reacts and wires the reaction roles`,
        "",
        `**Greeting new members:** \`${P}welcome channel here\``,
        `Then write it your way: \`${P}welcome text Hi {usuario}, welcome to {servidor}!\``,
        `\`${P}welcome test\` posts it using you as the example. \`${P}goodbye\` does the same for people leaving.`,
        "",
        `**Timezones:** \`${P}fuso add São Paulo\` · \`${P}fuso add Madrid\``,
        `Then just \`${P}fuso\` to see both times at once.`,
        "",
        `**Who's on the team:** \`${P}staff\``,
        `It reads the roles from \`${P}acesso cargo\`, so \`${P}staff add <@role>\` also grants the moderation commands.`,
      ],
    },

    xp: {
      titulo: "🎮 XP and levels",
      ordem: 4,
      resumo: "People earn XP by chatting and level up.",
      corpo: [
        `**Enable:** \`${P}xp on\``,
        `**Create the level roles:** \`${P}xp criarcargos\` (one every 10 levels)`,
        `**Adjust:** \`${P}xp setup\` shows everything you can change:`,
        `• \`${P}xp setup intervalo <5|10>\` — how many levels between roles`,
        `• \`${P}xp setup xp <min> <max>\` — how much a message earns`,
        `• \`${P}xp setup cooldown <seconds>\` — prevents spam farming`,
        `• \`${P}xp setup canal aqui|off\` — where to announce level ups`,
        "",
        `**See the ranking:** \`${P}xp top\` · **your profile:** \`${P}nivel\``,
      ],
    },

    ia: {
      titulo: "🤖 Judy (the AI)",
      ordem: 5,
      soComIA: true,
      resumo: "Chat, memory, participation and AI moderation.",
      corpo: [
        `**Test it:** \`${P}chat status\` shows whether the AI service is up.`,
        "Then just mention the bot or use `&chat <message>`.",
        "She can also **see images**: attach one and ask (\"what's in this?\").",
        "",
        `**Let her join on her own:** \`${P}chat livre on\` (in this channel)`,
        `• \`${P}chat livre modo relevante\` — only when the topic is worth it`,
        `• \`${P}chat livre modo todas\` — replies to everything`,
        "",
        `**Comments on her own initiative:** \`${P}chat comentar aqui\` · \`${P}chat comentar pordia <n>\``,
        "",
        `**Profile and memory:** \`${P}chat perfil\` shows what she knows about you.`,
        `\`${P}chat cuidado @user on\` — treats someone with extra kindness.`,
        `\`${P}chat esquecer\` erases yours; \`${P}chat esquecer tudo\` wipes the server's.`,
        "",
        `**AI moderation:** \`${P}modia criterios <what to moderate, in free text>\` then \`${P}modia on\`.`,
        "She deletes whatever violates them and pings the owner in the log — she never bans on her own.",
      ],
    },

    noticias: {
      titulo: "📰 News (RSS)",
      ordem: 6,
      resumo: "The bot posts the feeds' updates every hour.",
      corpo: [
        "Create a channel (e.g. **#news**) and, **inside it**:",
        "",
        `\`${P}rss canal aqui\` — sets where to publish`,
        `\`${P}rss add <feed-url>\` — e.g.: \`${P}rss add https://g1.globo.com/rss/g1/\``,
        `\`${P}rss list\` — registered feeds`,
        `\`${P}rss agora\` — forces a cycle to test`,
        "",
        "Every hour the bot posts the new items." + (comIA ? " Judy also writes an overall summary in her own voice." : ""),
      ],
    },

    mensagens: {
      titulo: "✉️ Pretty messages",
      ordem: 7,
      resumo: "Publishing announcements and rules with embed styling.",
      corpo: [
        `\`${P}embed\` on its own shows the help. The format is \`field: value\`, one per line:`,
        "```",
        `${P}embed`,
        "titulo: Rules",
        "descricao: Be kind to everyone.",
        "cor: #5865F2",
        "```",
        "",
        `Or everything on one line: \`${P}embed titulo: Rules | descricao: Be kind | cor: azul\``,
        "",
        "**Fields:** `titulo` `descricao` `cor` `rodape` `imagem` `canal`.",
      ],
    },

    economia: {
      titulo: "💰 The server's economy",
      ordem: 7.5,
      resumo: "A currency of this server's own: mining, ranking and a role shop.",
      corpo: [
        "_Separate from the RPG: each server has **one** currency of its own._",
        "",
        "**For everyone**",
        `\`${P}economia minerar\` — earn a handful, then wait (1 h by default)`,
        `\`${P}economia saldo\` · \`${P}economia top\` — who has the most`,
        `\`${P}economia loja\` · \`${P}economia comprar <role>\` — roles for sale`,
        `\`${P}economia pagar @user <amount>\``,
        "",
        "**Setting it up** _(ManageServer)_",
        `\`${P}economia config nome Petal\` · \`config simbolo 🌸\``,
        `\`${P}economia config ganho 10 30\` · \`config intervalo 1h\` — how much and how often`,
        `\`${P}economia loja add VIP 500\` — puts a role up for sale`,
        "",
        "_The bot only hands out roles **below its own** — and only charges if the role is delivered._",
      ],
    },




    rpg: {
      titulo: "🎲 RPG wiki",
      ordem: 9,
      resumo: "_(for players)_ how everything works: attributes, missions, spells, items, companions, currencies.",
      corpo: [
        "_One world: the same character on every server where Judy is. React ◀ ▶ to turn the pages._",
        "",
        "**🎭 Character and levels**",
        `\`${P}game criar [name]\` — creates · \`${P}game\` — your sheet · \`${P}game ficha @user\``,
        "Each level asks **50% more XP** than the previous one (level 2 asks 100).",
        "Every level gives **free points**; every **2 levels** all attributes go up by 1 on their own.",
        `\`${P}game pontos <attribute> [how many]\` — spends points (accepts \`str\`, \`dex\`, \`int\`, \`luk\`…)`,
        `\`${P}game resetar pontos\` — gives back every spent point to redistribute; costs Gold (grows with level)`,
        `\`${P}game top\` — ranking · \`${P}game apagar confirmar\` — start over`,
        `_\`${P}xp\` is something else: the server's message level._`,
        "",
        "**📊 The 9 attributes — what each one does**",
        "💪 **Strength** — the core of **power**: each point is worth 1. More power = better odds of completing a mission.",
        "🎯 **Dexterity** — **accuracy**: multiplies power, from 70% (none) up to nearly 100%. 10 points already give 85%.",
        "🧠 **Intelligence** — worth 0.7 in power; and, added to Luck, raises the **XP** of every mission and the **free points per level**.",
        "✨ **Charisma** — a little power (0.3 per point); a **spellbook discount** (up to 40%), better prices when you **sell to the market**, cheaper **mercenaries**.",
        "❤️ **Health** · 🛡️ **Resistance** · 💨 **Agility** — **survival**. Each point raises its own factor by 1/12, and the three **multiply**: 6/6/6 survives about 35% more than 18 points in one.",
        "🍀 **Luck** — adds 0.6 per point to survival; improves **loot rarity** and each mission's **coins**; and, with Intelligence, XP and points per level.",
        "🔷 **Mana** — how much **magic** stays active: each spell costs 1 to 8 mana, and they kick in from strongest to weakest while the mana lasts.",
        "",
        "**Numbers that help with a build**",
        "Points per level = 1 + ¼ × √(Intelligence + Luck) — with 16 combined, 2 points per level.",
        "Extra XP = 2% × √(Intelligence + Luck) — with 16 combined, +8%.",
        "Everything has diminishing returns: no attribute becomes the only choice.",
        "",
        "**⚔️ Missions**",
        `\`${P}game missao\` — the list, with YOUR odds on each · \`${P}game missao <name>\` — go`,
        "🏪 **Market**: no risk, little XP — the early safety net.",
        "🟢 Easy · 🟡 Medium · 🔴 Hard — real risk, real XP and loot; each mission level pays 50% more XP.",
        "**Odds of success** = your power ÷ (your power + required). **Odds of surviving** = your survival ÷ (it + the risk).",
        "**Level margin:** each level you have above the mission closes 1/6 of what's missing to 100% — with a **6-level margin**, the mission is guaranteed.",
        "Three outcomes:",
        "✅ **Success** — full XP, coins and a loot chance",
        "❌ **Failure** — 30% of the XP, no coins",
        "💀 **Fall** — 15% of the XP, ~30 min recovering, part of the Gold you carry goes to the dungeon, and companions may be captured. **Levels and gear are never lost.**",
        "",
        "**🤝 Dungeon co-op**",
        `\`${P}game coop abrir <mission>\` — opens a call in the channel · \`${P}game coop entrar\` · \`${P}game coop sair\``,
        `Up to **4 people**, each with the companions they bring. It leaves by itself when full, or when whoever opened it says \`${P}game coop partir\`; it expires in 10 min.`,
        "**One outcome for the group**: everyone's attributes add up (each extra member weighs 18% on the requirement, like in a party).",
        "The consequences are each one's: **full XP** (+10% per partner), **split coins**, their own loot, and — if the group falls — each recovers and risks their own companions.",
        "Dungeon missions only; whoever is recovering or in the mission's cooldown can't join.",
        "",
        "**✨ Spells**",
        `\`${P}game magias\` — the spellbook · \`${P}game aprender <name>\``,
        "🔥 **Attack** adds to power: Spark +15% · Fire Arrow +28% · Ice Lance +42% · Storm +62% · Final Judgment +85%.",
        "🛡️ **Support** adds to survival: Lesser Shield +18% · Heal +30% · Arcane Barrier +45% · Regeneration +65% · Divine Intervention +88%.",
        "Each has a minimum level (1, 3, 6, 12, 20) and a mana cost (1, 2, 3, 5, 8). Charisma lowers the price.",
        "",
        "**🎒 Items**",
        `\`${P}game itens\` · \`${P}game equipar <item>\` · \`${P}game catalogo [rarity|slot]\` · \`${P}game item <name>\``,
        "6 slots: ⚔️ weapon · 🪖 head · 🛡️ body · 💍 accessory ×3. Each item's bonus adds straight to the attributes.",
        "Rarities: Common · Uncommon · Rare · Epic · Legendary. **Commons never run out** (♾️); the others have stock.",
        "Loot comes from missions: harder missions and more **Luck** pull better rarities.",
        "",
        "**👥 Companions**",
        `\`${P}game recrutas\` · \`${P}game contratar [name]\` · \`${P}game followers\` · \`${P}game follower levar <name>\` (up to 2)`,
        `\`${P}game follower ficha <name>\` · \`${P}game follower dar <name> <item>\` (they carry up to 2 items)`,
        "⚔️ Fighter (strength, health) · 🛡️ Tank (resistance, health) · 🔮 Mage (intelligence, mana) · ✨ Support (luck, charisma) — each with a spell.",
        "Each one in the party **raises the mission's requirement by 18%** and **splits the coins** — they're worth it for variety of classes and spells, not raw strength.",
        `They spend ⚡energy per mission (1 back per hour; \`${P}game descansar\` restores it for coins).`,
        "",
        "**💰 Currencies and market**",
        "🪙 **Gold** — infinite: everyday money. 💎 **Crystal** — finite: 5,000 exist forever; drops 40× less and is worth ~40 Gold.",
        `\`${P}game carteira\` — balance and currency state · \`${P}game comprar [item]\` · \`${P}game vender <item>\``,
        "Everything revolves around **P** (how much of the currency players hold): **high P** → cheap items, but falling costs a lot; **low P** → the opposite.",
        "The market pays **below** the price when buying from you — buying and reselling always loses money.",
        `\`${P}game cambio 1 cristal\` — what it's worth · \`${P}game cambio 200 ouro para cristal\` — exchange with the bank (3% fee) · \`${P}game cambio tudo ouro para cristal\` — all of it`,
        "Currencies are **whole**: the bank hands out whole units and uses only what they cost; the rest stays with you.",
        `\`${P}game cambio 100 ouro por 2 cristal\` — offer to another player · \`${P}game mercado\` — player bazaar`,
        `\`${P}game trocar @user <your item> por <their item>\` — barter. Everything in **escrow**: nobody lists what they don't have, and nobody gets scammed.`,
        "",
        "**🕳️ Dungeon**",
        "Gold lost in falls goes to the **dungeon pot**. Whoever **wins** a dungeon mission takes a slice: 25% of the prize on Easy, 60% on Medium, all of it on Hard — and the fuller the pot, the bigger the prize. In co-op, the slice is split across the group.",
        `Captured companions stay locked there — \`${P}game dungeon\` shows who. Rescue is automatic: every mission you come back from is an attempt (success = full chance, coming back without completing = half).`,
        "The owner has priority for the first 6 h; after that, anyone's mission can free them.",
      ],
    },


    aventura: {
      titulo: "⚔️ RPG — missions and companions",
      ordem: 10,
      resumo: "_(for the players)_ missions, items, party and dungeon.",
      corpo: [
        "**Missions**",
        `\`${P}game missao\` — list with your odds in each one`,
        `\`${P}game missao <name>\` — sets off`,
        "",
        "🏪 **Market** — no risk, no scaling: the safety net of the early game.",
        "🟢🟡🔴 **Dungeon** — three difficulties, real risk and real loot.",
        "Falling does **not** cost levels or gear — only time recovering.",
        "Recovery (~30 min) runs alongside the mission cooldown: the longer one counts.",
        "",
        "**Items**",
        `\`${P}game itens\` · \`${P}game equipar <item>\` · \`${P}game catalogo\``,
        `\`${P}game item <name>\` — price, stock and bonuses of one item`,
        `6 slots: ⚔️🪖🛡️ and 💍×3 — your sheet (\`${P}game\`) lists the empty ones too.`,
        "The commons (♾️) never run out — nobody goes without equipment.",
        "",
        "**Magic**",
        `\`${P}game magias\` — the grimoire · \`${P}game aprender <name>\``,
        "They cost **Mana** and enter from the strongest down, while it lasts.",
        "🔥 Attack raises success · ✨ Support raises survival.",
        "",
        "**Companions**",
        `\`${P}game followers\` · \`${P}game follower levar <name>\` (up to 2)`,
        `\`${P}game follower ficha <name>\` — attributes, spell, energy and bag`,
        `\`${P}game follower dar <name> <item>\` — up to 2, adding to their attributes`,
        "Both names can have spaces; if ambiguous, separate them with `|`.",
        "⚔️ Fighter · 🛡️ Tank · 🔮 Mage · ✨ Support — each with one spell.",
        "They spend ⚡energy per mission (1 comes back per hour).",
        "Bringing them **raises the difficulty** and **splits the loot**: they're",
        "worth the variety of classes and spells, not brute force.",
        "",
        "**Dungeon**",
        `If the party falls, they can be captured. \`${P}game dungeon\` shows who's held.`,
        "**The rescue is automatic:** every mission you come back from is an",
        "attempt. Completing it gives the full chance, coming back without",
        "completing gives half, falling gives none.",
        "The owner has priority for the first 6h; after that, anyone's mission frees them.",
      ],
    },



    ajustes: {
      titulo: "⚙️ General settings",
      ordem: 12,
      resumo: "Overview, disabled commands and the global list.",
      corpo: [
        `\`${P}config\` — overview of everything configured on this server`,
        `\`${P}comando disable|enable <name>\` — toggles a command here`,
        `\`${P}banglobal <off|avisar|banir>\` — what to do when someone banned elsewhere joins`,
        `\`${P}idioma pt|en\` — the language I reply in on this server`,
        `\`${P}debug\` — full diagnostics: what's broken, and how to fix it`,
        `\`${P}debug @user\` · \`${P}debug #channel\` — one person, one channel`,
        "",
        `And \`${P}help\` lists everything, with \`${P}help <command>\` for details.`,
      ],
    },
  };

  // ── pt ──
  return {
    permissoes: {
      titulo: "🔑 Permissões do bot",
      ordem: 0,
      resumo: "Antes de tudo: sem isso, nada funciona.",
      corpo: [
        "Em **Configurações do servidor → Cargos**, dê ao cargo do bot:",
        "",
        "**Essenciais**",
        "• `ViewChannel`, `ReadMessageHistory` — ver e ler os canais",
        "• `SendMessage`, `SendEmbeds` — responder",
        `• \`React\` — reações (cargos por reação${comIA ? ", 👀 da Judy" : ""})`,
        "",
        "**Para moderar**",
        "• `ManageMessages` — apagar mensagens (automod, `&limpar`)",
        "• `KickMembers`, `BanMembers` — `&kick`, `&ban`, ban global",
        "• `TimeoutMembers` — silenciar por tempo (`&silenciar`)",
        "",
        "**Para gerir cargos e canais**",
        "• `ManageRole` — **criar** cargos (cargos de nível)",
        "• `AssignRoles` — **dar** cargos a alguém (autorole, nível, reação)",
        "• `ManageChannel` — criar/editar canais",
        "",
        "⚠️ `ManageRole` e `AssignRoles` são coisas **diferentes**: uma cria o cargo, a outra entrega para a pessoa. Faltando a segunda, o bot cria os cargos e falha na hora de aplicar.",
        "",
        "💡 O cargo do bot precisa estar **acima** dos cargos que ele vai gerenciar na lista de cargos.",
      ],
    },

    canais: {
      titulo: "🔀 Canais: os 3 tipos",
      ordem: 0.5,
      resumo: "Permissão de canal vence permissão de cargo. Separe todo canal em um de 3 tipos.",
      corpo: [
        "**A regra que explica quase todo \"por que não funciona\":**",
        "uma permissão definida **no canal** passa por cima da **do cargo**. Se um cargo pode *Enviar mensagens* no servidor mas o canal nega, o cargo não envia. Então: deixe as permissões dos cargos no *mínimo* e abra exceções canal por canal.",
        "",
        "Coloque todo canal em um de **três tipos**:",
        "",
        "**🔒 Só staff vê** — logs, alertas do Sentinela, bastidores",
        "• Canal → *Permissões* → **Padrão**: negue *Ver canal*",
        "• depois, em cada **cargo de staff**: permita *Ver canal*",
        "",
        "**📢 Só staff escreve** — regras, avisos, painéis de reaction role",
        "• **Padrão**: negue *Enviar mensagens* (mantenha *Ver canal* permitido)",
        "• em cada **cargo de staff**: permita *Enviar mensagens*",
        "",
        "**💬 Geral** — conversa, off-topic, mídia",
        "• não mexa em nada; herda o padrão do servidor",
        "",
        "**E o bot?** Dê ao cargo dele *Ver canal* + *Enviar mensagens* também nos dois primeiros tipos, senão ele não consegue registrar log, alertar nem publicar painel. " + "`&debug` confere isso por você, canal a canal.",
        "",
        `💡 \`${P}assistente canais\` pergunta quais canais são de cada tipo e lista exatamente o que clicar.`,
      ],
    },

    moderacao: {
      titulo: "🛡️ Moderação automática",
      ordem: 1,
      resumo: "Os filtros que agem sozinhos e o que acontece com quem infringe.",
      corpo: [
        `**1. Veja o estado atual:** \`${P}automod\``,
        "Mostra os 4 grupos — antispam (enxurrada), antiruido (texto poluído), antilink (links e convites), sentinela (conteúdo nocivo) — e as partes de cada um.",
        "",
        `**2. Ligue/desligue o que quiser:** \`${P}automod <grupo> on|off\` · só uma parte: \`${P}automod <grupo> <parte> on|off\``,
        `**3. Aprofunde:** \`${P}automod blocklist\`, \`${P}automod sentinela\`, \`${P}automod punicao\` — a família toda mora sob \`${P}automod\`, e o \`${P}help automod\` desce por ela`,
        `Ex.: \`${P}automod antilink on\` · \`${P}automod antiruido caps off\``,
        "",
        `**4. Defina a punição:** \`${P}automod punicao modo <avisar|apagar|confirmar|acumular|banir>\``,
        "• `avisar` — só avisa (bom para testar)",
        "• `apagar` — remove a mensagem, não pune a pessoa",
        "• `confirmar` — apaga, silencia e chama um moderador",
        "• `acumular` — sobe uma escada de punições a cada reincidência",
        "• `banir` — bane na hora",
        "",
        `**5. Se usar \`acumular\`:** \`${P}automod punicao escada\``,
        "A escada padrão é **aviso → 5 min de silêncio → 1 h de silêncio → ban**.",
        "Quem para no primeiro degrau nunca chega ao último; quem insiste sobe sozinho.",
        "**Filtros de ruído** (repetição, caixa alta, emoji, velocidade): o 1º deslize em 10 min é só um toque, sem aviso — menos conta nova e durante raid.",
        `Os avisos zeram depois de **30 dias** sem um novo (\`${P}automod punicao validade <dias|0>\`).`,
        `Mude com \`${P}automod punicao escada aviso,10m,2h,ban\`. O mute é o timeout nativo do Stoat: o bot precisa de **TimeoutMembers**.`,
        `**6. Se usar \`confirmar\`:** a pessoa fica em timeout até a staff decidir (no máximo 24 h) — o bot precisa de **TimeoutMembers**.`,
        "",
        `**Sentinela** (\`${P}automod sentinela\`, antigo \`scam\`): o único módulo que **julga** em vez de medir —`,
        "ele dá uma nota de suspeita ao conteúdo. E porque julga, ele se adapta:",
        "• **mais rígido com quem chegou agora** — o limiar acompanha o nível de XP do membro, então",
        "  uma conta recém-criada é olhada de perto e quem conversa aqui há semanas ganha margem",
        "• **avisa a staff** diante de um *padrão* repetido, antes de punir qualquer coisa",
        `\`${P}automod sentinela on\` · \`${P}automod sentinela sensitivity <baixa|media|alta>\` · \`${P}automod sentinela antiguidade on|off\``,
        `**Links permitidos:** \`${P}automod whitelist add <domínio>\`.`,
        "",
        `**Aviso manual:** \`${P}warn @pessoa <motivo>\` — sobe a mesma escada do automod. \`${P}warn lista @pessoa\` · \`${P}warn limpar @pessoa\`.`,
        `**Quem pode moderar:** \`${P}acesso cargo add <@cargo>\` dá poder de moderação a um cargo, sem precisar mexer nas permissões do Stoat.`,
        `**Onde os comandos valem:** \`${P}acesso canal somente\` + \`${P}acesso canal add\` limita **todos** os comandos de quem não é staff aos canais escolhidos (o RPG inclusive — é assim que se escolhe onde ele é jogado).`,
      ],
    },

    logs: {
      titulo: "📋 Registro (logs)",
      ordem: 2,
      resumo: "Onde o bot anota o que aconteceu.",
      corpo: [
        "Crie um canal (ex.: **#log**) visível só para a equipe. Depois, **dentro dele**:",
        "",
        `\`${P}log canal aqui\` — define este canal como o de registro`,
        `\`${P}log\` — mostra o que está sendo registrado`,
        `\`${P}log <punicoes|membros|mensagens|cargos|comandos> on|off\``,
        "",
        "Vale registrar punições e entradas/saídas; `comandos` é ruidoso e começa desligado.",
        "",
        ...(comIA ? ["💡 É no canal de log que a Judy te marca quando a moderação por IA apaga algo."] : []),
      ],
    },

    cargos: {
      titulo: "🎭 Cargos",
      ordem: 3,
      resumo: "Cargo ao entrar e cargos por reação.",
      corpo: [
        `**Cargo automático para quem entra:** \`${P}autorole set @Cargo\``,
        "O cargo pode ser mencionado, pelo nome ou pelo ID (Configurações → Cargos → *Copy role ID*).",
        "",
        `**Cargos por reação** (a pessoa reage e ganha o cargo):`,
        `1. Publique a mensagem: \`${P}embed titulo: Escolha seus cargos | descricao: 🎮 Jogos · 📢 Avisos\``,
        `2. Ligue emoji → cargo: \`${P}reactionrole add <mensagem> 🎮 <id-do-cargo>\``,
        "   A **mensagem** pode ser o ID **ou o link** (menu `...` → *Copiar link*).",
        `3. Confira com \`${P}reactionrole list\``,
        `4. Se só uma opção pode valer (cor, time, idade): \`${P}reactionrole exclusivo <mensagem> on\``,
        "   Aí escolher um emoji **troca** o cargo anterior em vez de acumular.",
        "",
        `**Silêncio** (\`${P}silenciar\`): timeout nativo do Stoat — sem cargo; o bot precisa de **TimeoutMembers**`,
        "",
        `**Cor dos cargos:** \`${P}cor <cargo> <cor>\``,
        `Aceita hex, nome, e até **gradiente** — que o cliente do Stoat não oferece:`,
        `\`${P}cor VIP gradiente #FF71CE #01CDFE #05FFA1\``,
        `\`${P}cor VIP preset vaporwave\` · \`${P}cor presets\` lista os prontos`,
        `\`${P}cor painel aqui\` — **faz tudo**: cria os cargos coloridos, publica a mensagem de escolha, reage e liga os cargos por reação`,
        "",
        `**Receber quem chega:** \`${P}boasvindas canal aqui\``,
        `Depois escreva do seu jeito: \`${P}boasvindas texto Olá {usuario}, boas-vindas a {servidor}!\``,
        `\`${P}boasvindas testar\` publica usando você de exemplo. O \`${P}adeus\` faz o mesmo para quem sai.`,
        "",
        `**Fusos horários:** \`${P}fuso add São Paulo\` · \`${P}fuso add Madrid\``,
        `Depois é só \`${P}fuso\` para ver a hora nas duas ao mesmo tempo.`,
        "",
        `**Quem é da equipe:** \`${P}staff\``,
        `Ele lê os cargos do \`${P}acesso cargo\`, então \`${P}staff add <@cargo>\` também dá acesso aos comandos de moderação.`,
      ],
    },

    xp: {
      titulo: "🎮 XP e níveis",
      ordem: 4,
      resumo: "As pessoas ganham XP conversando e sobem de nível.",
      corpo: [
        `**Ligar:** \`${P}xp on\``,
        `**Criar os cargos de nível:** \`${P}xp criarcargos\` (um a cada 10 níveis)`,
        `**Ajustar:** \`${P}xp setup\` mostra tudo que dá para mudar:`,
        `• \`${P}xp setup intervalo <5|10>\` — de quantos em quantos níveis dar cargo`,
        `• \`${P}xp setup xp <min> <max>\` — quanto ganha por mensagem`,
        `• \`${P}xp setup cooldown <segundos>\` — evita farm por spam`,
        `• \`${P}xp setup canal aqui|off\` — onde anunciar o level up`,
        "",
        `**Ver o ranking:** \`${P}xp top\` · **seu perfil:** \`${P}nivel\``,
      ],
    },

    ia: {
      titulo: "🤖 A Judy (IA)",
      ordem: 5,
      soComIA: true,
      resumo: "Conversa, memória, participação e moderação por IA.",
      corpo: [
        `**Testar:** \`${P}chat status\` mostra se o serviço de IA está no ar.`,
        "Depois é só mencionar o bot ou usar `&chat <mensagem>`.",
        "Ela também **vê imagens**: anexa uma e pergunta (\"o que aparece aqui?\").",
        "",
        `**Deixar ela participar sozinha:** \`${P}chat livre on\` (neste canal)`,
        `• \`${P}chat livre modo relevante\` — só quando o assunto vale`,
        `• \`${P}chat livre modo todas\` — responde tudo`,
        "",
        `**Comentários por iniciativa:** \`${P}chat comentar aqui\` · \`${P}chat comentar pordia <n>\``,
        "",
        `**Perfil e memória:** \`${P}chat perfil\` mostra o que ela sabe de você.`,
        `\`${P}chat cuidado @pessoa on\` — trata alguém com gentileza extra.`,
        `\`${P}chat esquecer\` apaga o seu; \`${P}chat esquecer tudo\` zera o servidor.`,
        "",
        `**Moderação por IA:** \`${P}modia criterios <o que moderar, em texto livre>\` e depois \`${P}modia on\`.`,
        "Ela apaga o que violar e marca o dono no log — nunca bane sozinha.",
      ],
    },

    noticias: {
      titulo: "📰 Notícias (RSS)",
      ordem: 6,
      resumo: "O bot posta as novidades dos feeds a cada hora.",
      corpo: [
        "Crie um canal (ex.: **#noticias**) e, **dentro dele**:",
        "",
        `\`${P}rss canal aqui\` — define onde publicar`,
        `\`${P}rss add <url-do-feed>\` — ex.: \`${P}rss add https://g1.globo.com/rss/g1/\``,
        `\`${P}rss list\` — feeds cadastrados`,
        `\`${P}rss agora\` — força um ciclo para testar`,
        "",
        "A cada hora o bot posta os itens novos." + (comIA ? " A Judy escreve também um resumo geral no tom dela." : ""),
      ],
    },

    mensagens: {
      titulo: "✉️ Mensagens bonitas",
      ordem: 7,
      resumo: "Publicar avisos e regras com visual de embed.",
      corpo: [
        `\`${P}embed\` sozinho mostra a ajuda. O formato é \`campo: valor\`, um por linha:`,
        "```",
        `${P}embed`,
        "titulo: Regras",
        "descricao: Seja legal com todos.",
        "cor: #5865F2",
        "```",
        "",
        `Ou tudo numa linha: \`${P}embed titulo: Regras | descricao: Seja legal | cor: azul\``,
        "",
        "**Campos:** `titulo` `descricao` `cor` `rodape` `imagem` `canal`.",
      ],
    },

    economia: {
      titulo: "💰 A economia do servidor",
      ordem: 7.5,
      resumo: "Uma moeda só deste servidor: mineração, ranking e loja de cargos.",
      corpo: [
        "_À parte do RPG: cada servidor tem **uma** moeda própria._",
        "",
        "**Para todo mundo**",
        `\`${P}economia minerar\` — ganha um punhado e espera (1 h por padrão)`,
        `\`${P}economia saldo\` · \`${P}economia top\` — quem tem mais`,
        `\`${P}economia loja\` · \`${P}economia comprar <cargo>\` — cargos à venda`,
        `\`${P}economia pagar @pessoa <quantia>\``,
        "",
        "**Montar** _(ManageServer)_",
        `\`${P}economia config nome Pétala\` · \`config simbolo 🌸\``,
        `\`${P}economia config ganho 10 30\` · \`config intervalo 1h\` — quanto e de quanto em quanto tempo`,
        `\`${P}economia loja add VIP 500\` — põe um cargo à venda`,
        "",
        "_O bot só entrega cargos **abaixo do dele** — e só cobra se o cargo for entregue._",
      ],
    },




    rpg: {
      titulo: "🎲 Wiki do RPG",
      ordem: 9,
      resumo: "_(para os jogadores)_ como tudo funciona: atributos, missões, magias, itens, companheiros, moedas.",
      corpo: [
        "_Um mundo só: o mesmo personagem em todo servidor onde a Judy está. Reaja ◀ ▶ para virar as páginas._",
        "",
        "**🎭 Personagem e níveis**",
        `\`${P}game criar [nome]\` — cria · \`${P}game\` — sua ficha · \`${P}game ficha @pessoa\``,
        "Cada nível pede **50% mais XP** que o anterior (o 2º pede 100).",
        "A cada nível você ganha **pontos livres**; a cada **2 níveis** todos os atributos sobem 1 sozinhos.",
        `\`${P}game pontos <atributo> [quantos]\` — gasta os pontos (aceita \`for\`, \`des\`, \`int\`, \`sor\`…)`,
        `\`${P}game resetar pontos\` — devolve todos os pontos gastos para redistribuir; custa Ouro (cresce com o nível)`,
        `\`${P}game top\` — ranking · \`${P}game apagar confirmar\` — recomeça do zero`,
        `_O \`${P}xp\` é outra coisa: o nível por mensagens do servidor._`,
        "",
        "**📊 Os 9 atributos — o que cada um faz**",
        "💪 **Força** — o principal do **poder**: cada ponto vale 1. Mais poder = mais chance de cumprir a missão.",
        "🎯 **Destreza** — a **precisão**: multiplica o poder, de 70% (sem nenhuma) até perto de 100%. Com 10 pontos já está em 85%.",
        "🧠 **Inteligência** — vale 0,7 no poder; e, somada à Sorte, aumenta o **XP** de cada missão e os **pontos livres por nível**.",
        "✨ **Carisma** — um pouco de poder (0,3 por ponto); **desconto no grimório** (até 40%), paga melhor quando você **vende ao mercado** e barateia **mercenários**.",
        "❤️ **Vida** · 🛡️ **Resistência** · 💨 **Agilidade** — a **sobrevivência**. Cada ponto aumenta o próprio fator em 1/12, e os três **se multiplicam**: 6/6/6 sobrevive uns 35% mais que 18 pontos numa só.",
        "🍀 **Sorte** — soma 0,6 por ponto na sobrevivência; melhora a **raridade do loot** e as **moedas** de cada missão; e, com a Inteligência, o XP e os pontos por nível.",
        "🔷 **Mana** — quanta **magia** fica ativa: cada magia custa de 1 a 8 de mana, e elas entram da mais forte para a mais fraca enquanto a mana der.",
        "",
        "**Contas que ajudam a montar a build**",
        "Pontos por nível = 1 + ¼ × √(Inteligência + Sorte) — com 16 somados, 2 pontos por nível.",
        "XP extra = 2% × √(Inteligência + Sorte) — com 16 somados, +8%.",
        "Tudo tem retorno decrescente: nenhum atributo vira a única escolha possível.",
        "",
        "**⚔️ Missões**",
        `\`${P}game missao\` — a lista, com a SUA chance em cada uma · \`${P}game missao <nome>\` — parte`,
        "🏪 **Mercado**: sem risco, pouco XP — a rede de segurança do começo.",
        "🟢 Fácil · 🟡 Médio · 🔴 Difícil — risco de verdade, XP e loot de verdade; cada nível de missão paga 50% mais XP.",
        "**Chance de cumprir** = seu poder ÷ (seu poder + o exigido). **Chance de sobreviver** = sua sobrevivência ÷ (ela + o risco).",
        "**Folga de nível:** cada nível seu acima do da missão fecha 1/6 do que falta para 100% — com **6 níveis de folga**, a missão é garantida.",
        "Três desfechos:",
        "✅ **Sucesso** — XP inteiro, moedas e chance de loot",
        "❌ **Falha** — 30% do XP, sem moedas",
        "💀 **Queda** — 15% do XP, ~30 min se recuperando, uma parte do Ouro que você carrega vai para a dungeon, e os companheiros podem ser capturados. **Nível e equipamento nunca se perdem.**",
        "",
        "**🤝 Co-op de dungeon**",
        `\`${P}game coop abrir <missão>\` — abre um chamado no canal · \`${P}game coop entrar\` · \`${P}game coop sair\``,
        `Até **4 pessoas**, cada uma com os companheiros que leva. Parte sozinho quando enche, ou quando quem abriu manda \`${P}game coop partir\`; expira em 10 min.`,
        "**Um desfecho para o grupo**: os atributos de todos somam (cada membro a mais pesa 18% na exigência, como na party).",
        "As consequências são de cada um: **XP inteiro** (+10% por parceiro), **moedas divididas**, o próprio loot, e — se o grupo cair — cada um se recupera e arrisca os seus companheiros.",
        "Só missões de dungeon; quem está se recuperando ou na espera da missão não entra.",
        "",
        "**✨ Magias**",
        `\`${P}game magias\` — o grimório · \`${P}game aprender <nome>\``,
        "🔥 **Ataque** soma ao poder: Faísca +15% · Flecha Ígnea +28% · Lança de Gelo +42% · Tempestade +62% · Juízo Final +85%.",
        "🛡️ **Suporte** soma à sobrevivência: Escudo Menor +18% · Cura +30% · Barreira Arcana +45% · Regeneração +65% · Intervenção Divina +88%.",
        "Cada uma tem nível mínimo (1, 3, 6, 12, 20) e custa mana (1, 2, 3, 5, 8). O Carisma baixa o preço.",
        "",
        "**🎒 Itens**",
        `\`${P}game itens\` · \`${P}game equipar <item>\` · \`${P}game catalogo [raridade|slot]\` · \`${P}game item <nome>\``,
        "6 slots: ⚔️ arma · 🪖 cabeça · 🛡️ corpo · 💍 acessório ×3. O bônus de cada item soma direto nos atributos.",
        "Raridades: Comum · Incomum · Raro · Épico · Lendário. Os **comuns nunca acabam** (♾️); os outros têm estoque.",
        "O loot sai das missões: dificuldade maior e mais **Sorte** puxam raridades melhores.",
        "",
        "**👥 Companheiros**",
        `\`${P}game recrutas\` · \`${P}game contratar [nome]\` · \`${P}game followers\` · \`${P}game follower levar <nome>\` (até 2)`,
        `\`${P}game follower ficha <nome>\` · \`${P}game follower dar <nome> <item>\` (carregam até 2 itens)`,
        "⚔️ Combatente (força, vida) · 🛡️ Tank (resistência, vida) · 🔮 Mago (inteligência, mana) · ✨ Suporte (sorte, carisma) — cada um com uma magia.",
        "Cada um na party **aumenta a exigência da missão em 18%** e **divide as moedas** — valem pela variedade de classes e magias, não por força bruta.",
        `Gastam ⚡energia por missão (volta 1 por hora; \`${P}game descansar\` recupera por moeda).`,
        "",
        "**💰 Moedas e mercado**",
        "🪙 **Ouro** — infinita: o dinheiro do dia a dia. 💎 **Cristal** — finita: existem 5.000 para sempre; cai 40× menos e vale ~40 Ouro.",
        `\`${P}game carteira\` — saldo e o estado das moedas · \`${P}game comprar [item]\` · \`${P}game vender <item>\``,
        "Tudo gira em torno do **P** (quanto da moeda está com os jogadores): **P alto** → itens baratos, mas cair custa caro; **P baixo** → o contrário.",
        "O mercado paga **abaixo** do preço ao comprar de você — comprar e revender sempre dá prejuízo.",
        `\`${P}game cambio 1 cristal\` — quanto vale · \`${P}game cambio 200 ouro para cristal\` — troca com o banco (3% de taxa) · \`${P}game cambio tudo ouro para cristal\` — tudo`,
        "As moedas são **inteiras**: o banco entrega unidades inteiras e usa só o que elas custam; o resto fica com você.",
        `\`${P}game cambio 100 ouro por 2 cristal\` — oferta a outro jogador · \`${P}game mercado\` — bazar entre jogadores`,
        `\`${P}game trocar @pessoa <seu item> por <item dela>\` — escambo. Tudo em **custódia**: ninguém anuncia o que não tem, e não existe calote.`,
        "",
        "**🕳️ Dungeon**",
        "O Ouro perdido nas quedas vai para o **pote da dungeon**. Quem **vence** uma missão de dungeon leva uma fatia: 25% do prêmio no Fácil, 60% no Médio, tudo no Difícil — e quanto mais cheio o pote, maior o prêmio. No co-op, a fatia se divide pelo grupo.",
        `Companheiros capturados ficam presos lá — \`${P}game dungeon\` mostra quem. O resgate é automático: cada missão de que você volta é uma tentativa (cumprir = chance cheia, voltar sem cumprir = metade).`,
        "O dono tem prioridade nas primeiras 6 h; depois, a missão de qualquer um solta.",
      ],
    },


    aventura: {
      titulo: "⚔️ RPG — missões e companheiros",
      ordem: 10,
      resumo: "_(para os jogadores)_ missões, itens, party e dungeon.",
      corpo: [
        "**Missões**",
        `\`${P}game missao\` — lista com sua chance em cada uma`,
        `\`${P}game missao <nome>\` — parte`,
        "",
        "🏪 **Mercado** — sem risco e sem escala: rede de segurança do começo.",
        "🟢🟡🔴 **Dungeon** — três dificuldades, risco real e loot de verdade.",
        "Cair **não** custa nível nem equipamento — só tempo se recuperando.",
        "A recuperação (~30 min) corre junto com o cooldown da missão: vale a maior.",
        "",
        "**Itens**",
        `\`${P}game itens\` · \`${P}game equipar <item>\` · \`${P}game catalogo\``,
        `\`${P}game item <nome>\` — preço, estoque e bônus de um item`,
        `6 slots: ⚔️🪖🛡️ e 💍×3 — sua ficha (\`${P}game\`) lista os vazios também.`,
        "Os comuns (♾️) nunca acabam — ninguém fica sem equipamento.",
        "",
        "**Magia**",
        `\`${P}game magias\` — o grimório · \`${P}game aprender <nome>\``,
        "Custam **Mana** e entram da mais forte para a mais fraca, enquanto ela durar.",
        "🔥 Ataque sobe o êxito · ✨ Suporte sobe a sobrevivência.",
        "",
        "**Companheiros**",
        `\`${P}game followers\` · \`${P}game follower levar <nome>\` (até 2)`,
        `\`${P}game follower ficha <nome>\` — atributos, magia, energia e mochila`,
        `\`${P}game follower dar <nome> <item>\` — carrega até 2, que somam nos atributos dele`,
        "Os dois nomes podem ter espaço; se ficar ambíguo, separe com `|`.",
        "⚔️ Combatente · 🛡️ Tank · 🔮 Mago · ✨ Suporte — cada um com uma magia.",
        "Gastam ⚡energia por missão (volta 1 por hora).",
        "Levá-los **aumenta a dificuldade** e **divide o loot**: valem pela",
        "variedade de classes e magias, não por força bruta.",
        "",
        "**Dungeon**",
        `Se a party cair, eles podem ser capturados. \`${P}game dungeon\` mostra quem está preso.`,
        "**O resgate é automático:** toda missão de que você volta é uma tentativa.",
        "Cumprir dá a chance cheia, voltar sem cumprir dá metade, cair não dá nenhuma.",
        "O dono tem prioridade nas primeiras 6h; depois, a missão de qualquer um solta.",
      ],
    },



    ajustes: {
      titulo: "⚙️ Ajustes gerais",
      ordem: 12,
      resumo: "Panorama, comandos desativados e lista global.",
      corpo: [
        `\`${P}config\` — panorama de tudo que está configurado neste servidor`,
        `\`${P}comando desativar|ativar <nome>\` — liga/desliga um comando aqui`,
        `\`${P}banglobal <off|avisar|banir>\` — o que fazer quando entra alguém banido em outro servidor`,
        `\`${P}idioma pt|en\` — em que idioma eu respondo neste servidor`,
        `\`${P}debug\` — diagnóstico completo: o que está quebrado e como resolver`,
        `\`${P}debug @pessoa\` · \`${P}debug #canal\` — uma pessoa, um canal`,
        "",
        `E \`${P}help\` lista tudo, com \`${P}help <comando>\` para detalhes.`,
      ],
    },
  };
}

const APELIDOS = {
  canal: "canais", channels: "canais", channel: "canais", tipos: "canais", types: "canais",
  permissao: "permissoes", permissões: "permissoes", perms: "permissoes", bot: "permissoes",
  permissions: "permissoes",
  automod: "moderacao", moderação: "moderacao", punicao: "moderacao", punição: "moderacao", filtros: "moderacao",
  moderation: "moderacao", filters: "moderacao",
  log: "logs", registro: "logs", logging: "logs",
  cargo: "cargos", autorole: "cargos", reactionrole: "cargos", roles: "cargos",
  nivel: "xp", niveis: "xp", "níveis": "xp", level: "xp", levels: "xp",
  personagem: "rpg", jogo: "rpg", ficha: "rpg", character: "rpg",
  missao: "aventura", missoes: "aventura", itens: "aventura",
  missions: "aventura", adventure: "aventura", items: "aventura",
  // o mercado e as moedas do RPG estão DENTRO do rpg; "economia" é a moeda do SERVIDOR (&economia)
  // (4 out 2026) "&tutorial game" é o jeito natural de pedir a wiki do jogo
  game: "rpg", jogo: "rpg", wiki: "rpg", personagem: "rpg", atributos: "rpg", character: "rpg", attributes: "rpg",
  coop: "rpg", "co-op": "rpg", magias: "rpg", spells: "rpg", itens: "rpg", items: "rpg", dungeon: "rpg",
  missao: "aventura", "missão": "aventura", missoes: "aventura", "missões": "aventura", missions: "aventura", followers: "aventura", companheiros: "aventura",
  mercado: "rpg", market: "rpg", carteira: "rpg", wallet: "rpg", cambio: "rpg", "câmbio": "rpg", moeda: "rpg",
  economy: "economia", minerar: "economia", mine: "economia",
  followers: "aventura", party: "aventura", dungeon: "aventura",
  judy: "ia", chat: "ia", modia: "ia", ai: "ia",
  rss: "noticias", feed: "noticias", "notícias": "noticias", news: "noticias",
  embed: "mensagens", avisos: "mensagens", messages: "mensagens", embeds: "mensagens",
  config: "ajustes", geral: "ajustes", settings: "ajustes", general: "ajustes",
};

function GUIA(P, lang = "pt", comIA = false) {
  if (lang === "en") return [
    { title: "📚 Getting started — Before anything",
      description: [
        "This guide has **6 pages**: react ◀ ▶ to turn, or type `&tutorial <number>`.",
        `🧙 **Fastest way:** \`${P}assistente\` — I ask and set it up for you (\`${P}assistente rapido\` is 5 questions). This guide is for those who'd rather see each step.`,
        "",
        "**First: the bot's permissions** (Server settings → Roles → the bot's role)",
        "• `ViewChannel`, `ReadMessageHistory`, `SendMessage`, `SendEmbeds`, `React` — the basics",
        "• `ManageMessages`, `KickMembers`, `BanMembers`, `TimeoutMembers` — to moderate",
        "• `ManageRole` **and** `AssignRoles` — one creates roles, the other hands them out. The bot needs **both**",
        "",
        "⚠️ The bot's role must sit **above** every role it will manage in the role list.",
        "",
        `Check it: \`${P}debug\` says what's missing · Deep dive: \`${P}tutorial permissoes\``,
      ].join("\n") },

    { title: "🔀 Getting started — Channels (the golden rule)",
      description: [
        "**A channel's permissions beat a role's.** If the channel denies it, no role can save it. Keep role permissions minimal and open exceptions per channel.",
        "",
        "Sort **every** channel into one of 3 types:",
        "",
        "**🔒 Staff-only to see** (logs, alerts) — *Default*: deny **View channel** → each staff role: allow **View channel**",
        "**📢 Staff-only to write** (rules, announcements, panels) — *Default*: deny **Send messages** → each staff role: allow **Send messages**",
        "**💬 General** — change nothing",
        "",
        "The bot's role needs *View* + *Send* in the first two types as well.",
        "",
        `Who's staff for the bot: \`${P}acesso cargo add @Role\` (or \`${P}staff add\`).`,
        "",
        `Check it: \`${P}debug\` · Guided: \`${P}assistente canais\` · Deep dive: \`${P}tutorial canais\``,
      ].join("\n") },

    { title: "🛡️ Getting started — Protection",
      description: [
        `**See the filters:** \`${P}automod\` — spam, invites, links, caps, mass mentions, odd characters.`,
        `**Toggle:** \`${P}automod antispam on\` (and so on for each group: antiruido, antilink, sentinela)`,
        "",
        `**Sentinel** \`${P}automod sentinela on\` — the group that *judges* content: scams, NSFW, gore, hate speech and new accounts' images.`,
        `• \`${P}automod sentinela antiguidade on\` — stricter with newcomers`,
        `• \`${P}automod sentinela alerta on\` — pings the staff on a suspicious *pattern*`,
        "",
        `**Punishment:** \`${P}automod punicao modo acumular\` — warning → 5 min mute → 1 h mute → ban (change it with \`${P}automod punicao escada\`). Mutes use the native timeout (**TimeoutMembers**).`,
        "",
        `**Logging:** create a 🔒 staff-only channel and, inside it, \`${P}log canal aqui\`.`,
        `**Global list:** \`${P}banglobal avisar\` warns when someone banned elsewhere joins.`,
        "",
        `Guided: \`${P}assistente protecao\` · Deep dive: \`${P}tutorial moderacao\``,
      ].join("\n") },

    { title: "🎨 Getting started — Welcome and roles",
      description: [
        `**Welcome embed:** go to the channel and \`${P}boasvindas canal aqui\`. Then:`,
        `• \`${P}boasvindas texto Welcome, {usuario}! You're member #{membros}.\``,
        `• \`${P}boasvindas testar\` — see it now`,
        `Markers: \`{usuario}\` mention · \`{nome}\` name · \`{servidor}\` · \`{membros}\`. \`${P}help boasvindas\` explains every parameter.`,
        `**Goodbye:** same thing with \`${P}adeus\`.`,
        "",
        `**Role on join:** \`${P}autorole set @Member\``,
        "",
        "**Reaction roles:**",
        `1. \`${P}embed titulo: Pick your roles | descricao: 🎮 Games · 📢 News\``,
        `2. \`${P}reactionrole add <message link> 🎮 Games\``,
        `3. \`${P}reactionrole exclusivo <message link> on\` — if only one may apply`,
        `**Colors in one go:** \`${P}cor painel aqui\` builds a "pick your color" panel.`,
        "",
        `Deep dive: \`${P}tutorial cargos\` · \`${P}tutorial mensagens\``,
      ].join("\n") },

    { title: "🎮 Getting started — XP and RPG",
      description: [
        `**Levels by message:** \`${P}xp on\`, then \`${P}xp setup\` to choose roles per level, multiplier and the announcement channel. \`${P}xp criarcargos\` creates the roles.`,
        "",
        `**RPG (character, missions, market):** a separate system. \`${P}tutorial rpg\` is the players' wiki; players then use \`${P}game criar\`.`,
        "",
        ...(comIA ? [
          `**Judy (AI):** mention the bot or \`${P}chat <message>\`. \`${P}chat livre on\` lets her join a channel's conversation; \`${P}modia\` moderates with free-text criteria.`,
          "",
        ] : []),
        `**Clock:** \`${P}fuso add London\` · **News:** \`${P}rss add <url>\` · **Voice:** \`${P}entrar\` while in a call (from any channel) — she joins and reads the chat; \`${P}musica <link>\` plays music (auto-ducks under TTS) and \`${P}sair\` leaves`,
        `**Support:** \`${P}ticket painel #channel\` — people react to open a private channel with staff · **Integrations:** \`${P}webhook criar <name>\` brings GitHub/Crafty/etc into your channels`,
        "",
        `Deep dive: \`${P}tutorial xp\` · \`${P}tutorial rpg\``,
      ].join("\n") },

    { title: "✅ Getting started — Checklist",
      description: [
        "Before opening the doors, run through this:",
        "",
        `☐ \`${P}debug\` shows nothing to fix (🔴)`,
        `☐ \`${P}staff\` lists the right roles`,
        `☐ \`${P}log\` points at a 🔒 staff-only channel`,
        `☐ \`${P}automod status\` and \`${P}automod sentinela\` are the way you want`,
        `☐ \`${P}automod punicao\` — the mode makes sense and the bot has **TimeoutMembers**`,
        `☐ \`${P}boasvindas testar\` looks right`,
        `☐ \`${P}config\` — the overview matches what you expected`,
        "",
        `Anything off? \`${P}help <command>\` explains every parameter; \`${P}help diagnostico\` lists the usual suspects.`,
        "",
        `🎉 That's it. To redo any part with guidance: \`${P}assistente\`.`,
      ].join("\n") },
  ];

  return [
    { title: "📚 Por onde começar — Antes de tudo",
      description: [
        "Este guia tem **6 páginas**: reaja ◀ ▶ para virar, ou digite `&tutorial <número>`.",
        `🧙 **Jeito mais rápido:** \`${P}assistente\` — eu pergunto e configuro por você (o \`${P}assistente rapido\` são 5 perguntas). Este guia é para quem prefere ver cada passo.`,
        "",
        "**Primeiro: as permissões do bot** (Configurações do servidor → Cargos → cargo do bot)",
        "• `ViewChannel`, `ReadMessageHistory`, `SendMessage`, `SendEmbeds`, `React` — o básico",
        "• `ManageMessages`, `KickMembers`, `BanMembers`, `TimeoutMembers` — para moderar",
        "• `ManageRole` **e** `AssignRoles` — um cria cargos, o outro entrega. O bot precisa dos **dois**",
        "",
        "⚠️ O cargo do bot precisa estar **acima** de todo cargo que ele vai mexer, na lista de cargos.",
        "",
        `Conferir: \`${P}debug\` diz o que falta · Aprofundar: \`${P}tutorial permissoes\``,
      ].join("\n") },

    { title: "🔀 Por onde começar — Canais (a regra de ouro)",
      description: [
        "**A permissão do canal vence a do cargo.** Se o canal nega, nenhum cargo salva. Deixe os cargos no mínimo e abra exceções canal por canal.",
        "",
        "Separe **todo** canal em um de 3 tipos:",
        "",
        "**🔒 Só staff vê** (logs, alertas) — *Padrão*: negue **Ver canal** → em cada cargo de staff: permita **Ver canal**",
        "**📢 Só staff escreve** (regras, avisos, painéis) — *Padrão*: negue **Enviar mensagens** → em cada cargo de staff: permita **Enviar mensagens**",
        "**💬 Geral** — não mexa em nada",
        "",
        "O cargo do bot precisa de *Ver* + *Enviar* também nos dois primeiros tipos.",
        "",
        `Quem é staff para o bot: \`${P}acesso cargo add @Cargo\` (ou \`${P}staff add\`).`,
        "",
        `Conferir: \`${P}debug\` · Guiado: \`${P}assistente canais\` · Aprofundar: \`${P}tutorial canais\``,
      ].join("\n") },

    { title: "🛡️ Por onde começar — Proteção",
      description: [
        `**Veja os filtros:** \`${P}automod\` — spam, convites, links, caps, menções em massa, caracteres estranhos.`,
        `**Ligue:** \`${P}automod antispam on\` (e assim por diante para cada grupo: antiruido, antilink, sentinela)`,
        "",
        `**Sentinela** \`${P}automod sentinela on\` — o grupo que *julga* conteúdo: golpe, +18, gore, ódio e imagens de conta nova.`,
        `• \`${P}automod sentinela antiguidade on\` — mais rígido com quem acabou de chegar`,
        `• \`${P}automod sentinela alerta on\` — avisa a staff num *padrão* suspeito`,
        "",
        `**Punição:** \`${P}automod punicao modo acumular\` — aviso → mute 5 min → mute 1 h → ban (mude com \`${P}automod punicao escada\`). O mute usa o timeout nativo (**TimeoutMembers**).`,
        "",
        `**Registro:** crie um canal 🔒 só-staff-vê e, dentro dele, \`${P}log canal aqui\`.`,
        `**Lista global:** \`${P}banglobal avisar\` avisa quando entra alguém banido em outro servidor.`,
        "",
        `Guiado: \`${P}assistente protecao\` · Aprofundar: \`${P}tutorial moderacao\``,
      ].join("\n") },

    { title: "🎨 Por onde começar — Boas-vindas e cargos",
      description: [
        `**Embed de boas-vindas:** vá ao canal e \`${P}boasvindas canal aqui\`. Depois:`,
        `• \`${P}boasvindas texto Bem-vindo, {usuario}! Você é o membro nº {membros}.\``,
        `• \`${P}boasvindas testar\` — veja agora`,
        `Marcadores: \`{usuario}\` menção · \`{nome}\` nome · \`{servidor}\` · \`{membros}\`. \`${P}help boasvindas\` explica cada parâmetro.`,
        `**Despedida:** a mesma coisa com \`${P}adeus\`.`,
        "",
        `**Cargo a quem entra:** \`${P}autorole set @Membro\``,
        "",
        "**Cargos por reação:**",
        `1. \`${P}embed titulo: Escolha seus cargos | descricao: 🎮 Jogos · 📢 Avisos\``,
        `2. \`${P}reactionrole add <link da mensagem> 🎮 Jogos\``,
        `3. \`${P}reactionrole exclusivo <link da mensagem> on\` — se só pode valer um`,
        `**Cores de uma vez:** \`${P}cor painel aqui\` monta o painel "escolha sua cor".`,
        "",
        `Aprofundar: \`${P}tutorial cargos\` · \`${P}tutorial mensagens\``,
      ].join("\n") },

    { title: "🎮 Por onde começar — XP e RPG",
      description: [
        `**Níveis por mensagem:** \`${P}xp on\`, depois \`${P}xp setup\` para escolher cargos por nível, multiplicador e canal de anúncio. \`${P}xp criarcargos\` cria os cargos.`,
        "",
        `**RPG (personagem, missões, mercado):** um sistema à parte. \`${P}tutorial rpg\` é a wiki de quem joga; os jogadores então usam \`${P}game criar\`.`,
        "",
        ...(comIA ? [
          `**Judy (IA):** mencione o bot ou \`${P}chat <mensagem>\`. \`${P}chat livre on\` deixa ela entrar na conversa de um canal; \`${P}modia\` modera com critérios em texto livre.`,
          "",
        ] : []),
        `**Relógio:** \`${P}fuso add Lisboa\` · **Notícias:** \`${P}rss add <url>\` · **Voz:** \`${P}entrar\` estando numa call (de qualquer canal) — ela entra e lê o chat; \`${P}musica <link>\` toca música (abaixa sozinha quando o TTS fala) e \`${P}sair\` sai`,
        `**Suporte:** \`${P}ticket painel #canal\` — as pessoas reagem para abrir um canal privado com a staff · **Integrações:** \`${P}webhook criar <nome>\` traz GitHub/Crafty/etc para seus canais`,
        "",
        `Aprofundar: \`${P}tutorial xp\` · \`${P}tutorial rpg\``,
      ].join("\n") },

    { title: "✅ Por onde começar — Checklist",
      description: [
        "Antes de abrir as portas, passe por isto:",
        "",
        `☐ \`${P}debug\` não acusa nada a resolver (🔴)`,
        `☐ \`${P}staff\` lista os cargos certos`,
        `☐ \`${P}log\` aponta para um canal 🔒 só-staff-vê`,
        `☐ \`${P}automod status\` e \`${P}automod sentinela\` estão do jeito que você quer`,
        `☐ \`${P}automod punicao\` — o modo faz sentido e o bot tem **TimeoutMembers**`,
        `☐ \`${P}boasvindas testar\` ficou bonito`,
        `☐ \`${P}config\` — o panorama bate com o que você esperava`,
        "",
        `Algo estranho? \`${P}help <comando>\` explica cada parâmetro; \`${P}help diagnostico\` lista os culpados de sempre.`,
        "",
        `🎉 É isso. Para refazer qualquer parte com ajuda: \`${P}assistente\`.`,
      ].join("\n") },
  ];
}

export async function cmdTutorial(message, args, ctx) {
  const { sendEmbed, COR, PREFIXO: P } = ctx;
  const lang = lingua(ctx);

  const comIA = (() => { try { return temIA(ctx.serverId); } catch { return false; } })();

  // Membro vê o guia de quem joga e usa; a staff vê a configuração inteira
  // (ver visao.js). E ninguém vê IA/voz onde elas não estão liberadas.
  const visao = await visaoMod.quemVe(message, ctx);
  const membro = visao.nivel === "membro";
  const todas = AREAS(P, lang, comIA);
  const areas = {};
  for (const [k, v] of Object.entries(todas)) {
    if (v.soComIA && !comIA) continue;
    if (membro && !visaoMod.AREAS_DO_MEMBRO.has(k)) continue;
    areas[k] = { ...v, corpo: visaoMod.filtrarLinhas(v.corpo, visao) };
  }
  const pedido = args[0]?.toLowerCase();

  // O membro que pede uma área da staff (ou o guia de configuração em páginas)
  const chavePedida = pedido && !/^\d+$/.test(pedido) ? (todas[pedido] ? pedido : APELIDOS[pedido]) : null;
  if (membro && (!pedido || /^\d+$/.test(pedido) || (chavePedida && todas[chavePedida] && !areas[chavePedida]))) {
    const lista = Object.entries(areas).sort((a, b) => a[1].ordem - b[1].ordem)
      .map(([k, v]) => `\`${P}tutorial ${k}\` — ${v.titulo}${v.resumo ? `: ${v.resumo}` : ""}`);
    return sendEmbed(message.channel, {
      title: lang === "en" ? "📚 Tutorial" : "📚 Tutorial",
      description: [
        chavePedida && todas[chavePedida] && !areas[chavePedida]
          ? (lang === "en" ? `🔒 \`${P}tutorial ${pedido}\` is the staff's setup guide.\n` : `🔒 \`${P}tutorial ${pedido}\` é o guia de configuração da staff.\n`)
          : null,
        lang === "en" ? "What you can learn here:" : "O que dá para aprender por aqui:",
        "",
        ...lista,
        "",
        lang === "en" ? `_\`${P}help\` lists the commands you can use._` : `_\`${P}help\` lista os comandos que você pode usar._`,
      ].filter((x) => x !== null).join("\n"),
      colour: COR.info,
    });
  }

  // ── Página de uma área (aprofundamento) ──
  if (pedido && !/^\d+$/.test(pedido)) {
    const chave = areas[pedido] ? pedido : APELIDOS[pedido];
    const area = chave ? areas[chave] : null;
    if (!area) {
      const nomes = Object.keys(areas).map((k) => `\`${k}\``).join(" · ");
      return sendEmbed(message.channel, lang === "en" ? {
        title: "❓ Unknown area",
        description: `I don't know that area. The existing ones:\n${nomes}\n\nOr use \`${P}tutorial\` for the paged guide.`,
        colour: COR.aviso,
      } : {
        title: "❓ Área desconhecida",
        description: `Não conheço essa área. As que existem:\n${nomes}\n\nOu use \`${P}tutorial\` para o guia em páginas.`,
        colour: COR.aviso,
      });
    }
    const ordem = Object.entries(areas).sort((a, b) => a[1].ordem - b[1].ordem).map(([k]) => k);
    const i = ordem.indexOf(chave);
    const prox = ordem[i + 1];
    const rodape = prox
      ? (lang === "en"
        ? `➡️ Next area: \`${P}tutorial ${prox}\` (${areas[prox].titulo})`
        : `➡️ Próxima área: \`${P}tutorial ${prox}\` (${areas[prox].titulo})`)
      : (lang === "en"
        ? `✅ That's the last area. \`${P}config\` shows how everything turned out.`
        : `✅ Essa é a última área. \`${P}config\` mostra como tudo ficou.`);
    // Uma área longa vira duas páginas, em vez de ser cortada no meio.
    const paginas = paginarLinhas([...area.corpo, "", rodape], { titulo: area.titulo, limite: 1300 });
    return enviarPaginado(ctx, message.channel, {
      paginas, autorId: message.authorId, comandoPagina: null,
    });
  }

  // ── O guia em páginas (&tutorial, &tutorial <n>) ──
  const paginas = GUIA(P, lang, comIA).map((pg) => ({ ...pg, description: visaoMod.filtrarLinhas(String(pg.description ?? "").split("\n"), visao).join("\n"), colour: COR.info }));
  const n = pedido ? parseInt(pedido, 10) : 0;
  return enviarPaginado(ctx, message.channel, {
    paginas, autorId: message.authorId,
    paginaInicial: Math.min(Math.max(n - 1, 0), paginas.length - 1),
    comandoPagina: `${P}tutorial`,
  });
}
