import { servidorPermitido as temIA } from "../ai/chat.js";
import { lingua } from "../core/i18n.js";
// ══════════════════════════════════════════════════════════
//  tutorial.js — &tutorial
//
//  Guia de primeiros passos. Não configura nada: mostra o
//  CAMINHO — por quais áreas passar, em que ordem, e qual
//  comando usar em cada uma. Cada área tem sua própria página
//  com os comandos exatos e o que esperar.
//
//  `&tutorial`          → o roteiro (visão geral, em ordem)
//  `&tutorial <área>`   → detalhes daquela área
//  `&tutorial permissoes` → o que o BOT precisa para funcionar
//
//  BILÍNGUE: AREAS(P, lang) devolve o dicionário no idioma do
//  servidor. As CHAVES das áreas ficam em PT nos dois idiomas
//  (são "nomes de comando", como &tutorial moderacao).
// ══════════════════════════════════════════════════════════

// Cada área: título, quando fazer, e os passos concretos.
function AREAS(P, lang = "pt") {
  if (lang === "en") return {
    permissoes: {
      titulo: "🔑 Bot permissions",
      ordem: 0,
      resumo: "First of all: without these, nothing works.",
      corpo: [
        "In **Server settings → Roles**, give the bot's role:",
        "",
        "**Essentials**",
        "• `ViewChannel`, `ReadMessageHistory` — see and read the channels",
        "• `SendMessage`, `SendEmbeds` — reply",
        "• `React` — reactions (reaction roles, Judy's 👀)",
        "",
        "**To moderate**",
        "• `ManageMessages` — delete messages (automod, `&limpar`)",
        "• `KickMembers`, `BanMembers` — `&kick`, `&ban`, global bans",
        "• `TimeoutMembers` — timed silences",
        "",
        "**To manage roles and channels**",
        "• `ManageRole` — **create** roles (silence role, level roles)",
        "• `AssignRoles` — **give** roles to someone (autorole, levels, reactions)",
        "• `ManageChannel` — create/edit channels",
        "",
        "⚠️ `ManageRole` and `AssignRoles` are **different** things: one creates the role, the other hands it to the person. Missing the second, the bot creates the roles and then fails to apply them.",
        "",
        "💡 The bot's role must sit **above** the roles it will manage in the role list.",
      ],
    },

    moderacao: {
      titulo: "🛡️ Automatic moderation",
      ordem: 1,
      resumo: "The filters that act on their own and what happens to offenders.",
      corpo: [
        `**1. See the current state:** \`${P}automod\``,
        "Lists each filter (invites, spam, links, caps, mass mentions, weird characters) and whether it's on.",
        "",
        `**2. Toggle whatever you want:** \`${P}automod <filter> on|off\``,
        `E.g.: \`${P}automod antilink on\``,
        "",
        `**3. Set the punishment:** \`${P}punicao modo <avisar|apagar|confirmar|acumular|banir>\``,
        "• `avisar` — warn only (good for testing)",
        "• `apagar` — removes the message, doesn't punish the person",
        "• `confirmar` — deletes, silences and calls a moderator",
        "• `acumular` — issues warnings and bans at the limit",
        "• `banir` — bans on the spot",
        "",
        `**4. If you use \`acumular\`:** \`${P}punicao warns <number>\``,
        `**5. If you use \`confirmar\`:** you need a silence role → \`${P}cargomudo\` creates one ready to go.`,
        "",
        `**Content detection** (scams, advertising): \`${P}scam on\` and \`${P}scam sensibilidade <baixa|media|alta>\`.`,
        `**Allowed links:** \`${P}whitelist add <domain>\`.`,
        "",
        `**Manual warning:** \`${P}warn @user <reason>\` — counts alongside the automod warnings.`,
        `**Who can moderate:** \`${P}acesso cargo add <@role>\` gives moderation power to a role without touching Stoat's permissions.`,
        `**Where commands work:** \`${P}acesso canal somente\` + \`${P}acesso canal add\` limits commands to chosen channels.`,
      ],
    },

    logs: {
      titulo: "📋 Logging",
      ordem: 2,
      resumo: "Where the bot writes down what happened.",
      corpo: [
        "Create a channel (e.g. **#log**) visible only to the team. Then, **inside it**:",
        "",
        `\`${P}log canal aqui\` — sets this channel as the log channel`,
        `\`${P}log\` — shows what's being logged`,
        `\`${P}log evento <punicoes|membros|mensagens|cargos|comandos> on|off\``,
        "",
        "Logging punishments and joins/leaves is worth it; `comandos` is noisy and starts disabled.",
        "",
        "💡 The log channel is where Judy pings you when AI moderation deletes something.",
      ],
    },

    cargos: {
      titulo: "🎭 Roles",
      ordem: 3,
      resumo: "Role on join, reaction roles and the silence role.",
      corpo: [
        `**Automatic role on join:** \`${P}autorole <role-id>\``,
        "Get the ID in Settings → Roles → *Copy role ID*.",
        "",
        `**Reaction roles** (react and get the role):`,
        `1. Post the message: \`${P}embed titulo: Pick your roles | descricao: 🎮 Games · 📢 News\``,
        `2. Wire emoji → role: \`${P}reactionrole add <message> 🎮 <role-id>\``,
        "   The **message** can be the ID **or the link** (`...` menu → *Copy link*).",
        `3. Check it with \`${P}reactionrole list\``,
        `4. If only one option can apply (color, team, age): \`${P}reactionrole exclusivo <message> on\``,
        "   Then picking one emoji **swaps** the previous role instead of stacking.",
        "",
        `**Silence role** (for \`${P}silence\`): \`${P}cargomudo\``,
        "Creates a role with everything denied and blocks it across the channels.",
        "",
        `**Role colors:** \`${P}cor <role> <color>\``,
        `Takes hex, names, and even **gradients** — which the Stoat client doesn't offer:`,
        `\`${P}cor VIP gradiente #FF71CE #01CDFE #05FFA1\``,
        `\`${P}cor VIP preset vaporwave\` · \`${P}cor presets\` lists the ready-made ones`,
        `\`${P}cor painel aqui\` — **does everything**: creates the colored roles, posts the picker message, reacts and wires the reaction roles`,
      ],
    },

    xp: {
      titulo: "🎮 XP and levels",
      ordem: 4,
      resumo: "People earn XP by chatting and level up.",
      corpo: [
        `**Enable:** \`${P}xp on\``,
        `**Create the level roles:** \`${P}xp criarcargos\` (one every 10 levels)`,
        `**Adjust:** \`${P}xp setup\` shows everything you can change:`,
        `• \`${P}xp setup intervalo <5|10>\` — how many levels between roles`,
        `• \`${P}xp setup xp <min> <max>\` — how much a message earns`,
        `• \`${P}xp setup cooldown <seconds>\` — prevents spam farming`,
        `• \`${P}xp setup canal aqui|off\` — where to announce level ups`,
        "",
        `**See the ranking:** \`${P}xp top\` · **your profile:** \`${P}nivel\``,
      ],
    },

    ia: {
      titulo: "🤖 Judy (the AI)",
      ordem: 5,
      soComIA: true,
      resumo: "Chat, memory, participation and AI moderation.",
      corpo: [
        `**Test it:** \`${P}chat status\` shows whether the AI service is up.`,
        "Then just mention the bot or use `&chat <message>`.",
        "",
        `**Let her join on her own:** \`${P}chat livre on\` (in this channel)`,
        `• \`${P}chat livre modo relevante\` — only when the topic is worth it`,
        `• \`${P}chat livre modo todas\` — replies to everything`,
        "",
        `**Comments on her own initiative:** \`${P}chat comentar aqui\` · \`${P}chat comentar pordia <n>\``,
        "",
        `**Profile and memory:** \`${P}chat perfil\` shows what she knows about you.`,
        `\`${P}chat cuidado @user on\` — treats someone with extra kindness.`,
        `\`${P}chat esquecer\` erases yours; \`${P}chat esquecer tudo\` wipes the server's.`,
        "",
        `**AI moderation:** \`${P}modia criterios <what to moderate, in free text>\` then \`${P}modia on\`.`,
        "She deletes whatever violates them and pings the owner in the log — she never bans on her own.",
      ],
    },

    noticias: {
      titulo: "📰 News (RSS)",
      ordem: 6,
      resumo: "The bot posts the feeds' updates every hour.",
      corpo: [
        "Create a channel (e.g. **#news**) and, **inside it**:",
        "",
        `\`${P}rss canal aqui\` — sets where to publish`,
        `\`${P}rss add <feed-url>\` — e.g.: \`${P}rss add https://g1.globo.com/rss/g1/\``,
        `\`${P}rss list\` — registered feeds`,
        `\`${P}rss agora\` — forces a cycle to test`,
        "",
        "Every hour the bot posts the new items. Where the AI is available, Judy also writes an overall summary in her own voice.",
      ],
    },

    mensagens: {
      titulo: "✉️ Pretty messages",
      ordem: 7,
      resumo: "Publishing announcements and rules with embed styling.",
      corpo: [
        `\`${P}embed\` on its own shows the help. The format is \`field: value\`, one per line:`,
        "```",
        `${P}embed`,
        "titulo: Rules",
        "descricao: Be kind to everyone.",
        "cor: #5865F2",
        "```",
        "",
        `Or everything on one line: \`${P}embed titulo: Rules | descricao: Be kind | cor: azul\``,
        "",
        "**Fields:** `titulo` `descricao` `cor` `rodape` `imagem` `canal`.",
      ],
    },

    game: {
      titulo: "🎲 Setting up the RPG",
      ordem: 8,
      resumo: "Getting the game ready on the server — start here.",
      corpo: [
        "_This page is for the **admins**. To play, see_",
        `\`${P}tutorial rpg\`, \`${P}tutorial aventura\` and \`${P}tutorial economia\`.`,
        "",
        "**1. Nothing to install**",
        "The RPG already works: the item and companion catalog and the default",
        `currency are created on their own. Someone can type \`${P}game criar\` right now.`,
        "",
        "**2. Choose where it's played**",
        "The game's messages are long and frequent. Limiting it to one channel helps:",
        `\`${P}acesso canal somente\` and then \`${P}acesso canal add\` in the game channel.`,
        "_Moderation keeps working in the other channels normally._",
        "",
        "**3. Check everything is standing**",
        `\`${P}game admin teste\` — runs the whole game on a throwaway character`,
        "and returns ✅/❌ per stage. Use it after each bot update.",
        "",
        "**4. Program the currencies** _(optional)_",
        `\`${P}game admin moeda perfil\` — 12 ready-made currencies, pick the ones you want`,
        `   e.g. \`${P}game admin moeda perfil brl xau btc\``,
        `\`${P}game admin moeda modelo mundo\` — creates Real, Dollar, Euro, Silver,`,
        "Gold and Bitcoin already balanced, in one go. There's also `fantasia` and `simples`.",
        `\`${P}game admin moeda ajuda\` — explains each field if you want to do it by hand.`,
        "",
        "**5. Calibrate before opening**",
        `\`${P}game admin simular <mission> 500\` shows the real success and death`,
        "rates. If it's too hard or too easy, tell me and I'll adjust the numbers.",
        "",
        "**6. Clean up the tests**",
        `\`${P}game admin reset servidor confirmar\` — erases the progress and starts over.`,
        `\`${P}game admin reset tudo confirmar\` — also erases the curated catalog.`,
        "",
        `_Testing tools: \`${P}game admin\` lists them all._`,
      ],
    },

    rpg: {
      titulo: "🎲 RPG — how to play",
      ordem: 9,
      resumo: "_(for the players)_ creating a character, attributes and builds.",
      corpo: [
        `**Create:** \`${P}game criar <name>\` · **Sheet:** \`${P}game\``,
        `Someone else's sheet: \`${P}game ficha @user\``,
        "",
        "**The 9 attributes:**",
        "💪 Strength · 🎯 Dexterity · 🛡️ Endurance · 💨 Agility · ❤️ Health",
        "🔷 Mana · 🧠 Intelligence · 🍀 Luck · ✨ Charisma",
        "",
        "**How your character grows**",
        "Each level you get **free points** to spend as you like, and every",
        "2 levels **all** attributes rise by 1 on their own. The base keeps",
        "everyone viable; the free points are what shape your build.",
        "",
        `**Spending points:** \`${P}game pontos <attribute> [amount]\``,
        `Abbreviations work: \`${P}game pontos int 3\``,
        "",
        "🧠 **Intelligence** and 🍀 **Luck** boost the XP you earn **and** how",
        "many points you receive per level — with diminishing returns, so they",
        "never stop mattering and never become the only viable choice.",
        "",
        "🛡️ Health, Endurance and Agility **multiply** on defense: spreading",
        "across the three yields more than stacking a single one.",
        "",
        `**Ranking:** \`${P}game top\` · **Start over:** \`${P}game apagar confirmar\``,
        "",
        `⚠️ Don't confuse it with \`${P}xp\`: that's the server's message-based leveling.`,
        "This is the RPG, with its own character.",
        "",
        `➡️ To actually play, see \`${P}tutorial aventura\`.`,
      ],
    },

    aventura: {
      titulo: "⚔️ RPG — missions and companions",
      ordem: 10,
      resumo: "_(for the players)_ missions, items, party and dungeon.",
      corpo: [
        "**Missions**",
        `\`${P}game missao\` — list with your odds in each one`,
        `\`${P}game missao <name>\` — sets off`,
        "",
        "🏪 **Market** — no risk, no scaling: the safety net of the early game.",
        "🟢🟡🔴 **Dungeon** — three difficulties, real risk and real loot.",
        "Falling does **not** cost levels or gear — only time recovering.",
        "Recovery (~30 min) runs alongside the mission cooldown: the longer one counts.",
        "",
        "**Items**",
        `\`${P}game itens\` · \`${P}game equipar <item>\` · \`${P}game catalogo\``,
        `\`${P}game item <name>\` — price, stock and bonuses of one item`,
        `6 slots: ⚔️🪖🛡️ and 💍×3 — your sheet (\`${P}game\`) lists the empty ones too.`,
        "The commons (♾️) never run out — nobody goes without equipment.",
        "",
        "**Magic**",
        `\`${P}game magias\` — the grimoire · \`${P}game aprender <name>\``,
        "They cost **Mana** and enter from the strongest down, while it lasts.",
        "🔥 Attack raises success · ✨ Support raises survival.",
        "",
        "**Companions**",
        `\`${P}game followers\` · \`${P}game follower levar <name>\` (up to 2)`,
        `\`${P}game follower ficha <name>\` — attributes, spell, energy and bag`,
        `\`${P}game follower dar <name> <item>\` — up to 2, adding to their attributes`,
        "Both names can have spaces; if ambiguous, separate them with `|`.",
        "⚔️ Fighter · 🛡️ Tank · 🔮 Mage · ✨ Support — each with one spell.",
        "They spend ⚡energy per mission (1 comes back per hour).",
        "Bringing them **raises the difficulty** and **splits the loot**: they're",
        "worth the variety of classes and spells, not brute force.",
        "",
        "**Dungeon**",
        `If the party falls, they can be captured. \`${P}game dungeon\` shows who's held.`,
        "**The rescue is automatic:** every mission you come back from is an",
        "attempt. Completing it gives the full chance, coming back without",
        "completing gives half, falling gives none.",
        "The owner has priority for the first 6h; after that, anyone's mission frees them.",
      ],
    },

    economia: {
      titulo: "💰 RPG — economy",
      ordem: 11,
      resumo: "_(for the players)_ currency, market and prices.",
      corpo: [
        `\`${P}game carteira\` — balance and the economy's state`,
        `\`${P}game comprar [item]\` · \`${P}game vender <item>\``,
        `\`${P}game contratar [name]\` — mercenaries`,
        `\`${P}game descansar\` — companions' energy for coin`,
        "",
        "**How prices move**",
        "Everything revolves around **P**: how much of the currency the players",
        "hold, compared to what the market has.",
        "",
        "• **High P** (rich players) → cheap items, but falling costs a lot",
        "• **Low P** (full market) → expensive items, but falling costs little",
        "",
        "That pushes the wealthy to spend and the broke to take risks,",
        "without anyone having to adjust anything.",
        "",
        "**Selling to the market**",
        "The NPC pays **below** the sale price — your ✨Charisma improves the",
        "offer, and also discounts hiring mercenaries. Buying and reselling",
        "always loses money, so there's no free lunch.",
        "",
        "_The bot owner can create several currencies with different rarities_",
        `_(\`${P}game admin moeda\`)._`,
        "",
        "**Trading with other players**",
        `\`${P}game mercado\` — bazaar: list items at whatever price you want`,
        `\`${P}game comprar <item> com <currency>\` — pay with the currency you pick`,
        `\`${P}game cambio 1 bitcoin\` — what it's worth in **every** currency`,
        `\`${P}game cambio 100 ouro para prata\` — exchange **with the bank**, instantly`,
        `\`${P}game cambio 100 ouro por 5 prata\` — offer to **another player**`,
        `\`${P}game cambio taxas\` — what the bank pays today, per currency`,
        `\`${P}game trocar @user <your item> por <their item>\` — bartering`,
        "",
        "Everything goes through **escrow**: whatever you list leaves your",
        "backpack and stays with me until someone closes the deal or you cancel.",
        "Nobody lists what they don't have, and nobody gets stiffed.",
        "",
        "The fee is next to nothing day-to-day and rises with volume — never",
        "to the point of making trading not worth it.",
        "",
        "**The dungeon keeps what is lost**",
        "When you fall you lose part of what you carry, and it goes into the",
        "dungeon's pot. The fuller the pot, the bigger the winner's share.",
      ],
    },

    ajustes: {
      titulo: "⚙️ General settings",
      ordem: 12,
      resumo: "Overview, disabled commands and the global list.",
      corpo: [
        `\`${P}config\` — overview of everything configured on this server`,
        `\`${P}comando <name> on|off\` — toggles a command here`,
        `\`${P}banglobal <off|avisar|banir>\` — what to do when someone banned elsewhere joins`,
        `\`${P}idioma pt|en\` — the language I reply in on this server`,
        `\`${P}debug\` — diagnostics when something doesn't work`,
        `\`${P}debug canais\` — what the bot can see and do in EACH channel`,
        `\`${P}debug silence @user\` — checks whether the silence will actually work`,
        "",
        `And \`${P}help\` lists everything, with \`${P}help <command>\` for details.`,
      ],
    },
  };

  // ── pt ──
  return {
    permissoes: {
      titulo: "🔑 Permissões do bot",
      ordem: 0,
      resumo: "Antes de tudo: sem isso, nada funciona.",
      corpo: [
        "Em **Configurações do servidor → Cargos**, dê ao cargo do bot:",
        "",
        "**Essenciais**",
        "• `ViewChannel`, `ReadMessageHistory` — ver e ler os canais",
        "• `SendMessage`, `SendEmbeds` — responder",
        "• `React` — reações (cargos por reação, 👀 da Judy)",
        "",
        "**Para moderar**",
        "• `ManageMessages` — apagar mensagens (automod, `&limpar`)",
        "• `KickMembers`, `BanMembers` — `&kick`, `&ban`, ban global",
        "• `TimeoutMembers` — silenciar por tempo",
        "",
        "**Para gerir cargos e canais**",
        "• `ManageRole` — **criar** cargos (cargo de silêncio, cargos de nível)",
        "• `AssignRoles` — **dar** cargos a alguém (autorole, nível, reação)",
        "• `ManageChannel` — criar/editar canais",
        "",
        "⚠️ `ManageRole` e `AssignRoles` são coisas **diferentes**: uma cria o cargo, a outra entrega para a pessoa. Faltando a segunda, o bot cria os cargos e falha na hora de aplicar.",
        "",
        "💡 O cargo do bot precisa estar **acima** dos cargos que ele vai gerenciar na lista de cargos.",
      ],
    },

    moderacao: {
      titulo: "🛡️ Moderação automática",
      ordem: 1,
      resumo: "Os filtros que agem sozinhos e o que acontece com quem infringe.",
      corpo: [
        `**1. Veja o estado atual:** \`${P}automod\``,
        "Lista cada filtro (convites, spam, links, caps, menções em massa, caracteres estranhos) e se está ligado.",
        "",
        `**2. Ligue/desligue o que quiser:** \`${P}automod <filtro> on|off\``,
        `Ex.: \`${P}automod antilink on\``,
        "",
        `**3. Defina a punição:** \`${P}punicao modo <avisar|apagar|confirmar|acumular|banir>\``,
        "• `avisar` — só avisa (bom para testar)",
        "• `apagar` — remove a mensagem, não pune a pessoa",
        "• `confirmar` — apaga, silencia e chama um moderador",
        "• `acumular` — dá avisos e bane ao atingir o limite",
        "• `banir` — bane na hora",
        "",
        `**4. Se usar \`acumular\`:** \`${P}punicao warns <número>\``,
        `**5. Se usar \`confirmar\`:** precisa de um cargo de silêncio → \`${P}cargomudo\` cria um pronto.`,
        "",
        `**Detecção de conteúdo** (golpes, divulgação): \`${P}scam on\` e \`${P}scam sensibilidade <baixa|media|alta>\`.`,
        `**Links permitidos:** \`${P}whitelist add <domínio>\`.`,
        "",
        `**Aviso manual:** \`${P}warn @pessoa <motivo>\` — conta junto com os avisos do automod.`,
        `**Quem pode moderar:** \`${P}acesso cargo add <@cargo>\` dá poder de moderação a um cargo, sem precisar mexer nas permissões do Stoat.`,
        `**Onde os comandos valem:** \`${P}acesso canal somente\` + \`${P}acesso canal add\` limita os comandos a canais escolhidos.`,
      ],
    },

    logs: {
      titulo: "📋 Registro (logs)",
      ordem: 2,
      resumo: "Onde o bot anota o que aconteceu.",
      corpo: [
        "Crie um canal (ex.: **#log**) visível só para a equipe. Depois, **dentro dele**:",
        "",
        `\`${P}log canal aqui\` — define este canal como o de registro`,
        `\`${P}log\` — mostra o que está sendo registrado`,
        `\`${P}log evento <punicoes|membros|mensagens|cargos|comandos> on|off\``,
        "",
        "Vale registrar punições e entradas/saídas; `comandos` é ruidoso e começa desligado.",
        "",
        "💡 É no canal de log que a Judy te marca quando a moderação por IA apaga algo.",
      ],
    },

    cargos: {
      titulo: "🎭 Cargos",
      ordem: 3,
      resumo: "Cargo ao entrar, cargos por reação e cargo de silêncio.",
      corpo: [
        `**Cargo automático para quem entra:** \`${P}autorole <id-do-cargo>\``,
        "Pegue o ID em Configurações → Cargos → *Copy role ID*.",
        "",
        `**Cargos por reação** (a pessoa reage e ganha o cargo):`,
        `1. Publique a mensagem: \`${P}embed titulo: Escolha seus cargos | descricao: 🎮 Jogos · 📢 Avisos\``,
        `2. Ligue emoji → cargo: \`${P}reactionrole add <mensagem> 🎮 <id-do-cargo>\``,
        "   A **mensagem** pode ser o ID **ou o link** (menu `...` → *Copiar link*).",
        `3. Confira com \`${P}reactionrole list\``,
        `4. Se só uma opção pode valer (cor, time, idade): \`${P}reactionrole exclusivo <mensagem> on\``,
        "   Aí escolher um emoji **troca** o cargo anterior em vez de acumular.",
        "",
        `**Cargo de silêncio** (para \`${P}silence\`): \`${P}cargomudo\``,
        "Cria um cargo com tudo negado e já bloqueia nos canais.",
        "",
        `**Cor dos cargos:** \`${P}cor <cargo> <cor>\``,
        `Aceita hex, nome, e até **gradiente** — que o cliente do Stoat não oferece:`,
        `\`${P}cor VIP gradiente #FF71CE #01CDFE #05FFA1\``,
        `\`${P}cor VIP preset vaporwave\` · \`${P}cor presets\` lista os prontos`,
        `\`${P}cor painel aqui\` — **faz tudo**: cria os cargos coloridos, publica a mensagem de escolha, reage e liga os cargos por reação`,
      ],
    },

    xp: {
      titulo: "🎮 XP e níveis",
      ordem: 4,
      resumo: "As pessoas ganham XP conversando e sobem de nível.",
      corpo: [
        `**Ligar:** \`${P}xp on\``,
        `**Criar os cargos de nível:** \`${P}xp criarcargos\` (um a cada 10 níveis)`,
        `**Ajustar:** \`${P}xp setup\` mostra tudo que dá para mudar:`,
        `• \`${P}xp setup intervalo <5|10>\` — de quantos em quantos níveis dar cargo`,
        `• \`${P}xp setup xp <min> <max>\` — quanto ganha por mensagem`,
        `• \`${P}xp setup cooldown <segundos>\` — evita farm por spam`,
        `• \`${P}xp setup canal aqui|off\` — onde anunciar o level up`,
        "",
        `**Ver o ranking:** \`${P}xp top\` · **seu perfil:** \`${P}nivel\``,
      ],
    },

    ia: {
      titulo: "🤖 A Judy (IA)",
      ordem: 5,
      soComIA: true,
      resumo: "Conversa, memória, participação e moderação por IA.",
      corpo: [
        `**Testar:** \`${P}chat status\` mostra se o serviço de IA está no ar.`,
        "Depois é só mencionar o bot ou usar `&chat <mensagem>`.",
        "",
        `**Deixar ela participar sozinha:** \`${P}chat livre on\` (neste canal)`,
        `• \`${P}chat livre modo relevante\` — só quando o assunto vale`,
        `• \`${P}chat livre modo todas\` — responde tudo`,
        "",
        `**Comentários por iniciativa:** \`${P}chat comentar aqui\` · \`${P}chat comentar pordia <n>\``,
        "",
        `**Perfil e memória:** \`${P}chat perfil\` mostra o que ela sabe de você.`,
        `\`${P}chat cuidado @pessoa on\` — trata alguém com gentileza extra.`,
        `\`${P}chat esquecer\` apaga o seu; \`${P}chat esquecer tudo\` zera o servidor.`,
        "",
        `**Moderação por IA:** \`${P}modia criterios <o que moderar, em texto livre>\` e depois \`${P}modia on\`.`,
        "Ela apaga o que violar e marca o dono no log — nunca bane sozinha.",
      ],
    },

    noticias: {
      titulo: "📰 Notícias (RSS)",
      ordem: 6,
      resumo: "O bot posta as novidades dos feeds a cada hora.",
      corpo: [
        "Crie um canal (ex.: **#noticias**) e, **dentro dele**:",
        "",
        `\`${P}rss canal aqui\` — define onde publicar`,
        `\`${P}rss add <url-do-feed>\` — ex.: \`${P}rss add https://g1.globo.com/rss/g1/\``,
        `\`${P}rss list\` — feeds cadastrados`,
        `\`${P}rss agora\` — força um ciclo para testar`,
        "",
        "A cada hora o bot posta os itens novos. Onde a IA está disponível, a Judy escreve também um resumo geral no tom dela.",
      ],
    },

    mensagens: {
      titulo: "✉️ Mensagens bonitas",
      ordem: 7,
      resumo: "Publicar avisos e regras com visual de embed.",
      corpo: [
        `\`${P}embed\` sozinho mostra a ajuda. O formato é \`campo: valor\`, um por linha:`,
        "```",
        `${P}embed`,
        "titulo: Regras",
        "descricao: Seja legal com todos.",
        "cor: #5865F2",
        "```",
        "",
        `Ou tudo numa linha: \`${P}embed titulo: Regras | descricao: Seja legal | cor: azul\``,
        "",
        "**Campos:** `titulo` `descricao` `cor` `rodape` `imagem` `canal`.",
      ],
    },

    game: {
      titulo: "🎲 Configurar o RPG",
      ordem: 8,
      resumo: "Deixar o jogo pronto no servidor — comece por aqui.",
      corpo: [
        "_Esta página é para quem **administra**. Para jogar, veja_",
        `\`${P}tutorial rpg\`, \`${P}tutorial aventura\` e \`${P}tutorial economia\`.`,
        "",
        "**1. Não precisa instalar nada**",
        "O RPG já funciona: o catálogo de itens e companheiros e a moeda padrão",
        `são criados sozinhos. Alguém pode digitar \`${P}game criar\` agora mesmo.`,
        "",
        "**2. Escolha onde se joga**",
        "As mensagens do jogo são longas e frequentes. Vale limitar a um canal:",
        `\`${P}acesso canal somente\` e depois \`${P}acesso canal add\` no canal do jogo.`,
        "_A moderação continua funcionando nos outros canais normalmente._",
        "",
        "**3. Confira que está tudo de pé**",
        `\`${P}game admin teste\` — roda o jogo inteiro num personagem descartável`,
        "e devolve ✅/❌ por etapa. Use depois de cada atualização do bot.",
        "",
        "**4. Programe as moedas** _(opcional)_",
        `\`${P}game admin moeda perfil\` — 12 moedas prontas, escolha as que quiser`,
        `   ex.: \`${P}game admin moeda perfil brl xau btc\``,
        `\`${P}game admin moeda modelo mundo\` — cria Real, Dólar, Euro, Prata,`,
        "Ouro e Bitcoin já balanceados, de uma vez. Há também `fantasia` e `simples`.",
        `\`${P}game admin moeda ajuda\` — explica cada campo se quiser fazer à mão.`,
        "",
        "**5. Calibre antes de abrir**",
        `\`${P}game admin simular <missão> 500\` mostra a taxa real de sucesso e`,
        "morte. Se estiver duro ou fácil demais, me avise que ajusto os números.",
        "",
        "**6. Limpe os testes**",
        `\`${P}game admin reset servidor confirmar\` — apaga o progresso e recomeça.`,
        `\`${P}game admin reset tudo confirmar\` — apaga também o catálogo curado.`,
        "",
        `_Ferramentas de teste: \`${P}game admin\` lista todas._`,
      ],
    },

    rpg: {
      titulo: "🎲 RPG — como jogar",
      ordem: 9,
      resumo: "_(para os jogadores)_ criar personagem, atributos e build.",
      corpo: [
        `**Criar:** \`${P}game criar <nome>\` · **Ficha:** \`${P}game\``,
        `Ficha de outra pessoa: \`${P}game ficha @pessoa\``,
        "",
        "**Os 9 atributos:**",
        "💪 Força · 🎯 Destreza · 🛡️ Resistência · 💨 Agilidade · ❤️ Vida",
        "🔷 Mana · 🧠 Inteligência · 🍀 Sorte · ✨ Carisma",
        "",
        "**Como o personagem cresce**",
        "A cada nível você ganha **pontos livres** para gastar como quiser, e a",
        "cada 2 níveis **todos** os atributos sobem 1 sozinhos. A base garante",
        "que ninguém fique inviável; os pontos livres é que fazem a sua build.",
        "",
        `**Distribuir pontos:** \`${P}game pontos <atributo> [quantos]\``,
        `Aceita abreviação: \`${P}game pontos int 3\``,
        "",
        "🧠 **Inteligência** e 🍀 **Sorte** aumentam o XP que você ganha **e**",
        "quantos pontos recebe por nível — com retorno decrescente, então nunca",
        "param de valer e nunca viram a única escolha possível.",
        "",
        "🛡️ Vida, Resistência e Agilidade se **multiplicam** na defesa: espalhar",
        "entre as três rende mais que empilhar numa só.",
        "",
        `**Ranking:** \`${P}game top\` · **Recomeçar:** \`${P}game apagar confirmar\``,
        "",
        `⚠️ Não confunda com \`${P}xp\`: aquele é o nível por mensagens do servidor.`,
        "Este é o RPG, com personagem próprio.",
        "",
        `➡️ Para jogar de fato, veja \`${P}tutorial aventura\`.`,
      ],
    },

    aventura: {
      titulo: "⚔️ RPG — missões e companheiros",
      ordem: 10,
      resumo: "_(para os jogadores)_ missões, itens, party e dungeon.",
      corpo: [
        "**Missões**",
        `\`${P}game missao\` — lista com sua chance em cada uma`,
        `\`${P}game missao <nome>\` — parte`,
        "",
        "🏪 **Mercado** — sem risco e sem escala: rede de segurança do começo.",
        "🟢🟡🔴 **Dungeon** — três dificuldades, risco real e loot de verdade.",
        "Cair **não** custa nível nem equipamento — só tempo se recuperando.",
        "A recuperação (~30 min) corre junto com o cooldown da missão: vale a maior.",
        "",
        "**Itens**",
        `\`${P}game itens\` · \`${P}game equipar <item>\` · \`${P}game catalogo\``,
        `\`${P}game item <nome>\` — preço, estoque e bônus de um item`,
        `6 slots: ⚔️🪖🛡️ e 💍×3 — sua ficha (\`${P}game\`) lista os vazios também.`,
        "Os comuns (♾️) nunca acabam — ninguém fica sem equipamento.",
        "",
        "**Magia**",
        `\`${P}game magias\` — o grimório · \`${P}game aprender <nome>\``,
        "Custam **Mana** e entram da mais forte para a mais fraca, enquanto ela durar.",
        "🔥 Ataque sobe o êxito · ✨ Suporte sobe a sobrevivência.",
        "",
        "**Companheiros**",
        `\`${P}game followers\` · \`${P}game follower levar <nome>\` (até 2)`,
        `\`${P}game follower ficha <nome>\` — atributos, magia, energia e mochila`,
        `\`${P}game follower dar <nome> <item>\` — carrega até 2, que somam nos atributos dele`,
        "Os dois nomes podem ter espaço; se ficar ambíguo, separe com `|`.",
        "⚔️ Combatente · 🛡️ Tank · 🔮 Mago · ✨ Suporte — cada um com uma magia.",
        "Gastam ⚡energia por missão (volta 1 por hora).",
        "Levá-los **aumenta a dificuldade** e **divide o loot**: valem pela",
        "variedade de classes e magias, não por força bruta.",
        "",
        "**Dungeon**",
        `Se a party cair, eles podem ser capturados. \`${P}game dungeon\` mostra quem está preso.`,
        "**O resgate é automático:** toda missão de que você volta é uma tentativa.",
        "Cumprir dá a chance cheia, voltar sem cumprir dá metade, cair não dá nenhuma.",
        "O dono tem prioridade nas primeiras 6h; depois, a missão de qualquer um solta.",
      ],
    },

    economia: {
      titulo: "💰 RPG — economia",
      ordem: 11,
      resumo: "_(para os jogadores)_ moeda, mercado e preços.",
      corpo: [
        `\`${P}game carteira\` — saldo e o estado da economia`,
        `\`${P}game comprar [item]\` · \`${P}game vender <item>\``,
        `\`${P}game contratar [nome]\` — mercenários`,
        `\`${P}game descansar\` — energia dos companheiros por moeda`,
        "",
        "**Como os preços se movem**",
        "Tudo gira em torno do **P**: quanto da moeda está com os jogadores,",
        "comparado ao que o mercado tem.",
        "",
        "• **P alto** (jogadores ricos) → itens baratos, mas cair custa caro",
        "• **P baixo** (mercado cheio) → itens caros, mas cair custa pouco",
        "",
        "Isso empurra quem tem dinheiro a gastar e quem não tem a arriscar,",
        "sem ninguém precisar ajustar nada.",
        "",
        "**Vender ao mercado**",
        "O NPC paga **abaixo** do preço de venda — seu ✨Carisma melhora a",
        "oferta, e também dá desconto ao contratar mercenários. Comprar e",
        "revender sempre dá prejuízo, então não existe dinheiro fácil.",
        "",
        "_O dono do bot pode criar várias moedas com raridades diferentes_",
        `_(\`${P}game admin moeda\`)._`,
        "",
        "**Negociar com outros jogadores**",
        `\`${P}game mercado\` — bazar: anuncie itens pelo preço que quiser`,
        `\`${P}game comprar <item> com <moeda>\` — paga com a moeda que você escolher`,
        `\`${P}game cambio 1 bitcoin\` — quanto vale em **todas** as moedas`,
        `\`${P}game cambio 100 ouro para prata\` — troca **com o banco**, na hora`,
        `\`${P}game cambio 100 ouro por 5 prata\` — oferta a **outro jogador**`,
        `\`${P}game cambio taxas\` — quanto o banco paga hoje, de cada moeda`,
        `\`${P}game trocar @pessoa <seu item> por <item dela>\` — escambo`,
        "",
        "Tudo passa por **custódia**: o que você anuncia sai da sua mochila e",
        "fica comigo até alguém fechar ou você cancelar. Ninguém anuncia o que",
        "não tem, e não existe calote.",
        "",
        "A taxa é quase nada no dia a dia e sobe com o movimento — nunca a ponto",
        "de inviabilizar negociar.",
        "",
        "**A dungeon guarda o que se perde**",
        "Ao cair você perde parte do que carrega, e isso vai para o pote da",
        "dungeon. Quanto mais cheio o pote, maior a fatia que o vencedor leva.",
      ],
    },

    ajustes: {
      titulo: "⚙️ Ajustes gerais",
      ordem: 12,
      resumo: "Panorama, comandos desativados e lista global.",
      corpo: [
        `\`${P}config\` — panorama de tudo que está configurado neste servidor`,
        `\`${P}comando <nome> on|off\` — liga/desliga um comando aqui`,
        `\`${P}banglobal <off|avisar|banir>\` — o que fazer quando entra alguém banido em outro servidor`,
        `\`${P}idioma pt|en\` — em que idioma eu respondo neste servidor`,
        `\`${P}debug\` — diagnóstico quando algo não funciona`,
        `\`${P}debug canais\` — o que o bot enxerga e pode fazer em CADA canal`,
        `\`${P}debug silence @pessoa\` — checa se o silêncio vai funcionar mesmo`,
        "",
        `E \`${P}help\` lista tudo, com \`${P}help <comando>\` para detalhes.`,
      ],
    },
  };
}

const APELIDOS = {
  permissao: "permissoes", permissões: "permissoes", perms: "permissoes", bot: "permissoes",
  permissions: "permissoes",
  automod: "moderacao", moderação: "moderacao", punicao: "moderacao", punição: "moderacao", filtros: "moderacao",
  moderation: "moderacao", filters: "moderacao",
  log: "logs", registro: "logs", logging: "logs",
  cargo: "cargos", autorole: "cargos", reactionrole: "cargos", roles: "cargos",
  nivel: "xp", niveis: "xp", "níveis": "xp", level: "xp", levels: "xp",
  personagem: "rpg", jogo: "rpg", ficha: "rpg", character: "rpg",
  configurar: "game", "configuração": "game", admin: "game", setup: "game",
  missao: "aventura", missoes: "aventura", itens: "aventura",
  missions: "aventura", adventure: "aventura", items: "aventura",
  moeda: "economia", mercado: "economia", loja: "economia", carteira: "economia",
  economy: "economia", market: "economia", wallet: "economia",
  followers: "aventura", party: "aventura", dungeon: "aventura",
  judy: "ia", chat: "ia", modia: "ia", ai: "ia",
  rss: "noticias", feed: "noticias", "notícias": "noticias", news: "noticias",
  embed: "mensagens", avisos: "mensagens", messages: "mensagens", embeds: "mensagens",
  config: "ajustes", geral: "ajustes", settings: "ajustes", general: "ajustes",
};

export async function cmdTutorial(message, args, ctx) {
  const { sendEmbed, COR, PREFIXO: P } = ctx;
  const lang = lingua(ctx);

  // A IA só roda nos servidores da allowlist. Mostrar essa área onde ela não
  // funciona é pior que omitir: a pessoa tenta e nada acontece.
  const comIA = (() => { try { return temIA(ctx.serverId); } catch { return false; } })();

  const todas = AREAS(P, lang);
  const areas = {};
  for (const [k, v] of Object.entries(todas)) {
    if (v.soComIA && !comIA) continue;
    areas[k] = v;
  }
  const pedido = args[0]?.toLowerCase();

  // ── Página de uma área ──
  if (pedido) {
    const chave = areas[pedido] ? pedido : APELIDOS[pedido];
    const area = chave ? areas[chave] : null;
    if (!area) {
      const nomes = Object.keys(areas).map((k) => `\`${k}\``).join(" · ");
      return sendEmbed(message.channel, lang === "en" ? {
        title: "❓ Unknown area",
        description: `I don't know that area. The existing ones:\n${nomes}\n\nOr use \`${P}tutorial\` to see the full walkthrough.`,
        colour: COR.aviso,
      } : {
        title: "❓ Área desconhecida",
        description: `Não conheço essa área. As que existem:\n${nomes}\n\nOu use \`${P}tutorial\` para ver o roteiro completo.`,
        colour: COR.aviso,
      });
    }
    const ordem = Object.entries(areas).sort((a, b) => a[1].ordem - b[1].ordem).map(([k]) => k);
    const i = ordem.indexOf(chave);
    const prox = ordem[i + 1];
    const rodape = prox
      ? (lang === "en"
        ? `\n\n➡️ Next area: \`${P}tutorial ${prox}\` (${areas[prox].titulo})`
        : `\n\n➡️ Próxima área: \`${P}tutorial ${prox}\` (${areas[prox].titulo})`)
      : (lang === "en"
        ? `\n\n✅ That's the last area. \`${P}config\` shows how everything turned out.`
        : `\n\n✅ Essa é a última área. \`${P}config\` mostra como tudo ficou.`);
    return sendEmbed(message.channel, {
      title: area.titulo,
      description: area.corpo.join("\n").slice(0, 1900) + rodape,
      colour: COR.info,
    });
  }

  // ── Roteiro geral ──
  const ordenadas = Object.entries(areas).sort((a, b) => a[1].ordem - b[1].ordem);
  const linhas = [
    lang === "en"
      ? "A new server usually gets ready in this order. **Nothing is mandatory** — skip whatever doesn't make sense for you."
      : "Um servidor novo costuma ficar pronto nesta ordem. **Nada é obrigatório** — pule o que não fizer sentido para você.",
    "",
  ];
  for (const [chave, a] of ordenadas) {
    linhas.push(`**${a.ordem === 0 ? "⚠️" : a.ordem + "."} ${a.titulo}**`);
    linhas.push(`${a.resumo}`);
    linhas.push(`\`${P}tutorial ${chave}\``);
    linhas.push("");
  }
  linhas.push(lang === "en"
    ? `Each page brings the exact commands. \`${P}help\` lists every command, \`${P}config\` shows the server's current state.`
    : `Cada página traz os comandos exatos. \`${P}help\` lista todos os comandos, \`${P}config\` mostra o estado atual do servidor.`);

  return sendEmbed(message.channel, {
    title: lang === "en" ? "📚 Where to start" : "📚 Por onde começar",
    description: linhas.join("\n").slice(0, 1950),
    colour: COR.info,
  });
}
